- alias: KNX relative dimming Stehlampe WZ
  id: 'knx_relative_dimming_stehlampe_wz'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.innr_e27_color_stehlampe_wz_level_light_color_on_off
      switch_address: '1/6/80'
      dimm_address: '1/6/82'
      dimm_time: 5
      dimm_steps: 10
- alias: KNX relative dimming Stehlampe Lea
  id: 'knx_relative_dimming_stehlampe_lea'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.innr_e14_tw_stehlampe_lea_level_light_color_on_off
      switch_address: '1/6/0'
      dimm_address: '1/6/2'
      dimm_time: 5
      dimm_steps: 10
- alias: KNX relative dimming Stehlampe Lara
  id: 'knx_relative_dimming_stehlampe_lara'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.innr_e14_ww_stehlampe_lara_level_on_off
      switch_address: '1/5/200'
      dimm_address: '1/5/202'
      dimm_time: 5
      dimm_steps: 10
- alias: KNX relative dimming Panel Arbeitszimmer
  id: 'knx_relative_dimming_panel_arbeitszimmer'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.ikea_panel_arbeitszimmer_esphome
      switch_address: '1/6/120'
      dimm_address: '1/6/122'
      dimm_time: 5
      dimm_steps: 10
- id: '1637055201020'
  alias: Test Licht GZ 2
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.automation_switch_light_o_gz_deckenlicht
    id: app_switch
    to: 'on'
  - platform: homeassistant
    event: start
    id: ha_start
  - platform: state
    entity_id: binary_sensor.helper_light_trigger_o_gz_deckenlicht
    id: motion
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
          - condition: trigger
            id: app_switch
          - condition: trigger
            id: ha_start
      sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.helper_light_auto_switched_o_gz_deckenlicht
      - choose:
        - conditions:
          - condition: state
            entity_id: binary_sensor.helper_light_keeping_fix_entities_o_gz_deckenlicht
            state: 'off'
          sequence:
          - choose:
            - conditions:
              - condition: state
                entity_id: binary_sensor.helper_light_trigger_o_gz_deckenlicht
                state: 'on'
              sequence:
              - choose:
                - conditions:
                  - condition: state
                    entity_id: binary_sensor.helper_light_is_too_dark_o_gz_deckenlicht
                    state: 'on'
                  sequence:
                  - condition: state
                    entity_id: input_boolean.automation_switch_light_o_gz_deckenlicht
                    state: 'on'
                  - condition: state
                    state: 'off'
                    entity_id: binary_sensor.helper_light_keeping_off_entities_o_gz_deckenlicht
                  - condition: state
                    state: 'off'
                    entity_id: input_boolean.helper_light_manually_switched_off_o_gz_deckenlicht
                  - choose:
                    - conditions:
                      - condition: state
                        entity_id: light.innr_e14_ww_decke_gastezimmer_level_on_off
                        state: 'off'
                      sequence:
                      - service: input_boolean.turn_on
                        target:
                          entity_id: input_boolean.helper_light_auto_switched_o_gz_deckenlicht
                    default: []
                  - service: light.turn_on
                    target:
                      entity_id: light.innr_e14_ww_decke_gastezimmer_level_on_off
                    data:
                      transition: 2
                      brightness_pct: 75
                default: []
            default: []
        default: []
    default: []
  mode: queued
  max: 10
#
#
#
# --- Regal ---
#
#
- id: '1637055201021'
  alias: Test Licht Regal Bad EG
  description: ''
  variables:
    transition_time: 1
  trigger:
  - platform: state
    entity_id: input_boolean.automation_switch_light_e_ba_regal
    id: app_switch
    to: 'on'
  - platform: homeassistant
    event: start
    id: ha_start
  - platform: state
    entity_id: binary_sensor.helper_light_trigger_e_ba_regal
    id: motion_on
    from: "off"
    to: "on"
  - platform: state
    entity_id: binary_sensor.helper_light_trigger_e_ba_regal
    id: motion_off
    from: "on"
    to: "off"
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
          - condition: trigger
            id: app_switch
          - condition: trigger
            id: ha_start
      sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.helper_light_auto_switched_e_ba_regal
      - choose:
        - conditions:
          - condition: state
            entity_id: binary_sensor.helper_light_keeping_fix_entities_e_ba_regal
            state: 'off'
          sequence:
          - choose:
            - conditions:
              - condition: state
                entity_id: binary_sensor.helper_light_trigger_e_ba_regal
                state: 'on'
              sequence:
              - choose:
                - conditions:
                  - condition: state
                    entity_id: binary_sensor.helper_light_is_too_dark_e_ba_regal
                    state: 'on'
                  sequence:
                  - condition: state
                    entity_id: input_boolean.automation_switch_light_e_ba_regal
                    state: 'on'
                  - condition: state
                    state: 'off'
                    entity_id: binary_sensor.helper_light_keeping_off_entities_e_ba_regal
                  - condition: state
                    state: 'off'
                    entity_id: input_boolean.helper_light_manually_switched_off_e_ba_regal
                  - choose:
                    - conditions:
                      - condition: state
                        entity_id: light.regal_bad_eg
                        state: 'off'
                      sequence:
                      - service: input_boolean.turn_on
                        target:
                          entity_id: input_boolean.helper_light_auto_switched_e_ba_regal
                    default: []
                  - service: light.turn_on
                    target:
                      entity_id: light.regal_bad_eg
                    data_template:
                      brightness: >
                        {{ states('sensor.helper_light_effective_brightness_e_ba_regal') | int(80) }}
                      transition: >
                        {{ transition_time }}
                # path 2
                - conditions:
                  - condition: state
                    entity_id: binary_sensor.helper_light_is_too_bright_e_ba_regal
                    state: 'on'
                  sequence:
                  - condition: state
                    entity_id: input_boolean.automation_switch_light_e_ba_regal
                    state: 'on'
                  - condition: state
                    state: 'off'
                    entity_id: binary_sensor.helper_light_keeping_on_entities_e_ba_regal
                  - condition: state
                    state: 'off'
                    entity_id: input_boolean.helper_light_manually_switched_on_e_ba_regal
                  - choose:
                    - conditions:
                      - condition: state
                        entity_id: light.regal_bad_eg
                        state: 'on'
                      sequence:
                      - service: input_boolean.turn_on
                        target:
                          entity_id: input_boolean.helper_light_auto_switched_e_ba_regal
                    default: []
                  - service: light.turn_off
                    target:
                      entity_id: light.regal_bad_eg
                default: []
            - conditions:
              - condition: state
                entity_id: binary_sensor.helper_light_trigger_e_ba_regal
                state: 'off'
              sequence:
              - condition: state
                entity_id: input_boolean.automation_switch_light_e_ba_regal
                state: 'on'
              - condition: state
                state: 'off'
                entity_id: binary_sensor.helper_light_keeping_on_entities_e_ba_regal
              - choose:
                - conditions:
                  - condition: state
                    entity_id: light.regal_bad_eg
                    state: 'on'
                  sequence:
                  - service: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.helper_light_auto_switched_e_ba_regal
                default: []
              - service: light.turn_off
                target:
                  entity_id: light.regal_bad_eg
            default: []
        # path 4
        - conditions:
          - condition: state
            entity_id: binary_sensor.helper_light_keeping_fix_entities_e_ba_regal
            state: 'on'
          sequence:
          - condition: state
            entity_id: input_boolean.automation_switch_light_e_ba_regal
            state: 'on'
          - choose:
            - conditions:
              - condition: state
                entity_id: light.regal_bad_eg
                state: 'off'
              sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.helper_light_auto_switched_e_ba_regal
            default: []
          - service: light.turn_on
            target:
              entity_id: light.regal_bad_eg
            data_template:
              brightness: >
                {{ states('sensor.helper_light_effective_brightness_e_ba_regal') | int(80) }}
              transition: >
                {{ transition_time }}
        default: []
    # path 5
    - conditions:
      - condition: trigger
        id: motion_on
      sequence:
      - condition: state
        entity_id: input_boolean.automation_switch_light_e_ba_regal
        state: 'on'
      - condition: state
        entity_id: binary_sensor.helper_light_keeping_off_entities_e_ba_regal
        state: 'off'
      - condition: state
        entity_id: binary_sensor.helper_light_keeping_fix_entities_e_ba_regal
        state: 'off'
      - condition: state
        entity_id: input_boolean.helper_light_manually_switched_off_e_ba_regal
        state: 'off'
      - condition: state
        entity_id: binary_sensor.helper_light_is_too_dark_e_ba_regal
        state: 'on'
      - choose:
        - conditions:
          - condition: state
            entity_id: light.regal_bad_eg
            state: 'off'
          sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.helper_light_auto_switched_e_ba_regal
        default: []
      - service: light.turn_on
        target:
          entity_id: light.regal_bad_eg
        data_template:
          brightness: >
            {{ states('sensor.helper_light_effective_brightness_e_ba_regal') | int(80) }}
          transition: >
            {{ transition_time }}
    # path 6
    - conditions:
      - condition: trigger
        id: motion_off
      sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.helper_light_manually_switched_on_e_ba_regal
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.helper_light_manually_switched_off_e_ba_regal
      - condition: state
        entity_id: input_boolean.automation_switch_light_e_ba_regal
        state: 'on'
      - condition: state
        entity_id: binary_sensor.helper_light_keeping_on_entities_e_ba_regal
        state: 'off'
      - condition: state
        entity_id: binary_sensor.helper_light_keeping_fix_entities_e_ba_regal
        state: 'off'
      - choose:
        - conditions:
          - condition: state
            entity_id: light.regal_bad_eg
            state: 'on'
          sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.helper_light_auto_switched_e_ba_regal
        default: []
      - service: light.turn_off
        target:
          entity_id: light.regal_bad_eg
    default: []
  mode: queued
  max: 10