- id: test_light_gz
  alias: Test - Licht GZ
  trigger:
  - platform: state
    entity_id: binary_sensor.helper_light_o_gz_deckenlicht_trigger
    to: 'on'
    id: motion
  - platform: state
    entity_id: binary_sensor.helper_light_o_gz_deckenlicht_keeping_fix_entities
    to: 'on'
    id: keeping_fix
  - platform: state
    entity_id:
    - switch.gaste_schlafen
    - switch.luften_le
    to: 'on'
    id: switching_off
  - platform: state
    entity_id: sensor.helligkeit_gastezimmer_pm
    id: illuminance_sensor
  - platform: state
    entity_id: sensor.helper_light_o_gz_deckenlicht_min_illuminance
    id: min_illuminance
  condition:
  - condition: state
    entity_id: input_boolean.app_switch_licht_gaestezimmer
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: motion
      - condition: template
        value_template: ''
      sequence:
      - choose:
        - conditions:
          - condition: device
            device_id: ''
            domain: ''
            entity_id: ''
          sequence: []
        default: []
    default: []

- alias: KNX relative dimming Stehlampe WZ
  id: 'knx_relative_dimming_stehlampe_wz'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.innr_e27_color_stehlampe_wz_level_light_color_on_off
      switch_address: '1/6/80'
      dimm_address: '1/6/82'
      dimm_time: 5
      dimm_steps: 10
- alias: KNX relative dimming Stehlampe Lea
  id: 'knx_relative_dimming_stehlampe_lea'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.innr_e14_tw_stehlampe_lea_level_light_color_on_off
      switch_address: '1/6/0'
      dimm_address: '1/6/2'
      dimm_time: 5
      dimm_steps: 10
- alias: KNX relative dimming Stehlampe Lara
  id: 'knx_relative_dimming_stehlampe_lara'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.innr_e14_ww_stehlampe_lara_level_on_off
      switch_address: '1/5/200'
      dimm_address: '1/5/202'
      dimm_time: 5
      dimm_steps: 10
- alias: KNX relative dimming Panel Arbeitszimmer
  id: 'knx_relative_dimming_panel_arbeitszimmer'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.ikea_panel_arbeitszimmer_esphome
      switch_address: '1/6/120'
      dimm_address: '1/6/122'
      dimm_time: 5
      dimm_steps: 10
- id: '1637055201020'
  alias: Test Licht GZ 2
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.automation_switch_licht_gz_decke
    id: app_switch
    to: 'on'
  - platform: state
    entity_id: binary_sensor.helper_light_o_gz_deckenlicht_trigger
    id: motion
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: app_switch
      sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.helper_light_o_gz_deckenlicht_auto_switched
      - choose:
        - conditions:
          - condition: state
            entity_id: binary_sensor.helper_light_o_gz_deckenlicht_keeping_fix_entities
            state: 'off'
          sequence:
          - choose:
            - conditions:
              - condition: state
                entity_id: binary_sensor.helper_light_o_gz_deckenlicht_trigger
                state: 'on'
              sequence:
              - choose:
                - conditions:
                  - condition: state
                    entity_id: binary_sensor.helper_light_o_gz_deckenlicht_is_too_dark
                    state: 'on'
                  sequence:
                  - condition: state
                    entity_id: input_boolean.automation_switch_licht_gz_decke
                    state: 'on'
                  - condition: state
                    state: 'off'
                    entity_id: binary_sensor.helper_light_o_gz_deckenlicht_keeping_off_entities
                  - condition: state
                    state: 'off'
                    entity_id: input_boolean.helper_light_o_gz_deckenlicht_manually_switched_off
                  - choose:
                    - conditions:
                      - condition: state
                        entity_id: light.innr_e14_ww_decke_gastezimmer_level_on_off
                        state: 'off'
                        sequence:
                        - service: input_boolean.turn_on
                          target:
                            entity_id: input_boolean.helper_light_o_gz_deckenlicht_auto_switched
                        - service: light.turn_on
                          target:
                            entity_id: light.innr_e14_ww_decke_gastezimmer_level_on_off
                          data:
                            transition: 2
                      - condition: state
                        entity_id: light.innr_e14_ww_decke_gastezimmer_level_on_off
                        state: 'on'
                        sequence:
                        - service: light.turn_on
                          target:
                            entity_id: light.innr_e14_ww_decke_gastezimmer_level_on_off
                          data:
                            transition: 2
                    default: []
                default: []
            default: []
        default: []
    default: []
  mode: queued
  max: 10