- alias: Test - Licht GZ
  id: 'test_light_gz'

  trigger:
    - platform: state
      entity_id: binary_sensor.helper_light_o_gz_deckenlicht_trigger
      to: 'on'
      id: 'motion'
    - platform: state
      entity_id: binary_sensor.helper_light_o_gz_deckenlicht_keeping_fix_entities
      to: 'on'
      id: 'keeping_fix'
    - platform: state
      entity_id: 
        - switch.gaste_schlafen
        - switch.luften_le
      to: 'on'
      id: 'switching_off'
    - platform: state
      entity_id: sensor.helligkeit_gastezimmer_pm
      id: 'illuminance_sensor'
    - platform: state
      entity_id: sensor.helper_light_o_gz_deckenlicht_min_illuminance
      id: 'min_illuminance'

  action:
    - delay: 0:01
#    - choose:
#	    - conditions:
#        - condition: trigger
#          id: motion

- alias: KNX relative dimming Stehlampe WZ
  id: 'knx_relative_dimming_stehlampe_wz'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights: light.innr_e27_color_stehlampe_wz_level_light_color_on_off
      switch_address: '1/6/80'
      dimm_address: '1/6/82'
      dimm_time: 5
      dimm_steps: 20
- alias: KNX relative dimming Stehlampe Lea
  id: 'knx_relative_dimming_stehlampe_lea'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights: light.innr_e14_tw_stehlampe_lea_level_light_color_on_off
      switch_address: '1/6/0'
      dimm_address: '1/6/2'
      dimm_time: 5
      dimm_steps: 20
- alias: KNX relative dimming Stehlampe Lara
  id: 'knx_relative_dimming_stehlampe_lara'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights: light.innr_e14_ww_stehlampe_lara_level_on_off
      switch_address: '1/5/200'
      dimm_address: '1/5/202'
      dimm_time: 5
      dimm_steps: 20
- alias: KNX relative dimming Panel Arbeitszimmer
  id: 'knx_relative_dimming_panel_arbeitszimmer'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights: light.ikea_panel_arbeitszimmer_esphome
      switch_address: '1/6/120'
      dimm_address: '1/6/122'
      dimm_time: 5
      dimm_steps: 20