- alias: KNX relative dimming Stehlampe WZ
  id: 'knx_relative_dimming_stehlampe_wz'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.innr_e27_color_stehlampe_wz_level_light_color_on_off
      switch_address: '1/6/80'
      dimm_address: '1/6/82'
      dimm_time: 5
      dimm_steps: 10
- alias: KNX relative dimming Stehlampe Lea
  id: 'knx_relative_dimming_stehlampe_lea'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.innr_e14_tw_stehlampe_lea_level_light_color_on_off
      switch_address: '1/6/0'
      dimm_address: '1/6/2'
      dimm_time: 5
      dimm_steps: 10
- alias: KNX relative dimming Stehlampe Lara
  id: 'knx_relative_dimming_stehlampe_lara'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.innr_e14_ww_stehlampe_lara_level_on_off
      switch_address: '1/5/200'
      dimm_address: '1/5/202'
      dimm_time: 5
      dimm_steps: 10
- alias: KNX relative dimming Panel Arbeitszimmer
  id: 'knx_relative_dimming_panel_arbeitszimmer'
  description: ''
  use_blueprint:
    path: /config/blueprints/knx_relative_dimming_farmio.yaml
    input:
      target_lights:
        entity_id: light.ikea_panel_arbeitszimmer_esphome
      switch_address: '1/6/120'
      dimm_address: '1/6/122'
      dimm_time: 5
      dimm_steps: 10
- id: '1639043665489'
  alias: Play on Kodi WZ
  description: ''
  trigger:
  - platform: event
    event_type: play_on_kodi_wz
    id: play_on_kodi_wz
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.samsung_7_series_55
  - service: media_player.play_media
    data:
      media_content_id: '{{ trigger.event.data.filepath }}'
      media_content_type: video
    target:
      entity_id: media_player.kodi_wz_2
  - service: media_player.volume_set
    target:
      entity_id: media_player.beam
    data:
      volume_level: 0.2
  mode: restart
- id: '1640156192211'
  alias: ZigBee Taster Lara
  description: ''
  trigger_variables:
      device_ieee: 00:15:8d:00:06:72:6e:97
  trigger:
  - platform: event
    event_type: zha_event
    id: zha_event
    event_data:
      device_ieee: "{{ device_ieee }}"
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id: switch.la_schlaft
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  mode: single
- id: '1640156192212'
  alias: ZigBee Taster Lea
  description: ''
  trigger_variables:
      device_ieee: 00:15:8d:00:06:6f:9b:9d
  trigger:
  - platform: event
    event_type: zha_event
    id: zha_event
    event_data:
      device_ieee: "{{ device_ieee }}"
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id: switch.le_schlaft
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  mode: single
- id: '1640156192213'
  alias: ZigBee Taster Gäste
  description: ''
  trigger_variables:
      device_ieee: 00:15:8d:00:02:5f:22:62
  trigger:
  - platform: event
    event_type: zha_event
    id: zha_event
    event_data:
      device_ieee: "{{ device_ieee }}"
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id: switch.gaste_schlafen
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  mode: single
- id: '3f8caab8-7874-4d85-a0a6-13a83dd0fcc0'
  alias: Erinnerung Heizung Partyraum vorne lange an
  description: ''
  trigger:
    - platform: numeric_state
      entity_id: sensor.el_leistung_heizung_partyraum_vorne
      above: '100'
      for:
        hours: 4
        minutes: 0
        seconds: 0
  condition: []
  action:
    - repeat:
        while:
          - condition: numeric_state
            entity_id: sensor.el_leistung_heizung_partyraum_vorne
            above: '100'
        sequence:
          - service: notify.telegram_jo
            data:
              message: Heizung Partyraum vorne ist noch an
          - delay:
              hours: 2
              minutes: 0
              seconds: 0
              milliseconds: 0
  mode: single
- id: 'e1fa2ab4-17ee-476d-9cde-02c450ad93b9'
  alias: Erinnerung Heizung Partyraum hinten lange an
  description: ''
  trigger:
    - platform: numeric_state
      entity_id: sensor.el_leistung_heizung_partyraum_hinten
      above: '100'
      for:
        hours: 4
        minutes: 0
        seconds: 0
  condition: []
  action:
    - repeat:
        while:
          - condition: numeric_state
            entity_id: sensor.el_leistung_heizung_partyraum_hinten
            above: '100'
        sequence:
          - service: notify.telegram_jo
            data:
              message: Heizung Partyraum hinten ist noch an
          - delay:
              hours: 2
              minutes: 0
              seconds: 0
              milliseconds: 0
  mode: single
- id: '8fc7df48-115a-44a8-ab48-8f8a514563f1'
  alias: Erinnerung Batterie Hochzeitsbild
  description: ''
  trigger:
    - platform: template
      value_template: "{% if states.sensor.esp_wemos_d1_2_wlan_signal.last_updated is defined %}{{ ((as_timestamp(now()) - as_timestamp(states.sensor.esp_wemos_d1_2_wlan_signal.last_updated)) / 3600) > 12 }}{% else %}{{ false }}{% endif %}"
  condition: []
  action:
    - repeat:
        while:
          - condition: template
            value_template: "{% if states.sensor.esp_wemos_d1_2_wlan_signal.last_updated is defined %}{{ ((as_timestamp(now()) - as_timestamp(states.sensor.esp_wemos_d1_2_wlan_signal.last_updated)) / 3600) > 12 }}{% else %}{{ false }}{% endif %}"
        sequence:
          - service: notify.telegram_jo
            data:
              message: Batterie Hochzeitsbild ist leer
          - delay:
              hours: 8
              minutes: 0
              seconds: 0
              milliseconds: 0
  mode: single
- id: 'f59f075d-d8f6-4b8e-b8e8-23c39b261b5c'
  alias: KNX Scenes
  description: ''
  mode: queued
  trigger:
    - platform: event
      event_type: knx_event
      event_data:
        destination: 15/0/50
  condition: []
  action:
    - service: notify.telegram_jo
      data:
        message: knx scene detected
    - choose:
      - conditions:
        - condition: template
          value_template: '{{ trigger.event.data.data == [22] }}'
        sequence:
        - service: notify.telegram_jo
          data:
            message: Lüftung auto
