homeassistant:
  # Name of the location where Home Assistant is running 
  name: Home
  # Location required to calculate the time the sun rises and sets 
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  customize_glob: !include cutomize_glob.yaml
  packages: !include_dir_named packages/
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.178.0/24
        - 172.29.148.0/24
    - type: homeassistant
  whitelist_external_dirs:
    - /share

debugpy:
  start: false

default_config:

#######

api:

automation: !include automations.yaml
#automation:

#battery_sim: !include config_battery_sim.yaml

binary_sensor: !include binary_sensors.yaml

camera: !include config_camera.yaml

climate:

cloud:
  alexa: !include alexa.yaml

cover:
#  - platform: template
#    covers:
#      jalousie_kuche_template:
#        device_class: blind
#        friendly_name: "Jalousie Küche Template"
#        position_template: "{{ states('sensor.garage_door')|float > 0 }}"
#        open_cover:
#          service: script.open_garage_door
#        close_cover:
#          service: script.close_garage_door
#        stop_cover:
#          service: script.stop_garage_door

discovery:

downloader:
  download_dir: www

generic_hygrostat: !include config_generic_hygrostat.yaml

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret

http:
  cors_allowed_origins:
    - http://odroidxu4.fritz.box
    - http://192.168.178.23/

folder_watcher:
  - folder: /share/abstellraum/

frontend: 
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

knx: !include config_knx.yaml

light: !include light.yaml

logger:
  default: info
  logs:
    xknx.log: debug

lovelace: !include config_lovelace.yaml

#influxdb: !include influxdb.yaml

input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_text: !include input_text.yaml

media_player:

modbus: !include modbus.yaml

mqtt: !include config_mqtt.yaml

notify: !include config_notify.yaml

#powercalc: !include config_powercalc.yaml

recorder: !include config_recorder.yaml

rest_command:
  bildschirm_theke_command:
    url: 'http://192.168.178.42:2323/?cmd={{ cmd }}&key={{ key }}&value={{ value }}&type=json&password=nopw'
  bildschirm_theke_speak:
    url: 'http://192.168.178.42:2323/?cmd=textToSpeech&text={{ text }}&password=nopw'

telegram_bot: !include config_telegram_bot.yaml

template: !include template.yaml

tts:
  - platform: google_translate
    language: "de"

#utility_meter: !include utility_meter.yaml

sensor: !include sensors.yaml

stream:

switch: !include switch.yaml

system_log:
  max_entries: 100
  fire_event: true

#waste_collection_schedule: !include config_waste_collection_schedule.yaml

weather:

zone: !include zones.yaml
