homeassistant:
  # Name of the location where Home Assistant is running 
  name: Home
  # Location required to calculate the time the sun rises and sets 
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  customize_glob: !include cutomize_glob.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.178.0/24
        - 172.29.148.0/24
    - type: homeassistant
  whitelist_external_dirs:
    - /share

zone: !include zones.yaml

frontend: 
  themes: !include_dir_merge_named themes

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: http://192.168.178.39:9541

api:
mobile_app:
#hacs: # HA custom store	
#  token: !secret github_api_key

system_log:
  max_entries: 100
  fire_event: true

logger:
  default: info
  logs:
    homeassistant.components.mqtt: warning
    googleapiclient.discovery: warning

lovelace:
  mode: yaml

automation: !include automations.yaml
config:

system_health:

#sentry:
#  dsn: !secret sentry_dsn

# Discover some devices automatically
discovery:
#  ignore:
#    - igd

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user_1
  password: !secret mqtt_pw_1
  client_id: home-assistant
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

webhook:

media_player:
# kodi now configured via UI - integrations
#  - platform: kodi
#    host: 192.168.178.38

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_id_1
      - !secret telegram_id_2
      - !secret telegram_id_alarm_gruppe

notify:
  - name: telegram_jo
    platform: telegram
    chat_id: !secret telegram_id_1
  - name: telegram_ma
    platform: telegram
    chat_id: !secret telegram_id_2
  - name: telegram_alarm_gruppe
    platform: telegram
    chat_id: !secret telegram_id_alarm_gruppe
  - platform: kodi
    name: kodi_wz
    host: 192.168.178.38

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret

recorder:
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - climate
      - cover
      - light
      - device_tracker
      - input_boolean
  exclude:
    entities:
      - sensor.time
      - sensor.last_boot
      - sensor.windfang_wc_temp_ist_text
      - sensor.windfang_wc_temp_soll_text
  purge_keep_days: 7

history:

#owntracks:

# Enables a map showing the location of tracked devices
#map:

#speedtestdotnet:

#ourgroceries:
#  username: !secret our_groceries_username
#  password: !secret our_groceries_password

# Track the sun
sun:

weather:
#  - platform: darksky
#    api_key: !secret darksky_api_key
#    name: Dark Sky
#    mode: hourly
#  - platform: openweathermap
#    api_key: !secret owm_api_key

knx:
  event_filter: 
    - "0/3/20"
    - "0/3/40"
    - "1/6/80"
    - "1/6/82"
    - "10/7/6"
    - "12/0/6"
    - "15/0/28"
    - "15/0/29"
    - "15/0/47"
    - "15/0/48"
    - "15/0/50"
    - "15/0/51"
    - "15/0/52"
    - "15/0/58"
    - "15/0/65"
    - "15/0/66"
  state_updater: true
  binary_sensor: !include knx_binary_sensor.yaml
  switch: !include knx_switch.yaml
  sensor: !include knx_sensor.yaml
  cover: !include knx_cover.yaml
  climate: !include knx_climate.yaml
  light: !include knx_light.yaml
  scene: !include knx_scene.yaml
  expose:
  - type: 'wind_speed_kmh'
    entity_id: 'sensor.windgeschwindigkeit_wetterstation_kmh'
    address: '13/0/50'
  - type: 'binary'
    entity_id: 'input_boolean.eisschutz_jalousien'
    address: '13/0/32'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_ku'
    address: '9/0/11'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_hst'
    address: '9/0/31'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_wz_bodentiefes'
    address: '9/0/51'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_wz_couch'
    address: '9/0/71'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_sz'
    address: '9/0/91'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_ba_og'
    address: '9/0/231'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_la_bodentiefes'
    address: '9/0/111'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_la_lichtband'
    address: '9/0/131'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_nz'
    address: '9/0/151'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_le_lichtband'
    address: '9/0/171'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_le_bodentiefes'
    address: '9/0/191'
  - type: 'binary'
    entity_id: 'input_boolean.sperre_jal_gz'
    address: '9/0/211'
  - type: 'string'
    entity_id: 'sensor.windfang_wc_temp_ist_text'
    address: '10/7/8'
  - type: 'string'
    entity_id: 'sensor.windfang_wc_temp_soll_text'
    address: '10/7/7'
#  - type: 'temperature'
#    entity_id: 'sensor.temp_owm'
#    address: '13/0/0'
  - type: 'temperature'
    entity_id: 'sensor.onewire_15_estrich_wc_1'
    address: '12/0/6'
  - type: 'binary'
    entity_id: 'switch.shellyswitch25_10521c45de0b_relay_0'
    address: '0/3/21'
  - type: 'binary'
    entity_id: 'switch.shellyswitch25_10521c45de0b_relay_1'
    address: '0/3/41'

light:
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

switch:

cover:

climate:

utility_meter: !include utility_meter.yaml

stream:
camera:
  - platform: local_file
    name: Meteogram
    file_path: /config/www/meteograms/meteogram.png
#  - platform: local_file
#    name: Abstellraum_letze_Bewegung
#    file_path: /config/www/camera_abstellraum/last_motion.jpg
#  - platform: onvif
#    host: 192.168.178.47
#    password: !secret mqtt_pw_1
#    port: 8080

folder_watcher:
  - folder: /share/abstellraum/

# Text to speech
#tts:
#  - platform: google

# Cloud
cloud:

# Inputs
input_boolean: !include input_boolean.yaml
input_number:
  pizza_timer_2:
    name: Pizza Timer
    initial: 0
    min: 0
    max: 30
    step: 1
  strompreis:
    name: Strompreis
    min: 0
    max: 0.5
    step: 0.001
  timer_spezial_luftf_waschk:
    name: Timer verringerte Luftfeuchtigkeit Waschküche
    initial: 0
    min: 0
    max: 12
    step: 1
  timer_spezial_luftf_werkelraum:
    name: Timer verringerte Luftfeuchtigkeit Werkelraum
    initial: 0
    min: 0
    max: 12
    step: 1
  timer_spezial_luftf_wz:
    name: Timer erhöhte Luftfeuchtigkeit WZ
    initial: 0
    min: 0
    max: 24
    step: 1
  speicher_stromzaehler_rohdaten_wp_innen:
    name: Speicher Stromz. Rohdat. WP innen
    min: 0
    max: 4294967294
  speicher_stromzaehler_rohdaten_wp_aussen:
    name: Speicher Stromz. Rohdat. WP aussen
    min: 0
    max: 4294967294
  speicher_stromzaehler_rohdaten_wp_heizstab:
    name: Speicher Stromz. Rohdat. WP Heizstab
    min: 0
    max: 4294967294
  speicher_stromzaehler_rohdaten_kochfeld:
    name: Speicher Stromz. Rohdat. Kochfeld
    min: 0
    max: 4294967294
input_text:
  location_jo_roh:
    name: Location Jo roh
  saved_reminder_01:
    max: 255
  saved_reminder_02:
    max: 255
  saved_reminder_03:
    max: 255
  saved_reminder_04:
    max: 255
  saved_reminder_05:
    max: 255
  saved_reminder_06:
    max: 255
  saved_reminder_07:
    max: 255
  saved_reminder_08:
    max: 255
  saved_reminder_09:
    max: 255
