include:
  domains:
    - sensor
    - binary_sensor
    - switch
    - climate
    - cover
    - light
    - device_tracker
    - input_boolean
exclude:
  entities:
    - sensor.time
    - sensor.last_boot
    - sensor.windfang_wc_temp_ist_text
    - sensor.windfang_wc_temp_soll_text
purge_keep_days: 8