enable_autodiscovery: false
force_update_frequency: 00:05:00
create_energy_sensors: true
power_sensor_naming: "El. Leistung PowerCalc {}"
energy_sensor_naming: "Stromzähler PowerCalc {}"
create_utility_meters: true
utility_meter_types:
  - daily
  - monthly
  - yearly
energy_integration_method: left
energy_sensor_precision: 3
#create_domain_groups:
#  - light
#  - media_player