#db_url: !secret maria_db_url
exclude:
  entities:
    - sensor.time
    - sensor.last_boot
    - sensor.windfang_wc_temp_ist_text
    - sensor.windfang_wc_temp_soll_text
    - sensor.el_leistung_licht_sicherung_3_2
    - sensor.el_leistung_licht_sicherung_3_2_scheinleistung
    - sensor.el_leistung_licht_sicherung_3_3
    - sensor.el_leistung_licht_sicherung_3_3_scheinleistung
    - sensor.pv_einspeisung_letzte_3_min_durchschnitt
  event_types:
    - call_service
purge_keep_days: 16