- name: Luftentfeuchter Waschküche
  humidifier: switch.0x00158d0003891388
  target_sensor: sensor.luftfeuchtigkeit_waschkuche
  target_humidity: 50
  dry_tolerance: 3
  wet_tolerance: 3
  device_class: "dehumidifier"
  min_cycle_duration:
    minutes: 10
  keep_alive:
    minutes: 15
  sensor_stale_duration: 02:00:00
- name: Luftentfeuchter Partyraum
  humidifier: switch.esp_sd_6_relais
  target_sensor: sensor.luftfeuchtigkeit_partyraum
  target_humidity: 60
  dry_tolerance: 2
  wet_tolerance: 1
  device_class: "dehumidifier"
  min_cycle_duration:
    minutes: 10
  keep_alive:
    minutes: 15
  sensor_stale_duration: 02:00:00
- name: Luftentfeuchter Speis
  humidifier: switch.kuhlschrank_keller
  target_sensor: sensor.luftfeuchtigkeit_vorratsraum
  target_humidity: 55
  dry_tolerance: 2
  wet_tolerance: 3
  device_class: "dehumidifier"
  min_cycle_duration:
    minutes: 10
  keep_alive:
    minutes: 15
  sensor_stale_duration: 02:00:00