homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml

zone: !include zones.yaml

frontend: !include frontend.yaml
#http:
#  ssl_certificate: certificate.pem
#  ssl_key: privkey.pem

api:

lovelace:
  mode: yaml

# Enables configuration UI
config:

system_health:

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

hacs: # HA custom store
  token: !secret github_api_key
  appdaemon: True
  theme: True

# Discover some devices automatically
discovery:
  ignore:
    - igd

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

mqtt:
  broker: a0d7b954-mqtt
  username: !secret mqtt_user_1
  password: !secret mqtt_pw_1
  client_id: home-assistant
  discovery: true

media_player:
  - platform: kodi
    host: 192.168.1.125

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_id_1
      - !secret telegram_id_2

notify:
  - name: telegram_jo
    platform: telegram
    chat_id: !secret telegram_id_1
  - name: telegram_ma
    platform: telegram
    chat_id: !secret telegram_id_2
  - platform: kodi
    name: kodi_wz
    host: 192.168.1.125

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret

recorder:
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - climate
      - cover
      - light
      - device_tracker
      - input_boolean
  exclude:
    entities:
      - sensor.yr_symbol
      - sensor.time
  purge_interval: 1
  purge_keep_days: 7
  db_url: !secret db_url

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.6
  - platform: bluetooth_le_tracker
    track_new_devices: true
  - platform: bluetooth_tracker

owntracks:
#  max_gps_accuracy: 2000

# Enables a map showing the location of tracked devices
#map:

speedtestdotnet:

ourgroceries:
  username: !secret our_groceries_username
  password: !secret our_groceries_password

# Track the sun
sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    name: Dark Sky
#    mode: hourly
  - platform: openweathermap
    api_key: !secret owm_api_key

knx:
  fire_event: true
  fire_event_filter: ["*/*/*"]
  state_updater: true
  expose:
  - type: 'speed_ms'
    entity_id: 'sensor.windgeschwindigkeit_wetterstation_kmh'
    address: '13/0/50'
  - type: 'string'
    entity_id: 'sensor.windfang_wc_temp_ist_text'
    address: '10/7/8'
  - type: 'string'
    entity_id: 'sensor.windfang_wc_temp_soll_text'
    address: '10/7/7'

#knx_reader: # custom component for reading a GA status

light: !include lights.yaml

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

switch: !include switches.yaml

cover: !include covers.yaml

climate: !include climate.yaml

camera:
  - platform: local_file
    name: Meteogram
    file_path: /config/www/meteograms/meteogram.png
  - platform: generic
    name: Meteogram_generic
    still_image_url: https://127.0.0.1:8123/local/meteograms/meteogram.png
    verify_ssl: false

# Text to speech
#tts:
#  - platform: google

# Cloud
cloud:

#group: !include groups.yaml

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 1800 # Updated this to the number of seconds you wish

# Inputs
input_boolean:
  # Test-Switch
  test_trigger:
    name: Testtrigger
    icon: mdi:ray-start-arrow
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
  # App Switches
  app_switch_licht_kueche:
    name: Automatik Licht Küche
    icon: mdi:auto-fix
  app_switch_licht_esszimmer:
    name: Automatik Licht Esszimmer
    icon: mdi:auto-fix
  app_switch_licht_wohnzimmer:
    name: Automatik Licht Wohnzimmer
    icon: mdi:auto-fix
  app_switch_licht_schlafzimmer:
    name: Automatik Licht Schlafzimmer
    icon: mdi:auto-fix
  app_switch_licht_bad_eg:
    name: Automatik Licht Bad EG
    icon: mdi:auto-fix
  app_switch_licht_flur_eg:
    name: Automatik Licht Flur EG
    icon: mdi:auto-fix
  app_switch_licht_windfang:
    name: Automatik Licht Windfang
    icon: mdi:auto-fix
  app_switch_licht_wc:
    name: Automatik Licht WC
    icon: mdi:auto-fix
  app_switch_licht_la:
    name: Automatik Licht La
    icon: mdi:auto-fix
  app_switch_licht_naehzimmer:
    name: Automatik Licht Nähzimmer
    icon: mdi:auto-fix
  app_switch_licht_le:
    name: Automatik Licht Le
    icon: mdi:auto-fix
  app_switch_licht_gaestezimmer:
    name: Automatik Licht Gästezimmer
    icon: mdi:auto-fix
  app_switch_licht_flur_og:
    name: Automatik Licht Flur OG
    icon: mdi:auto-fix
  app_switch_licht_bad_og:
    name: Automatik Licht Bad OG
    icon: mdi:auto-fix
  app_switch_licht_treppe_og:
    name: Automatik Licht Treppe OG
    icon: mdi:auto-fix
  app_switch_licht_treppe_keller:
    name: Automatik Licht Kellertreppe
    icon: mdi:auto-fix
  app_switch_jalousie_kueche:
    name: Automatik Jalousie Küche
    icon: mdi:auto-fix
  app_switch_jalousie_esszimmer:
    name: Automatik Jalousie Esszimmer
    icon: mdi:auto-fix
  app_switch_jalousie_wohnzimmer:
    name: Automatik Jalousie Wohnzimmer
    icon: mdi:auto-fix
  app_switch_jalousie_schlafzimmer:
    name: Automatik Jalousie Schlafzimmer
    icon: mdi:auto-fix
  app_switch_jalousie_la:
    name: Automatik Jalousie La
    icon: mdi:auto-fix
  app_switch_jalousie_naehzimmer:
    name: Automatik Jalousie Nähzimmer
    icon: mdi:auto-fix
  app_switch_jalousie_le:
    name: Automatik Jalousie Le
    icon: mdi:auto-fix
  app_switch_jalousie_gaestezimmer:
    name: Automatik Jalousie Gästezimmer
    icon: mdi:auto-fix
  app_switch_jalousie_bad_og:
    name: Automatik Jalousie Bad OG
    icon: mdi:auto-fix
  app_switch_log_events:
    name: Logging HA events in AD
    icon: mdi:note-text
input_number:
  pizza_timer_2:
    name: Pizza Timer
    initial: 0
    min: 0
    max: 30
    step: 1

automation:
  - id: enable_zigbee_join
    alias: Enable Zigbee joining
    hide_entity: true
    trigger:
      platform: state
      entity_id: input_boolean.zigbee_permit_join
      to: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: 'true'
    - service: timer.start
      data:
        entity_id: timer.zigbee_permit_join
  - id: disable_zigbee_join
    alias: Disable Zigbee joining
    trigger:
    - entity_id: input_boolean.zigbee_permit_join
      platform: state
      to: 'off'
    action:
    - data:
        payload: 'false'
        topic: zigbee2mqtt/bridge/config/permit_join
      service: mqtt.publish
    - data:
        entity_id: timer.zigbee_permit_join
      service: timer.cancel
    hide_entity: true
  - id: disable_zigbee_join_timer
    alias: Disable Zigbee joining by timer
    hide_entity: true
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.zigbee_permit_join
    action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: 'false'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.zigbee_permit_join
