homeassistant:
  # Name of the location where Home Assistant is running 
  name: Home
  # Location required to calculate the time the sun rises and sets 
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  customize_glob: !include cutomize_glob.yaml
  packages: !include_dir_named packages/
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.178.0/24
        - 172.29.148.0/24
    - type: homeassistant
  whitelist_external_dirs:
    - /share

default_config:

#######

api:

automation: !include automations.yaml

battery_sim: !include config_battery_sim.yaml

binary_sensor: !include binary_sensors.yaml

camera: !include config_camera.yaml

climate:

cloud:
  alexa: !include alexa.yaml

cover:

discovery:

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret

folder_watcher:
  - folder: /share/abstellraum/

frontend: 
  themes: !include_dir_merge_named themes

knx: !include config_knx.yaml

light: !include light.yaml

logger:
  default: info
  logs:
    homeassistant.components.mqtt: warning
    googleapiclient.discovery: warning

lovelace: !include config_lovelace.yaml

input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_text: !include input_text.yaml

media_player:

modbus: !include modbus.yaml

mqtt: !include config_mqtt.yaml

notify: !include config_notify.yaml

recorder: !include config_recorder.yaml

rest_command:
  bildschirm_theke_command:
    url: 'http://192.168.178.42:2323/?cmd={{ cmd }}&key={{ key }}&value={{ value }}&type=json&password=nopw'

telegram_bot: !include config_telegram_bot.yaml

template: !include template.yaml

#utility_meter: !include utility_meter.yaml

sensor: !include sensors.yaml

stream:

switch: !include switch.yaml

system_log:
  max_entries: 100
  fire_event: true

weather:

zone: !include zones.yaml