event:
  - address:
    - "0/3/20"
  - address:
    - "0/3/40"
  - address:
    - "1/5/200"
  - address:
    - "1/5/202"
  - address:
    - "1/6/0"
  - address:
    - "1/6/2"
  - address:
    - "1/6/40"
  - address:
    - "1/6/42"
  - address:
    - "1/6/80"
  - address:
    - "1/6/82"
  - address:
    - "1/6/120"
  - address:
    - "1/6/122"
  - address:
    - "10/7/6"
  - address:
    - "12/0/6"
  - address:
    - "15/0/28"
  - address:
    - "15/0/29"
  - address:
    - "15/0/47"
  - address:
    - "15/0/48"
  - address:
    - "15/0/50"
  - address:
    - "15/0/51"
  - address:
    - "15/0/52"
  - address:
    - "15/0/58"
  - address:
    - "15/0/65"
  - address:
    - "15/0/66"
#state_updater: true
binary_sensor: !include knx_binary_sensor.yaml
switch: !include knx_switch.yaml
sensor: !include knx_sensor.yaml
cover: !include knx_cover.yaml
climate: !include knx_climate.yaml
light: !include knx_light.yaml
scene: !include knx_scene.yaml
expose:
- type: 'binary'
  entity_id: 'binary_sensor.tag_nacht_wetterstation_ersatz'
  address: '13/0/3'
- type: time
  address: '13/0/11'
- type: datetime
  address: '13/0/12'
- type: 'wind_speed_kmh'
  entity_id: 'sensor.windgeschwindigkeit_wetterstation_kmh'
  address: '13/0/50'
- type: 'binary'
  entity_id: 'input_boolean.eisschutz_jalousien'
  address: '13/0/32'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_ku'
  address: '9/0/11'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_hst'
  address: '9/0/31'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_wz_bodentiefes'
  address: '9/0/51'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_wz_couch'
  address: '9/0/71'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_sz'
  address: '9/0/91'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_ba_og'
  address: '9/0/231'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_la_bodentiefes'
  address: '9/0/111'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_la_lichtband'
  address: '9/0/131'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_nz'
  address: '9/0/151'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_le_lichtband'
  address: '9/0/171'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_le_bodentiefes'
  address: '9/0/191'
- type: 'binary'
  entity_id: 'input_boolean.sperre_jal_gz'
  address: '9/0/211'
- type: 'string'
  entity_id: 'sensor.windfang_wc_temp_ist_text'
  address: '10/7/8'
- type: 'string'
  entity_id: 'sensor.windfang_wc_temp_soll_text'
  address: '10/7/7'
- type: 'temperature'
  entity_id: 'sensor.temp_aussen'
  address: '13/0/0'
- type: 'temperature'
  entity_id: 'sensor.onewire_15_estrich_wc_1'
  address: '12/0/6'
- type: 'binary'
  entity_id: 'switch.shellyswitch25_10521c45de0b_relay_0'
  address: '0/3/21'
- type: 'binary'
  entity_id: 'switch.shellyswitch25_10521c45de0b_relay_1'
  address: '0/3/41'
# Stehlampe WZ - Anzeige auf Taster
- type: "binary"
  entity_id: "light.innr_e27_color_stehlampe_wz_level_light_color_on_off"
  address: "1/6/81"
  default: false
- type: "percentU8"
  entity_id: "light.innr_e27_color_stehlampe_wz_level_light_color_on_off"
  attribute: "brightness"
  default: 0
  address: "1/6/84"
# Stehlampe Le - Anzeige auf Taster
- type: "binary"
  entity_id: "light.innr_e14_tw_stehlampe_lea_level_light_color_on_off"
  address: "1/6/1"
  default: false
- type: "percentU8"
  entity_id: "light.innr_e14_tw_stehlampe_lea_level_light_color_on_off"
  attribute: "brightness"
  default: 0
  address: "1/6/4"
# Stehlampe La - Anzeige auf Taster
- type: "binary"
  entity_id: "light.innr_e14_ww_stehlampe_lara_level_on_off"
  address: "1/5/201"
  default: false
- type: "percentU8"
  entity_id: "light.innr_e14_ww_stehlampe_lara_level_on_off"
  attribute: "brightness"
  default: 0
  address: "1/5/204"
# Deckenlicht GZ - Anzeige auf Taster
- type: "binary"
  entity_id: "light.innr_e14_ww_decke_gastezimmer_level_on_off"
  address: "1/6/41"
  default: false
- type: "percentU8"
  entity_id: "light.innr_e14_ww_decke_gastezimmer_level_on_off"
  attribute: "brightness"
  default: 0
  address: "1/6/44"