homeassistant:
  # Name of the location where Home Assistant is running 
  name: Home
  # Location required to calculate the time the sun rises and sets 
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  customize_glob: !include cutomize_glob.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.178.0/24
        - 172.29.148.0/24
    - type: homeassistant
  whitelist_external_dirs:
    - /share

zone: !include zones.yaml

frontend: 
  themes: !include_dir_merge_named themes

api:

logger:
  default: info
  logs:
    homeassistant.components.mqtt: warning
    googleapiclient.discovery: warning

lovelace:
  mode: yaml

config:

system_health:

#sentry:
#  dsn: !secret sentry_dsn

hacs: # HA custom store
  token: !secret github_api_key
  appdaemon: True
#  theme: True

# Discover some devices automatically
discovery:
#  ignore:
#    - igd

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user_1
  password: !secret mqtt_pw_1
  client_id: home-assistant
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

webhook:
 
zigbee2mqtt_networkmap:
   #topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

media_player:
  - platform: kodi
    host: 192.168.178.38

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_id_1
      - !secret telegram_id_2
      - !secret telegram_id_alarm_gruppe

notify:
  - name: telegram_jo
    platform: telegram
    chat_id: !secret telegram_id_1
  - name: telegram_ma
    platform: telegram
    chat_id: !secret telegram_id_2
  - name: telegram_alarm_gruppe
    platform: telegram
    chat_id: !secret telegram_id_alarm_gruppe
  - platform: kodi
    name: kodi_wz
    host: 192.168.178.38

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret

recorder:
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - climate
      - cover
      - light
      - device_tracker
      - input_boolean
  exclude:
    entities:
      - sensor.yr_symbol
      - sensor.time
      - sensor.last_boot
      - sensor.windfang_wc_temp_ist_text
      - sensor.windfang_wc_temp_soll_text
  purge_keep_days: 7

history:

owntracks:

# Enables a map showing the location of tracked devices
#map:

#speedtestdotnet:

#ourgroceries:
#  username: !secret our_groceries_username
#  password: !secret our_groceries_password

# Track the sun
sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    name: Dark Sky
#    mode: hourly
  - platform: openweathermap
    api_key: !secret owm_api_key

knx:
  fire_event: true
  fire_event_filter: ["*/*/*"]
  state_updater: true
  expose:
  - type: 'wind_speed_kmh'
    entity_id: 'sensor.windgeschwindigkeit_wetterstation_kmh'
    address: '13/0/50'
  - type: 'string'
    entity_id: 'sensor.windfang_wc_temp_ist_text'
    address: '10/7/8'
  - type: 'string'
    entity_id: 'sensor.windfang_wc_temp_soll_text'
    address: '10/7/7'
#  - type: 'temperature'
#    entity_id: 'sensor.temp_owm'
#    address: '13/0/0'
scene:
  - name: Jal Wohnbereich runter
    platform: knx
    address: 15/0/50
    scene_number: 7
  - name: Jal Wohnbereich hoch
    platform: knx
    address: 15/0/50
    scene_number: 8

light: !include lights.yaml

#yeelight:
#  devices:
#    192.168.178.53:
#      name: Wuerfel gross Ecke
#      model: color2
#    192.168.178.55:
#      name: Wuerfel klein
#      model: color2
#    192.168.178.53:
#      name: Wuerfel gross Feuerstelle

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

switch: !include switches.yaml

cover: !include covers.yaml

climate: !include climate.yaml

stream:
camera:
  - platform: local_file
    name: Meteogram
    file_path: /config/www/meteograms/meteogram.png
  - platform: local_file
    name: Abstellraum_letze_Bewegung
    file_path: /config/www/camera_abstellraum/last_motion.jpg
  - platform: onvif
    host: 192.168.178.47
    password: !secret mqtt_pw_1
    port: 8080

folder_watcher:
  - folder: /share/abstellraum/

# Text to speech
#tts:
#  - platform: google

# Cloud
cloud:

# Inputs
input_boolean:
  # Test-Switch
  test_trigger:
    name: Testtrigger
    icon: mdi:ray-start-arrow
  gewitter:
    name: Gewitter
    icon: mdi:flash-alert
  anwesenheit_simulieren:
    name: Anwesenheit simulieren
    icon: mdi:bag-checked
  gaeste_abends:
    name: Gäste abends
    icon: mdi:glass-cocktail
  flur_alarm_jo:
    name: Flur-Alarm Jo
    icon: mdi:motion-sensor
  flur_alarm_ma:
    name: Flur-Alarm Ma
    icon: mdi:motion-sensor
  gaeste_gz:
    name: Gästezimmer
    icon: mdi:bed-empty
  heizung_winter:
    name: Heizung Winter-Modus
    icon: mdi:snowflake
  korrektur_heizung_ku:
    name: Kurrektur Heizung Küche
    icon: mdi:auto-fix
  korrektur_heizung_ez:
    name: Kurrektur Heizung EZ
    icon: mdi:auto-fix
  korrektur_heizung_wz:
    name: Kurrektur Heizung WZ
    icon: mdi:auto-fix
  korrektur_heizung_sz:
    name: Kurrektur Heizung SZ
    icon: mdi:auto-fix
  korrektur_heizung_bad_eg:
    name: Kurrektur Heizung Bad EG
    icon: mdi:auto-fix
  korrektur_heizung_wf_wc:
    name: Kurrektur Heizung Windf./WC
    icon: mdi:auto-fix
  korrektur_heizung_la:
    name: Kurrektur Heizung La
    icon: mdi:auto-fix
  korrektur_heizung_nz:
    name: Kurrektur Heizung Nähzimmer
    icon: mdi:auto-fix
  korrektur_heizung_le:
    name: Kurrektur Heizung Le
    icon: mdi:auto-fix
  korrektur_heizung_gz:
    name: Kurrektur Heizung Gäste
    icon: mdi:auto-fix
  korrektur_heizung_flur_og:
    name: Kurrektur Heizung Flur OG
    icon: mdi:auto-fix
  korrektur_heizung_bad_og:
    name: Kurrektur Heizung Bad OG
    icon: mdi:auto-fix
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
  # App Switches
  app_switch_licht_kueche:
    name: Automatik Licht Küche
    icon: mdi:auto-fix
  app_switch_licht_esszimmer:
    name: Automatik Licht Esszimmer
    icon: mdi:auto-fix
  app_switch_licht_christbaum:
    name: Automatik Licht Christbaum
    icon: mdi:auto-fix
  app_switch_licht_wohnzimmer:
    name: Automatik Licht Wohnzimmer
    icon: mdi:auto-fix
  app_switch_licht_schlafzimmer:
    name: Automatik Licht Schlafzimmer
    icon: mdi:auto-fix
  app_switch_licht_bad_eg:
    name: Automatik Licht Bad EG
    icon: mdi:auto-fix
  app_switch_licht_flur_eg:
    name: Automatik Licht Flur EG
    icon: mdi:auto-fix
  app_switch_licht_windfang:
    name: Automatik Licht Windfang
    icon: mdi:auto-fix
  app_switch_licht_wc:
    name: Automatik Licht WC
    icon: mdi:auto-fix
  app_switch_licht_la:
    name: Automatik Licht La
    icon: mdi:auto-fix
  app_switch_licht_naehzimmer:
    name: Automatik Licht Nähzimmer
    icon: mdi:auto-fix
  app_switch_licht_le:
    name: Automatik Licht Le
    icon: mdi:auto-fix
  app_switch_licht_gaestezimmer:
    name: Automatik Licht Gästezimmer
    icon: mdi:auto-fix
  app_switch_licht_flur_og:
    name: Automatik Licht Flur OG
    icon: mdi:auto-fix
  app_switch_licht_bad_og:
    name: Automatik Licht Bad OG
    icon: mdi:auto-fix
  app_switch_licht_treppe_og:
    name: Automatik Licht Treppe OG
    icon: mdi:auto-fix
  app_switch_licht_treppe_keller:
    name: Automatik Licht Kellertreppe
    icon: mdi:auto-fix
  app_switch_licht_aussen_carport:
    name: Automatik Licht Carport
    icon: mdi:auto-fix
  app_switch_jalousie_kueche:
    name: Automatik Jalousie Küche
    icon: mdi:auto-fix
  app_switch_jalousie_esszimmer:
    name: Automatik Jalousie Esszimmer
    icon: mdi:auto-fix
  app_switch_jalousie_wohnzimmer:
    name: Automatik Jalousie Wohnzimmer
    icon: mdi:auto-fix
  app_switch_jalousie_schlafzimmer:
    name: Automatik Jalousie Schlafzimmer
    icon: mdi:auto-fix
  app_switch_jalousie_la:
    name: Automatik Jalousie La
    icon: mdi:auto-fix
  app_switch_jalousie_naehzimmer:
    name: Automatik Jalousie Nähzimmer
    icon: mdi:auto-fix
  app_switch_jalousie_le:
    name: Automatik Jalousie Le
    icon: mdi:auto-fix
  app_switch_jalousie_gaestezimmer:
    name: Automatik Jalousie Gästezimmer
    icon: mdi:auto-fix
  app_switch_jalousie_bad_og:
    name: Automatik Jalousie Bad OG
    icon: mdi:auto-fix
  app_switch_log_events:
    name: Logging HA events in AD
    icon: mdi:note-text
  kodi_just_started_playing:
    name: Kodi just started playing
    icon: mdi:play-circle-outline
    initial: off
input_number:
  pizza_timer_2:
    name: Pizza Timer
    initial: 0
    min: 0
    max: 30
    step: 1
input_text:
  location_jo_roh:
    name: Location Jo roh
