tesla_powerwall:
# Beginn: 25.10.2021
  name: Tesla Powerwall
  import_sensor: sensor.stromzaehler_netzbezug
  export_sensor: sensor.stromzaehler_netzeinspeisung
  size_kwh: 13.5
  max_discharge_rate_kw: 4.6
  max_charge_rate_kw: 3.68
  efficiency: 0.9
byd_hvs_05_1:
# Beginn: 25.10.2021
  name: BYD HVS 5_1
  import_sensor: sensor.stromzaehler_netzbezug
  export_sensor: sensor.stromzaehler_netzeinspeisung
  size_kwh: 5.1
  max_discharge_rate_kw: 5.1
  max_charge_rate_kw: 5.1
  efficiency: 0.95
byd_hvs_10_2:
# Beginn: 25.10.2021
  name: BYD HVS 10_2
  import_sensor: sensor.stromzaehler_netzbezug
  export_sensor: sensor.stromzaehler_netzeinspeisung
  size_kwh: 10.2
  max_discharge_rate_kw: 10.0
  max_charge_rate_kw: 10.0
  efficiency: 0.95
byd_hvm_11_0:
# Beginn: 25.10.2021
  name: BYD HVM 11_0
  import_sensor: sensor.stromzaehler_netzbezug
  export_sensor: sensor.stromzaehler_netzeinspeisung
  size_kwh: 11.0
  max_discharge_rate_kw: 10.0
  max_charge_rate_kw: 10.0
  efficiency: 0.95
byd_hvm_16_6:
# Beginn: 25.10.2021
  name: BYD HVM 16_6
  import_sensor: sensor.stromzaehler_netzbezug
  export_sensor: sensor.stromzaehler_netzeinspeisung
  size_kwh: 16.6
  max_discharge_rate_kw: 10.0
  max_charge_rate_kw: 10.0
  efficiency: 0.95
byd_hvm_22_1:
# Beginn: 25.10.2021
  name: BYD HVM 22_1
  import_sensor: sensor.stromzaehler_netzbezug
  export_sensor: sensor.stromzaehler_netzeinspeisung
  size_kwh: 22.1
  max_discharge_rate_kw: 10.0
  max_charge_rate_kw: 10.0
  efficiency: 0.95
