homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

zone: !include zones.yaml

frontend: !include frontend.yaml

api:

lovelace:
  mode: yaml

# Enables configuration UI
config:

system_health:

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

hacs: # HA custom store
  token: !secret github_api_key
  appdaemon: True
  theme: True

# Discover some devices automatically
discovery:
  ignore:
    - igd

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

mqtt:
  broker: a0d7b954-mqtt
  username: !secret mqtt_user_1
  password: !secret mqtt_pw_1
  client_id: home-assistant

media_player:
  - platform: kodi
    host: kodi-wz

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_id_1
      - !secret telegram_id_2

notify:
  - name: telegram_jo
    platform: telegram
    chat_id: !secret telegram_id_1
  - name: telegram_ma
    platform: telegram
    chat_id: !secret telegram_id_2
  - platform: kodi
    name: kodi_wz
    host: kodi-wz

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret

recorder:
  include:
    domains:
      - sensor
      - switch
      - climate
      - cover
      - light
  purge_interval: 0
  db_url: !secret db_url

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.6
  - platform: bluetooth_le_tracker
    track_new_devices: true
  - platform: bluetooth_tracker

owntracks:
#  max_gps_accuracy: 2000

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    name: Dark Sky
#    mode: hourly
  - platform: openweathermap
    api_key: !secret owm_api_key

knx:
  fire_event: true
  fire_event_filter: ["*/*/*"]
  state_updater: true

knx_reader: # custom component for reading a GA status

light: !include lights.yaml

sensor: !include sensors.yaml

switch: !include switches.yaml

cover: !include covers.yaml

climate: !include climate.yaml

camera:
  - platform: local_file
    name: Meteogram
    file_path: /config/www/meteograms/meteogram.png

# Text to speech
#tts:
#  - platform: google

# Cloud
cloud:

#group: !include groups.yaml

# Inputs
input_select:
  pizza_timer:
    name: Pizza Timer
    options:
      - "keine Pizza"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "20"
      - "25"
      - "30"
      - "Abbruch"
    initial: "keine Pizza"
    icon: mdi:pizza
