#
###############################################
#####        Download Meteogram           #####
###############################################
- id: '4461323f-ee9a-423e-8819-61efb3f9357d'
  alias: Download Meteogram
  description: ''
  mode: queued
  trigger:
    - platform: time
      at: "04:04:20"
  condition: []
  action:
    - service: downloader.download_file
      data:
        subdir: meteograms
        url: !secret url_meteogram
        filename: meteogram.png
        overwrite: true
#
###############################################
#####            Wasser-Alarm             #####
###############################################
- id: 'b182ebf4-79f0-4fa8-ba15-68cd685789f3'
  alias: Wasser-Alarm
  description: ''
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.aqara_doppeltaster_waschkuche_action
      to: "single_right"
      id: single_right
    - platform: state
      entity_id: binary_sensor.eimer_hebeanlage_voll
      to: 'on'
      id: eimer_hebeanlage_voll
    - platform: state
      entity_id: binary_sensor.wasser_boden_bei_hebeanlage
      to: 'on'
      id: wasser_boden_bei_hebeanlage
    - platform: state
      entity_id: binary_sensor.sicherung_keller_sd_rausgeflogen
      to: 'on'
      id: sicherung_keller_sd_rausgeflogen
    - platform: state
      entity_id: binary_sensor.wasser_unter_spule
      to: 'on'
      id: wasser_unter_spule
    - platform: state
      entity_id: input_boolean.test_alarm
      to: 'on'
      id: probealarm
    - platform: time
      at: "04:03:00"
      id: activate_fogotten_input_boolean
  condition: []
  action:
    - choose:
      - conditions:
        - condition: trigger
          id: eimer_hebeanlage_voll
        - condition: state
          entity_id: input_boolean.alarm_activated
          state: 'on'
        sequence:
        - service: switch.turn_off
          target:
            entity_id: switch.waschmaschine
        - service: notify.telegram_jo
          data:
            message: 'Alarm - Eimer Hebeanlage voll - habe die Waschmaschinen-Steckdose ausgeschalten!'
        - service: notify.telegram_ma
          data:
            message: 'Alarm - Eimer Hebeanlage voll - habe die Waschmaschinen-Steckdose ausgeschalten!'
        - service: rest_command.bildschirm_theke_speak
          data:
            text: Alarm%20Eimer%20Hebeanlage%20ist%20voll
        - service: hassio.addon_stdin
          data:
            addon: 89275b70_dss_voip
            input: !secret call_alarm_hebeanlage_voll
      - conditions:
        - condition: trigger
          id: wasser_boden_bei_hebeanlage
        - condition: state
          entity_id: input_boolean.alarm_activated
          state: 'on'
        sequence:
        - service: switch.turn_off
          target:
            entity_id: switch.waschmaschine
        - service: notify.telegram_jo
          data:
            message: 'Alarm - Wasser auf dem Boden bei der Hebeanlage - habe die Waschmaschinen-Steckdose ausgeschalten!'
        - service: notify.telegram_ma
          data:
            message: 'Alarm - Wasser auf dem Boden bei der Hebeanlage - habe die Waschmaschinen-Steckdose ausgeschalten!'
        - service: rest_command.bildschirm_theke_speak
          data:
            text: Alarm%20Wasser%20auf%20dem%20Boden%20bei%20der%20Hebeanlage
        - service: hassio.addon_stdin
          data:
            addon: 89275b70_dss_voip
            input: !secret call_alarm_wasser_boden_hebeanlage
      - conditions:
        - condition: trigger
          id: sicherung_keller_sd_rausgeflogen
        - condition: state
          entity_id: input_boolean.alarm_activated
          state: 'on'
        sequence:
        - service: switch.turn_off
          target:
            entity_id: switch.waschmaschine
        - service: notify.telegram_jo
          data:
            message: 'Alarm - Sicherung Keller-Steckdosen (Hebeanlage!) rausgeflogen - habe die Waschmaschinen-Steckdose ausgeschalten!'
        - service: notify.telegram_ma
          data:
            message: 'Alarm - Sicherung Keller-Steckdosen (Hebeanlage!) rausgeflogen - habe die Waschmaschinen-Steckdose ausgeschalten!'
        - service: rest_command.bildschirm_theke_speak
          data:
            text: Achtung%20Hebeanlage%20hat%20keinen%20Strom
        - service: hassio.addon_stdin
          data:
            addon: 89275b70_dss_voip
            input: !secret call_alarm_hebeanlage_kein_strom
      - conditions:
        - condition: trigger
          id: wasser_unter_spule
        - condition: state
          entity_id: input_boolean.alarm_activated
          state: 'on'
        sequence:
        - service: notify.telegram_jo
          data:
            message: 'Alarm - Wasser auf dem Boden unter der Sp端le oder Sp端lmaschine!'
        - service: notify.telegram_ma
          data:
            message: 'Alarm - Wasser auf dem Boden unter der Sp端le oder Sp端lmaschine!'
        - service: rest_command.bildschirm_theke_speak
          data:
            text: Alarm%20Wasser%20auf%20dem%20Boden%20bei%20der%20Sp%C3%BCle%20oder%20Sp%C3%BClmaschine
        - service: hassio.addon_stdin
          data:
            addon: 89275b70_dss_voip
            input: !secret call_alarm_wasser_boden_spuele
      - conditions:
        - condition: trigger
          id: probealarm
        sequence:
        - service: notify.telegram_jo
          data:
            message: 'Probealarm'
#        - service: rest_command.bildschirm_theke_speak
#          data:
#            text: Probealarm
        - service: hassio.addon_stdin
          data:
            addon: 89275b70_dss_voip
            input: !secret call_probealarm
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.test_alarm
      - conditions:
        - condition: trigger
          id: activate_fogotten_input_boolean
        sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: input_boolean.alarm_activated
      - conditions:
        - condition: trigger
          id: single_right
        sequence:
        - service: switch.turn_on
          target:
            entity_id: switch.waschmaschine
        - service: switch.turn_on
          target:
            entity_id: switch.wasserabsperrventil
        - service: notify.telegram_jo
          data:
            message: 'Waschmaschine hat (wieder) Strom, Wasser ist wieder an'
        - service: notify.telegram_ma
          data:
            message: 'Waschmaschine hat (wieder) Strom, Wasser ist wieder an'