resources:
  - url: /local/custom_ui/weather-card/weather-card-hours.js
    type: module
  - url: /local/custom_ui/bignumber-card/bignumber-card.js?v=1.0.0
    type: js
  - url: /local/custom_ui/monster-card/monster-card.js?v=1.0.0
    type: js
  - url: /local/custom_ui/kiosk/kiosk.js
    type: js
  - url: /local/custom_ui/card-tools/card-tools.js?v=0.4.0
    type: js
  - url: /local/custom_ui/layout-card/layout-card.js?v=0.1.0
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module 
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module    

title: Lieblingshaus
cch:
  sidebar_closed: true
  swipe: true
  swipe_animate: swipe
views:
  - !include lovelace/00_home_mobile.yaml
  - !include lovelace/01_home_panel.yaml
  - !include lovelace/10_wohnbereich.yaml
  - !include lovelace/20_eltern.yaml
