resources:
  - url: /local/custom_ui/flex-table-card/flex-table-card.js
    type: js
  - url: /local/custom_ui/weather-card/weather-card-hours.js
    type: module
  #- url: /local/custom_ui/compact-custom-header/compact-custom-header.js?v=0.0.1
  #  type: js
  - url: /local/custom_ui/bignumber-card/bignumber-card.js?v=1.0.0
    type: js
  - url: /local/custom_ui/monster-card/monster-card.js?v=1.0.0
    type: js
  - url: /local/custom_ui/kiosk/kiosk.js
    type: js
  - url: /local/custom_ui/card-tools/card-tools.js?v=0.4.0
    type: js
  - url: /local/custom_ui/layout-card/layout-card.js?v=0.1.0
    type: js

title: Lieblingshaus
views:
  - icon: mdi:home
    id: home
    title: Home
    #badges:
    #  - !secret device_jo
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:bignumber-card
            entity: sensor.time
            scale: 22px
            title: "Uhr"
          - type: custom:bignumber-card
            entity: sensor.temp_owm
            scale: 22px
            title: Draußen
          - type: custom:bignumber-card
            entity: sensor.t_wz_ist_oh
            scale: 22px
            title: Wohnzimmer
      - type: picture-elements
        image: /local/meteograms/meteogram.png
        elements:
          - type: image
            entity: camera.meteogram
            camera_image: camera.meteogram
            style:
              left: 50%
              top: 50%
              width: 100%
              height: 100%
      - type: custom:weather-card
        entity: weather.dark_sky
        icons: '/local/icons/weather_icons/static/'
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: "Wetterwarnungen"
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.dwd_warn*"
          exclude:
            - state: "off"
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: "zu erledigen"
          show_header_toggle: false
        filter:
          include:
            - entity_id: "switch.reminder*"
              state: "on"
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: "Geburtstage"
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.birthday*"
          exclude:
            - state: "off"
      - type: entities
        entities:
          - entity: sensor.restmuelltonne_anzeige
            name: Restmüll
          - entity: sensor.biotonne_anzeige
            name: Biotonne
          - entity: sensor.papiertonne_anzeige
            name: Papiertonne
          - entity: sensor.raweg_anzeige
            name: RaWeg
  - icon: mdi:monitor
    id: panel
    title: Panel
    panel: true
    #badges:
    #  - !secret device_jo
    cards:
      - type: custom:layout-card
        layout: vertical
        max_width: [50%, 50%]
        cards:
          - type: picture-elements
            image: /local/meteograms/meteogram.png
            elements:
              - type: image
                entity: camera.meteogram
                camera_image: camera.meteogram
                style:
                  left: 50%
                  top: 50%
                  width: 100%
                  height: 100%
          - type: custom:monster-card
            show_empty: false
            card:
              type: entities
              title: "Wetterwarnungen"
              show_header_toggle: false
            filter:
              include:
                - entity_id: "sensor.dwd_warn*"
              exclude:
                - state: "off"
          - type: custom:monster-card
            show_empty: false
            card:
              type: entities
              title: "zu erledigen"
              show_header_toggle: false
            filter:
              include:
                - entity_id: "switch.reminder*"
                  state: "on"
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: sensor.restmuelltonne_anzeige
                    name: Restmüll
                  - entity: sensor.biotonne_anzeige
                    name: Biotonne
                  - entity: sensor.papiertonne_anzeige
                    name: Papiertonne
                  - entity: sensor.raweg_anzeige
                    name: RaWeg
              - type: custom:monster-card
                show_empty: false
                card:
                  type: entities
                  title: "Geburtstage"
                  show_header_toggle: false
                filter:
                  include:
                    - entity_id: "sensor.birthday*"
                  exclude:
                    - state: "off"
          - break
          - type: horizontal-stack
            cards:
              - type: custom:weather-card
                entity: weather.dark_sky
                icons: '/local/icons/weather_icons/static/'
              - type: vertical-stack
                cards:
                  - type: horizontal-stack
                    cards:
                      - type: custom:bignumber-card
                        entity: sensor.date
                        scale: 22px
                      - type: custom:bignumber-card
                        entity: sensor.time
                        scale: 22px
                  - type: horizontal-stack
                    cards:
                      - type: custom:bignumber-card
                        entity: sensor.temp_owm
                        scale: 22px
                        title: Draußen
                      - type: custom:bignumber-card
                        entity: sensor.t_wz_ist_oh
                        scale: 22px
                        title: Wohnzimmer
