resources:
  - url: /local/custom_ui/weather-card/weather-card-hours.js
    type: module
  - url: /local/custom_ui/bignumber-card/bignumber-card.js?v=1.0.0
    type: js
  - url: /local/custom_ui/monster-card/monster-card.js?v=1.0.0
    type: js
  - url: /local/custom_ui/kiosk/kiosk.js
    type: js
  - url: /local/custom_ui/card-tools/card-tools.js?v=0.4.0
    type: js
  - url: /local/custom_ui/layout-card/layout-card.js?v=0.1.0
    type: js
  - url: /local/custom_ui/state-switch/state-switch.js?v=0.1.0
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module 
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/bar-card/bar-card.js
    type: js

title: Lieblingshaus
cch:
  sidebar_closed: true
  swipe: true
  swipe_animate: swipe
  exceptions:
    - conditions:
        user: Bildschirm
      config:
        background: "#303030"
        all_tabs_color: "#ff9c27"
        all_buttons_color: "#ff9c27"
        tab_indicator_color:  "#ff9c27"
        notify_indicator_color: "#eeeeee"

views:
  - !include lovelace/01_home_panel.yaml
  - !include lovelace/10_wohnbereich.yaml
  - !include lovelace/20_eltern.yaml
  - !include lovelace/30_flure_treppen_carport.yaml
  - !include lovelace/40_kinder_und_bad.yaml
  - !include lovelace/50_nz_gz.yaml
  - !include lovelace/60_keller.yaml
  - !include lovelace/80_automatisierungen.yaml
  - !include lovelace/82_temperaturen.yaml
  - !include lovelace/83_helligkeiten.yaml
  - !include lovelace/84_anwesenheiten.yaml
  - !include lovelace/90_technik.yaml
