resources:
  - url: /local/custom_ui/weather-card/weather-card-hours.js
    type: module
  - url: /local/custom_ui/bignumber-card/bignumber-card.js?v=1.0.0
    type: js
  - url: /local/custom_ui/monster-card/monster-card.js?v=1.0.0
    type: js
  - url: /local/custom_ui/kiosk/kiosk.js
    type: js
  - url: /local/custom_ui/card-tools/card-tools.js?v=0.4.0
    type: js
  - url: /local/custom_ui/layout-card/layout-card.js?v=0.1.0
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module 
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module    

title: Lieblingshaus
cch:
  sidebar_closed: true
  swipe: true
  swipe_animate: swipe
views:
  - title: Home (mobil)
    path: home_mobile
    icon: mdi:cellphone
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:bignumber-card
            entity: sensor.time
            scale: 22px
            title: "Uhr"
          - type: custom:bignumber-card
            entity: sensor.temp_owm
            scale: 22px
            title: Draußen
          - type: custom:bignumber-card
            entity: sensor.t_wz_ist_oh
            scale: 22px
            title: Wohnzimmer
      - type: picture-elements
        image: /local/meteograms/meteogram.png
        elements:
          - type: image
            entity: camera.meteogram
            camera_image: camera.meteogram
            style:
              left: 50%
              top: 50%
              width: 100%
              height: 100%
      - type: custom:weather-card
        entity: weather.dark_sky
        icons: '/local/icons/weather_icons/static/'
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: "Wetterwarnungen"
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.dwd_warn*"
          exclude:
            - state: "off"
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: "zu erledigen"
          show_header_toggle: false
        filter:
          include:
            - entity_id: "switch.reminder*"
              state: "on"
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: "Geburtstage"
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.birthday*"
          exclude:
            - state: "off"
      - type: entities
        entities:
          - entity: sensor.restmuelltonne_anzeige
            name: Restmüll
          - entity: sensor.biotonne_anzeige
            name: Biotonne
          - entity: sensor.papiertonne_anzeige
            name: Papiertonne
          - entity: sensor.raweg_anzeige
            name: RaWeg
      - type: entities
        title: Pizza Timer
        show_header_toggle: false
        entities:
          - input_select.pizza_timer
      - type: entities
        title: "Wer ist wo..."
        show_header_toggle: false
        entities:
          - entity: sensor.location_jo
  - title: Home (Panel)
    path: home_panel
    icon: mdi:monitor
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_width: [50%, 50%]
        cards:
          - type: picture-elements
            image: /local/meteograms/meteogram.png
            elements:
              - type: image
                entity: camera.meteogram
                camera_image: camera.meteogram
                style:
                  left: 50%
                  top: 50%
                  width: 100%
                  height: 100%
          - type: custom:monster-card
            show_empty: false
            card:
              type: entities
              title: "Wetterwarnungen"
              show_header_toggle: false
            filter:
              include:
                - entity_id: "sensor.dwd_warn*"
              exclude:
                - state: "off"
          - type: custom:monster-card
            show_empty: false
            card:
              type: entities
              title: "zu erledigen"
              show_header_toggle: false
            filter:
              include:
                - entity_id: "switch.reminder*"
                  state: "on"
          - type: horizontal-stack
            cards:
              - type: entities
                title: "Abfall"
                show_header_toggle: false
                entities:
                  - entity: sensor.restmuelltonne_anzeige
                    name: Restmüll
                  - entity: sensor.biotonne_anzeige
                    name: Biotonne
                  - entity: sensor.papiertonne_anzeige
                    name: Papiertonne
                  - entity: sensor.raweg_anzeige
                    name: RaWeg
              - type: custom:monster-card
                show_empty: false
                card:
                  type: entities
                  title: "Geburtstage"
                  show_header_toggle: false
                filter:
                  include:
                    - entity_id: "sensor.birthday*"
                  exclude:
                    - state: "off"
          - break
          - type: horizontal-stack
            cards:
              - type: custom:weather-card
                entity: weather.dark_sky
                icons: '/local/icons/weather_icons/static/'
              - type: vertical-stack
                cards:
                  - type: horizontal-stack
                    cards:
                      - type: custom:bignumber-card
                        entity: sensor.date
                        scale: 22px
                      - type: custom:bignumber-card
                        entity: sensor.time
                        scale: 22px
                  - type: horizontal-stack
                    cards:
                      - type: custom:bignumber-card
                        entity: sensor.t_wz_ist_oh
                        scale: 22px
                        title: Wohnzimmer
                      - type: custom:bignumber-card
                        entity: sensor.temp_owm
                        scale: 22px
                        title: Draußen
                  - type: entities
                    title: "Wer ist wo..."
                    show_header_toggle: false
                    entities:
                      - entity: sensor.location_jo
  - title: Wohnbereich
    path: wohnbereich
    icon: mdi:food-fork-drink
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: "Küche"
            show_header_toggle: true
            entities:
            - type: custom:slider-entity-row
              entity: light.panels_kuche
              name: Panels Küche
              toggle: true
            - type: custom:slider-entity-row
              entity: light.panels_bar
              name: Panels Bar
              toggle: true
            - type: custom:slider-entity-row
              entity: light.arbeitsplatte
              name: Arbeitsplatte
              toggle: true
            - type: custom:slider-entity-row
              entity: light.sockelbeleuchtung
              name: Sockel
              toggle: true
          - type: entities
            title: "Jalousie"
            show_header_toggle: false
            entities:
            - entity: cover.jalousie_kuche
              name: Küche
            - type: custom:slider-entity-row
              entity: cover.jalousie_kuche
              full_row: true
          - type: 'custom:simple-thermostat'
            entity: climate.kuche
            sensors:
              - entity: sensor.temp_kuche_pm
                name: Temp. PM
