resources:
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card.js?v=1.0.1
    type: module

title: Lieblingshaus
views:
  - icon: mdi:home
    id: home
    title: Home
    cards:
      - type: "custom:calendar-card"
      name: "Geburtstage"
      showProgressBar: false
      numberOfDays: 30
      entities:
        - calendar.geburtstage_und_jahrestag
