resources:
  - url: /local/custom_ui/moment_js/moment.js
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card-bd.js?v=1.0.1
    type: module
  - url: /local/custom_ui/weather-card/weather-card-hours.js
    type: module

title: Lieblingshaus
views:
  - icon: mdi:home
    id: home
    title: Home
    cards:
      - type: "custom:calendar-card-bd"
        name: "Geburtstage"
        showProgressBar: false
        numberOfDays: 90
        entities:
          - calendar.geburtstage_und_jahrestag
      - type: custom:weather-card
        entity: weather.dark_sky
        icons: '/local/icons/weather_icons/animated/'
      - type: glance
        show_name: false
        entities:
          - entity: switch.restmuelltonne_erinnerung
            name: Restmüll
            tap_action:
              action: call_service
              service: homeassistant.update_entity
              service_data:
                entity_id: switch.restmuelltonne_erinnerung
          - entity: switch.biotonne_erinnerung
            name: Bio
            tap_action:
              action: toggle
          - entity: switch.papiertonne_erinnerung
            name: Papier
            tap_action:
              action: toggle
          - entity: switch.raweg_erinnerung
            name: RaWeg
          - entity: switch.copy
            name: BioCopy
            tap_action:
              action: toggle

