resources:
  - url: /local/custom_ui/flex-table-card/flex-table-card.js
    type: js
  - url: /local/custom_ui/weather-card/weather-card-hours.js
    type: module
  #- url: /local/custom_ui/compact-custom-header/compact-custom-header.js?v=0.0.1
  #  type: js
  - url: /local/custom_ui/bignumber-card/bignumber-card.js?v=1.0.0
    type: js
  - url: /local/custom_ui/monster-card/monster-card.js?v=1.0.0
    type: js
  - url: /local/custom_ui/kiosk/kiosk.js
    type: js
  - url: /local/custom_ui/card-tools/card-tools.js?v=0.4.0
    type: js

title: Lieblingshaus
views:
  - icon: mdi:home
    id: home
    title: Home
    #badges:
    #  - !secret device_jo
    cards:
      #- type: custom:compact-custom-header
      #  header: true
      #  menu: true
      #  notification: true
      #  voice: false
      #  options: true
      #  tabs: true
      #  clock: options
      #  clock_format: 24
      #  clock_am_pm: false
      #  disable: false
      #  background_image: false
      - type: horizontal-stack
        cards:
          - type: custom:bignumber-card
            entity: sensor.time
            scale: 22px
            title: "Uhr"
          - type: custom:bignumber-card
            entity: sensor.temp_owm
            scale: 22px
            title: Draußen
          - type: custom:bignumber-card
            entity: sensor.t_wz_ist_oh
            scale: 22px
            title: Wohnzimmer
      - type: picture-elements
        image: /local/meteograms/meteogram.png
        elements:
          - type: image
            entity: camera.meteogram
            camera_image: camera.meteogram
            style:
              left: 50%
              top: 50%
              width: 100%
              height: 100%
#      - type: custom:flex-table-card 
#        entities:
#          include: variable.birthdays
#        columns:
#          - name: " "
#            attr_as_list: weekday
#          - name: " "
#            attr_as_list: when
#          - name: Geburtstage
#            attr_as_list: who
      - type: custom:weather-card
        entity: weather.dark_sky
        icons: '/local/icons/weather_icons/static/'
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: "Wetterwarnungen"
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.dwd_warn*"
          exclude:
            - state: "off"
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: "zu erledigen"
          show_header_toggle: false
        filter:
          include:
            - entity_id: "switch.reminder*"
              state: "on"
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: "Geburtstage"
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.birthday*"
          exclude:
            - state: "off"
      - type: entities
        entities:
          - entity: sensor.restmuelltonne_anzeige
            name: Restmüll
          - entity: sensor.biotonne_anzeige
            name: Biotonne
          - entity: sensor.papiertonne_anzeige
            name: Papiertonne
          - entity: sensor.raweg_anzeige
            name: RaWeg
#      - type: glance
#        show_name: true
#        entities:
#          - entity: sensor.restmuelltonne_anzeige
#            name: Restmüll
#          - entity: sensor.biotonne_anzeige
#            name: Biotonne
#          - entity: sensor.papiertonne_anzeige
#            name: Papiertonne
#          - entity: sensor.raweg_anzeige
#            name: RaWeg
