resources:
  - url: /local/custom_ui/flex-table-card/flex-table-card.js
    type: js
  - url: /local/custom_ui/weather-card/weather-card-hours.js
    type: module
  - url: /local/custom_ui/compact-custom-header/compact-custom-header.js?v=0.0.1
    type: js
  - url: /local/custom_ui/bignumber-card/bignumber-card.js?v=1.0.0
    type: js

title: Lieblingshaus
views:
  - icon: mdi:home
    id: home
    title: Home
    badges:
      - !secret device_jo
    cards:
      - type: custom:compact-custom-header
        header: true
        menu: true
        notification: true
        voice: false
        options: true
        tabs: true
        clock: options
        clock_format: 24
        clock_am_pm: false
        disable: false
        background_image: false
      - type: horizontal-stack
        cards:
          - type: custom:bignumber-card
            entity: sensor.time
            scale: 30px
          - type: custom:bignumber-card
            entity: sensor.temp_owm
            scale: 30px
      - type: custom:flex-table-card 
        entities:
          include: variable.birthdays
        columns:
          - name: " "
            attr_as_list: weekday
          - name: " "
            attr_as_list: when
          - name: Geburtstage
            attr_as_list: who
      - type: custom:weather-card
        entity: weather.dark_sky
        icons: '/local/icons/weather_icons/animated/'
      - type: entity-filter
        entities:
          - entity: switch.restmuelltonne_erinnerung
            name: Restmüll
            tap_action:
              action: toggle
          - entity: switch.biotonne_erinnerung
            name: Bio
            tap_action:
              action: toggle
          - entity: switch.papiertonne_erinnerung
            name: Papier
            tap_action:
              action: toggle
          - entity: switch.raweg_erinnerung
            name: RaWeg
            tap_action:
              action: toggle
        show_empty: false
        state_filter:
          - "on"
        card: 
          type: glance
          show_name: true
          show_state: false
      - type: glance
        show_name: true
        entities:
          - entity: sensor.restmuelltonne_anzeige
            name: Restmüll
          - entity: sensor.biotonne_anzeige
            name: Biotonne
          - entity: sensor.papiertonne_anzeige
            name: Papiertonne
          - entity: sensor.raweg_anzeige
            name: RaWeg
