resources:
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card-bd.js?v=1.0.1
    type: module
  - url: /local/custom_ui/weather-card/weather-card.js
    type: module

title: Lieblingshaus
views:
  - icon: mdi:home
    id: home
    title: Home
    cards:
      - type: "custom:calendar-card-bd"
        name: "Geburtstage"
        showProgressBar: false
        numberOfDays: 90
        entities:
          - calendar.geburtstage_und_jahrestag
      - type: custom:weather-card
        entity: weather.openweathermap
        icons: '/local/icons/weather_icons/animated/'
