resources:
  - url: /local/custom_ui/moment_js/moment.js
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card-bd.js?v=1.0.1
    type: module
  - url: /local/custom_ui/weather-card/weather-card-hours.js
    type: module

title: Lieblingshaus
views:
  - icon: mdi:home
    id: home
    title: Home
    cards:
      - type: "custom:calendar-card-bd"
        name: "Geburtstage"
        showProgressBar: false
        numberOfDays: 90
        entities:
          - calendar.geburtstage_und_jahrestag
      - type: custom:weather-card
        entity: weather.dark_sky
        icons: '/local/icons/weather_icons/animated/'
      - type: entity-filter
        entities:
          - entity: switch.restmuelltonne_erinnerung
            name: Restmüll
            tap_action:
              action: toggle
          - entity: switch.biotonne_erinnerung
            name: Bio
            tap_action:
              action: toggle
          - entity: switch.papiertonne_erinnerung
            name: Papier
            tap_action:
              action: toggle
          - entity: switch.raweg_erinnerung
            name: RaWeg
            tap_action:
              action: toggle
        show_empty: false
        state_filter:
          - "on"
        card: 
          type: glance
          show_name: true
          show_state: false
      - type: glance
        show_name: true
        entities:
          - entity: sensor.restmuelltonne_anzeige
            name: Restmüll
          - entity: sensor.biotonne_anzeige
            name: Biotonne
          - entity: sensor.papiertonne_anzeige
            name: Papiertonne
          - entity: sensor.raweg_anzeige
            name: RaWeg
