resources:
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card-bd.js?v=1.0.1
    type: module
  - type: module
    url: /local/custom-weather-card-chart.js

title: Lieblingshaus
views:
  - icon: mdi:home
    id: home
    title: Home
    cards:
      - type: "custom:calendar-card-bd"
        name: "Geburtstage"
        showProgressBar: false
        numberOfDays: 90
        entities:
          - calendar.geburtstage_und_jahrestag
      - type: 'custom:weather-card-chart'
        title: Weather
        weather: weather.dark_sky
        sun: sun.sun
