resources:
#  - url: /local/custom_ui/weather-card/weather-card-hours.js
#    type: module
#  - url: /local/custom_ui/bignumber-card/bignumber-card.js?v=1.0.0
#    type: js
#  - url: /local/custom_ui/kiosk/kiosk.js
#    type: js
  - url: /local/custom_ui/card-tools/card-tools.js?v=0.4.0
    type: js
  - url: /local/custom_ui/layout-card/layout-card.js?v=0.1.0
    type: js
#  - url: /local/custom_ui/state-switch/state-switch.js?v=0.1.0
#    type: js
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module 
  - url: /community_plugin/simple-thermostat/simple-thermostat.js?v=1
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/bar-card/bar-card.js
    type: js
#  - url: /community_plugin/our-groceries-card/our-groceries-card.js
#    type: js
#  - url: /local/custom_ui/markdown-mod/markdown-mod.js
#    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: js
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/lovelace-hui-element/hui-element.js
    type: module

title: Lieblingshaus
custom_header:
  compact_mode: true
  header_text: '{{ states.sensor.time.state }}'
  exceptions:
    - conditions:
        user: Bildschirm
      config:
        background: "#202020"
        all_tabs_color: "#ff9c27"
        menu_color: "#ff9c27"
        voice_color: "#ff9c27"
        options_color: "#ff9c27"
        tab_indicator_color:  "#ff9c27"
        notify_indicator_color: "#eeeeee"

views:
  - !include lovelace/01_home.yaml
  - !include lovelace/10_wohnbereich.yaml
  - !include lovelace/20_eltern.yaml
  - !include lovelace/30_flure_treppen_carport.yaml
  - !include lovelace/35_aussen.yaml
  - !include lovelace/40_kinder_und_bad.yaml
  - !include lovelace/50_nz_gz.yaml
  - !include lovelace/60_keller.yaml
  - !include lovelace/70_automatisierungen.yaml
  - !include lovelace/75_heizung.yaml
  - !include lovelace/80_stromverbrauch.yaml
  - !include lovelace/82_temperaturen.yaml
  - !include lovelace/83_helligkeiten.yaml
  - !include lovelace/84_wetterstation.yaml
  - !include lovelace/86_anwesenheiten.yaml
  - !include lovelace/90_technik.yaml
  - !include lovelace/94_alarme.yaml
  - !include lovelace/95_hochzeitsvideo.yaml
  - !include lovelace/96_tagesschau.yaml
  - !include lovelace/96_tagesschau_2.yaml
#  - !include lovelace/98_einkaufen.yaml
