title: Lieblingshaus
views:
  - !include lovelace/01_home.yaml
#  - !include lovelace/02_home_mobile.yaml
  - !include lovelace/10_wohnbereich.yaml
  - !include lovelace/20_eltern.yaml
  - !include lovelace/30_flure_treppen_carport.yaml
  - !include lovelace/35_aussen.yaml
  - !include lovelace/40_kinder_und_bad.yaml
  - !include lovelace/50_nz_gz.yaml
  - !include lovelace/60_keller.yaml
  - !include lovelace/69_anwesenheiten.yaml
  - !include lovelace/70_automatisierungen.yaml
  - !include lovelace/72_jalousien.yaml
  - !include lovelace/75_heizung.yaml
  - !include lovelace/79_pv.yaml
  - !include lovelace/80_stromverbrauch.yaml
  - !include lovelace/81_temperaturen.yaml
  - !include lovelace/82_luftfeuchtigkeit.yaml
  - !include lovelace/83_helligkeiten.yaml
  - !include lovelace/84_wetterstation.yaml
  - !include lovelace/87_wowa.yaml
  - !include lovelace/90_technik.yaml
  - !include lovelace/94_alarme.yaml
  - !include lovelace/95_hochzeitsvideo.yaml
  - !include lovelace/96_tagesschau.yaml
