auto_light_k_kellertreppe:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_treppe_keller
  light: light.shellydimmer_d472fe_light_0
  type: dim
  triggers: 
    - binary_sensor.pm_ktr_treppe
    - binary_sensor.pm_k_fl_2
  brightness_values:
    "00:00": 40
  min_illuminance_values:
    "00:00": 1
