# - Gästezimmer
#auto_light_o_gz_deckenlicht:
#  module: auto_light
#  class: auto_light
#  debug: quiet
#  app_switch: input_boolean.app_switch_licht_gaestezimmer
#  light: light.innr_e14_ww_decke_gastezimmer_level_on_off
#  type: dim
#  triggers: 
#    - binary_sensor.pm_o_gz
#  brightness_values:
#    "00:00": 20
#    "08:00": 60
#    "09:00": 80
#    "10:00": 100
#    "20:00": 70
#    "22:00": 40
#    "23:00": 20
#  min_illuminance_values:
#    "00:00": 10
#    "05:00": 20
#    "06:30": 30
#    "09:00": 40
#    "17:00": 30
#    "19:00": 20
#    "23:00": 10
#  illuminance_sensor: sensor.helligkeit_gastezimmer_pm
#  keeping_off_entities:
#    - switch.gaste_schlafen
#    - switch.luften_le
#  switching_off_entities:
#    - switch.gaste_schlafen
#    - switch.luften_le
knx_dim_funk_gz_deckenlicht:
  module: knx_dim_funk
  class: knx_dim_funk
  light_entity: light.innr_e14_ww_decke_gastezimmer_level_on_off
  steps:
    - 0
    - 5
    - 30
    - 70
    - 100
  command_ga_dim: "15/0/51"
  command_ga_switch: "15/0/52"
