auto_light_k_vorratsraum:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_keller
  light: light.vorratsraum
  type: switch
  triggers: 
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_83155c04_on_off
    - binary_sensor.anwesenheit_vorratsraum
  min_illuminance_values:
    "00:00": 1
