# - LED-Streifen Carport
auto_light_a_cp_led_streifen:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.led_streifen_carport
  type: dim
  triggers: 
    - binary_sensor.pm_a_eg
    - binary_sensor.pm_a_cp
  keeping_on_entities:
    - binary_sensor.pm_a_ar
  brightness_values:
    "00:00": 60
  min_illuminance_values:
    "00:00": 600
  illuminance_sensor: sensor.helligkeit_wetterstation
auto_light_a_eg_bodenlicht:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.bodenlicht_eingang
  type: dim
  triggers: 
    - binary_sensor.pm_a_eg
    - binary_sensor.pm_a_cp
  keeping_on_entities:
    - binary_sensor.pm_a_ar
  brightness_values:
    "00:00": 70
  min_illuminance_values:
    "00:00": 600
  illuminance_sensor: sensor.helligkeit_wetterstation
# - Spots Carport
auto_light_a_cp_spots:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.spots_carport
  type: switch
  triggers: 
    - binary_sensor.pm_a_eg
    - binary_sensor.pm_a_cp
  keeping_on_entities:
    - binary_sensor.pm_a_ar
  min_illuminance_values:
    "00:00": 1000
  illuminance_sensor: sensor.helligkeit_wetterstation
# - Abstellraum
auto_light_a_abstellraum:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.abstellraum_carport
  type: switch
  triggers: 
    - binary_sensor.pm_a_ar
  keeping_on_entities:
    - binary_sensor.pm_a_eg
    - binary_sensor.pm_a_cp
  min_illuminance_values:
    "00:00": 4000000
  illuminance_sensor: sensor.helligkeit_wetterstation
# - Leuchtwürfel Terrasse
auto_light_a_tr_wurfel_ecke_gross:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.innr_color_terrasse_ecke_gross_level_light_color_on_off
  type: switch
  triggers: 
    - binary_sensor.hst_offen
  min_illuminance_values:
    "00:00": 600
  illuminance_sensor: sensor.helligkeit_wetterstation
auto_light_a_tr_wurfel_ecke_klein:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.innr_color_terrasse_ecke_klein_level_light_color_on_off
  type: switch
  triggers: 
    - binary_sensor.hst_offen
  min_illuminance_values:
    "00:00": 600
  illuminance_sensor: sensor.helligkeit_wetterstation
auto_light_a_tr_wurfel_feuerstelle:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.innr_color_terrasse_feuerstelle_level_light_color_on_off
  type: switch
  triggers: 
    - binary_sensor.hst_offen
  min_illuminance_values:
    "00:00": 600
  illuminance_sensor: sensor.helligkeit_wetterstation
