#auto_light_o_nz_jo:
#  module: auto_light
#  class: auto_light
#  debug: quiet
#  app_switch: input_boolean.app_switch_licht_naehzimmer
#  light: light.schreibtisch_decke
#  type: switch
#  triggers: 
#    - binary_sensor.pm_o_nz
#  min_illuminance_values:
#    "00:00": 0
#  illuminance_sensor: sensor.helligkeit_nahzimmer_pm
#  switching_off_offset: 400
#auto_light_o_nz_ma:
#  module: auto_light
#  class: auto_light
#  debug: quiet
#  app_switch: input_boolean.app_switch_licht_naehzimmer
#  light: light.ikea_panel_arbeitszimmer_esphome
#  type: dim
#  triggers: 
#    - binary_sensor.pm_o_nz
#  brightness_values:
#    "00:00": 30
#    "04:00": 20
#    "06:30": 40
#    "07:30": 50
#    "09:00": 80
#    "18:00": 50
#    "19:00": 40
#  min_illuminance_values:
#    "00:00": 35
#  illuminance_sensor: sensor.helligkeit_nahzimmer_pm
#  switching_off_offset: 60
#  keeping_off_entities:
#    - switch.gaste_schlafen
#    - switch.luften_eg
#  switching_off_entities:
#    - switch.luften_eg
