# - Bad OG
auto_light_o_ba_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_bad_og
  light: light.panels_bad_og
  triggers: 
    - binary_sensor.pm_o_ba
  brightness_values:
    "00:00": 50
    "06:00": 60
    "09:00": 90
    "17:00": 80
    "18:00": 70
    "20:00": 50
  min_illuminance_values:
    "00:00": 25
    "06:00": 35
    "18:00": 30
    "21:00": 25
  illuminance_sensor: sensor.helligkeit_bad_og_pm
  special_brightness_entities:
    switch.bad_og_nachtmodus: 5
auto_light_o_ba_spiegel:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_bad_og
  light: light.spiegel_bad_og
  triggers: 
    - binary_sensor.pm_o_ba
  brightness_values:
    "00:00": 0
    "01:00": 0
  min_illuminance_values:
    "00:00": 1000
    "01:00": 1000
  illuminance_sensor: sensor.helligkeit_bad_og_pm
