# - Esszimmer
auto_light_e_ez_panels:
  module: auto_light_beta
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_esszimmer
  light: light.panels_esszimmer
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 40
    "04:30": 50
    "06:00": 60
    "06:30": 78
    "18:30": 65
    "21:30": 40
  min_illuminance_values:
    "00:00": 10
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "18:30": 30
    "21:30": 10
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  special_brightness_entities:
    switch.majo_schlafen: 10
  keeping_off_entities:
    - binary_sensor.tv_abends_an
#    - binary_sensor.abends_und_min_ein_kind_im_bett
#  keeping_on_entities:
#    - binary_sensor.abends_und_min_ein_kind_im_bett
  switching_off_entities:
    - switch.majo_schlafen
    - binary_sensor.tv_abends_an
auto_light_e_ez_christbaum:
  module: auto_light_beta
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_esszimmer
  light: light.sd_fussraum_bar
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 100
    "01:00": 100
  min_illuminance_values:
    "00:00": 10
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "18:30": 30
    "21:30": 10
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  keeping_off_entities:
    - binary_sensor.tv_abends_an
  switching_off_entities:
    - switch.majo_schlafen
    - binary_sensor.tv_abends_an
# - Küche
auto_light_e_ku_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_kueche
  light: light.panels_kuche
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 40
    "04:30": 50
    "06:00": 60
    "06:30": 78
    "18:30": 70
    "21:30": 40
  min_illuminance_values:
    "00:00": 10
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "09:00": 50
    "17:00": 40
    "18:30": 30
    "21:30": 10
  illuminance_sensor: sensor.helligkeit_kuche_pm
  special_brightness_entities:
    switch.majo_schlafen: 10
  keeping_fix_entities:
    binary_sensor.tv_abends_an: 25
auto_light_e_ku_arbeitsplatte:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_kueche
  light: light.arbeitsplatte
  triggers: 
    - binary_sensor.pm_e_ku_kuche
  brightness_values:
    "00:00": 40
    "06:00": 60
    "06:30": 65
    "09:00": 90
    "17:00": 80
    "17:30": 70
    "19:30": 60
    "22:00": 40
  min_illuminance_values:
    "00:00": 20
    "06:00": 30
    "08:30": 40
    "09:00": 50
    "17:00": 40
    "20:00": 30
    "22:00": 20
  illuminance_sensor: sensor.helligkeit_kuche_pm
  special_brightness_entities:
    switch.majo_schlafen: 20
# - Bar Panels
auto_light_e_bar_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_kueche
  light: light.panels_bar
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 40
    "04:30": 50
    "06:00": 60
    "06:30": 70
    "07:00": 80
    "08:00": 90
    "17:00": 75
    "18:30": 70
    "21:30": 60
  min_illuminance_values:
    "00:00": 10
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "09:00": 50
    "17:00": 40
    "18:30": 30
    "21:30": 10
  illuminance_sensor: sensor.helligkeit_kuche_pm
  special_brightness_entities:
    switch.majo_schlafen: 10
  keeping_fix_entities:
    binary_sensor.tv_pizza_abend: 50
  keeping_off_entities:
    - binary_sensor.kein_tv_pizza_abend
# - Wohnzimmer
auto_light_e_wz_panels:
  module: auto_light
  class: auto_light
  debug: few
  constrain_input_boolean: input_boolean.app_switch_licht_wohnzimmer
  light: light.panels_wohnzimmer
  triggers: 
    - binary_sensor.pm_e_wz_durchgang
    - binary_sensor.pm_e_wz_couch_links
    - binary_sensor.pm_e_wz_couch_rechts
  brightness_values:
    "00:00": 50
    "06:00": 60
    "06:30": 70
    "07:00": 80
    "19:00": 50
    "21:00": 30
  min_illuminance_values:
    "00:00": 20
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "09:00": 50
    "17:00": 40
    "18:30": 30
    "21:30": 20
  illuminance_sensor: sensor.helligkeit_wohnzimmer_pm
  special_brightness_entities:
    binary_sensor.tv_ist_an: 30
  keeping_fix_entities:
    binary_sensor.tv_pizza_abend: 10
    binary_sensor.tv_abend_ohne_pizza: 5
