# - La
dimmer_steps_panels_la:
  module: dimmer_steps
  class: dimmer_steps
  light_entity: light.panels_la
  steps:
    - 0
    - 5
    - 30
    - 50
    - 70
    - 100
  command_ga: "15/0/29"
dimmer_steps_wuerfel_la:
  module: dimmer_steps
  class: dimmer_steps
  light_entity: light.wandwurfel_la
  steps:
    - 0
    - 3
    - 20
    - 55
    - 100
  command_ga: "15/0/48"
dimmer_steps_stehlampe_la:
  module: dimmer_steps
  class: dimmer_steps
  light_entity: light.innr_e14_ww_stehlampe_lara_level_on_off
  steps:
    - 0
    - 3
    - 15
    - 50
    - 100
  command_ga: "15/0/66"
