# - Flur OG
auto_light_o_fl_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_flur_og
  light: light.panels_flur_og
  type: dim
  triggers: 
    - binary_sensor.pm_o_fl_treppe
    - binary_sensor.pm_o_fl_flur
    - binary_sensor.pm_o_ko_la_tuer
    - binary_sensor.pm_o_kw_le_tuer
  brightness_values:
    "00:00": 30
    "03:00": 10
    "06:30": 40
    "08:00": 80
    "09:00": 90
    "17:00": 80
    "18:00": 70
    "20:30": 50
  min_illuminance_values:
    "00:00": 5
    "06:30": 25
    "09:00": 30
    "17:00": 25
    "19:00": 10
    "23:00": 5
  illuminance_sensor: sensor.helligkeit_flur_og_pm
  keeping_off_entities:
    - binary_sensor.la_oder_le_schlafen
    - switch.luften_eg
  switching_off_entities:
    - binary_sensor.la_oder_le_schlafen
    - switch.luften_eg
  special_brightness_entities:
    binary_sensor.schlafen_oder_aufwachphase_kinder: 15
