# - La
auto_light_o_la_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_la
  light: light.panels_la
  type: dim
  triggers: 
    - binary_sensor.pm_o_ko_la_raum
    - binary_sensor.pm_o_ko_la_tuer
  brightness_values:
    "00:00": 25
    "07:30": 50
    "08:00": 70
    "09:00": 90
    "17:00": 80
    "18:00": 60
    "20:00": 50
    "21:00": 30
  min_illuminance_values:
    "00:00": 20
    "05:30": 30
    "07:30": 40
    "09:00": 50
    "18:00": 35
    "21:00": 20
  illuminance_sensor: sensor.helligkeit_la_pm
  keeping_off_entities:
    - switch.la_schlaft
    - switch.bleib_so_la_licht
  keeping_on_entities:
    - switch.bleib_so_la_licht
  switching_off_entities:
    - switch.la_schlaft
  special_brightness_entities:
    binary_sensor.schlafen_oder_aufwachphase_la: 5
auto_light_o_la_wuerfel:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_la
  light: light.wandwurfel_la
  type: dim
  triggers: 
    - binary_sensor.pm_o_ko_la_raum
    - binary_sensor.pm_o_ko_la_tuer
  brightness_values:
    "00:00": 30
    "05:30": 40
    "06:30": 50
    "08:00": 60
    "09:00": 70
    "17:00": 60
    "18:00": 50
    "20:00": 40
    "21:00": 30
  min_illuminance_values:
    "00:00": 5
    "05:30": 20
    "09:00": 50
    "18:00": 20
    "21:00": 5
  illuminance_sensor: sensor.helligkeit_la_pm
  keeping_fix_entities:
    switch.la_schlaft: 2
  keeping_off_entities:
    - switch.bleib_so_la_licht
  keeping_on_entities:
    - switch.bleib_so_la_licht
  special_brightness_entities:
    binary_sensor.schlafen_oder_aufwachphase_la: 30
auto_light_o_la_stehlampe:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_la
  light: light.innr_e14_ww_stehlampe_lara_level_on_off
  type: dim
  triggers: 
    - binary_sensor.pm_o_ko_la_raum
    - binary_sensor.pm_o_ko_la_tuer
  brightness_values:
    "00:00": 80
  min_illuminance_values:
    "00:00": 0
  illuminance_sensor: sensor.helligkeit_la_pm
  keeping_off_entities:
    - switch.la_schlaft
  switching_off_entities:
    - switch.la_schlaft
# --- Dim-Steps ---
dimmer_steps_panels_la:
  module: dimmer_steps
  class: dimmer_steps
  light_entity: light.panels_la
  steps:
    - 0
    - 5
    - 30
    - 50
    - 70
    - 100
  command_ga: "15/0/29"
dimmer_steps_wuerfel_la:
  module: dimmer_steps
  class: dimmer_steps
  light_entity: light.wandwurfel_la
  steps:
    - 0
    - 3
    - 20
    - 55
    - 100
  command_ga: "15/0/48"
dimmer_steps_stehlampe_la:
  module: dimmer_steps
  class: dimmer_steps
  light_entity: light.innr_e14_ww_stehlampe_lara_level_on_off
  steps:
    - 0
    - 3
    - 15
    - 50
    - 100
  command_ga: "15/0/66"
