# - WC panels
auto_light_e_wc_panels:
  module: auto_light_beta
  class: auto_light
  debug: few
  constrain_input_boolean: input_boolean.app_switch_licht_wc
  light: light.panels_wc
  type: dim
  triggers: 
    - binary_sensor.pm_e_wc
  brightness_values:
    "00:00": 20
    "09:00": 80
    "17:00": 70
    "18:30": 60
    "20:00": 20
  min_illuminance_values:
    "00:00": 5
    "05:00": 10
    "06:30": 20
    "09:00": 25
    "17:00": 20
    "19:00": 10
    "23:00": 5
  illuminance_sensor: sensor.helligkeit_wc_pm
  switching_off_offset: 20
  special_brightness_entities:
    switch.majo_schlafen: 5
# - WC Spiegel
auto_light_e_wc_spiegel:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_wc
  light: light.spiegel_wc
  type: switch
  triggers: 
    - binary_sensor.pm_e_wc
  min_illuminance_values:
    "00:00": 10
    "05:00": 20
    "06:30": 30
    "09:00": 40
    "17:00": 30
    "19:00": 20
    "23:00": 10
  illuminance_sensor: sensor.helligkeit_wc_pm
  keeping_off_entities:
    - switch.majo_schlafen
