# - Bad OG
#auto_light_o_ba_panels:
#  module: auto_light
#  class: auto_light
#  debug: quiet
#  app_switch: input_boolean.app_switch_licht_bad_og
#  light: light.panels_bad_og
#  type: dim
#  triggers: 
#    - binary_sensor.pm_o_ba
#  brightness_values:
#    "00:00": 50
#    "06:00": 75
#    "09:00": 90
#    "21:00": 70
#  min_illuminance_values:
#    "00:00": 25
#    "06:00": 40
#  illuminance_sensor: sensor.helligkeit_bad_og_pm
#  keeping_off_entities:
#    - switch.bad_og_nachtmodus
#  switching_off_entities:
#    - switch.bad_og_nachtmodus
#  special_brightness_entities:
#    binary_sensor.aufwachphase_kinder: 15
#auto_light_o_ba_spiegel_oben:
#  module: auto_light
#  class: auto_light
#  debug: quiet
#  app_switch: input_boolean.app_switch_licht_bad_og
#  light: light.led_auf_spiegelschrank_bad_og
#  type: dim
#  triggers: 
#    - binary_sensor.pm_o_ba
#  brightness_values:
#    "00:00": 90
#  min_illuminance_values:
#    "00:00": 90
#  illuminance_sensor: sensor.helligkeit_bad_eg_pm
#  special_brightness_entities:
#    switch.bad_og_nachtmodus: 13
#    binary_sensor.aufwachphase_kinder: 65
#auto_light_o_ba_spiegel:
#  module: auto_light
#  class: auto_light
#  debug: quiet
#  app_switch: input_boolean.app_switch_licht_bad_og
#  light: light.spiegel_bad_og
#  type: switch
#  triggers: 
#    - binary_sensor.pm_o_ba
#  min_illuminance_values:
#    "00:00": 0
#  illuminance_sensor: sensor.helligkeit_bad_og_pm
