# - Bad EG
auto_light_e_ba_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_bad_eg
  light: light.panels_bad_eg
  type: dim
  triggers: 
    - binary_sensor.pm_e_ba
  brightness_values:
    "00:00": 20
    "06:00": 50
    "07:00": 60
    "08:00": 80
    "17:00": 70
    "18:00": 60
  min_illuminance_values:
    "00:00": 10
    "06:00": 25
    "07:00": 40
    "08:00": 50
    "17:00": 40
    "18:00": 20
  illuminance_sensor: sensor.helligkeit_bad_eg_pm
auto_light_e_ba_spiegel:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_bad_eg
  light: light.spiegel_bad_eg
  type: dim
  min_illuminance_values:
    "00:00": 0
  switching_off_entities:
    - switch.majo_schlafen
