auto_light_o_nz_naehtisch:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_naehzimmer
  light: light.nahtisch_decke
  type: switch
  triggers: 
    - binary_sensor.pm_o_nz
  min_illuminance_values:
    "00:00": 0
  illuminance_sensor: sensor.helligkeit_nahzimmer_pm
auto_light_o_nz_schreibtisch:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_naehzimmer
  light: light.schreibtisch_decke
  type: switch
  triggers: 
    - binary_sensor.pm_o_nz
  min_illuminance_values:
    "00:00": 0
  illuminance_sensor: sensor.helligkeit_nahzimmer_pm
