# - Le
auto_light_o_le_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_le
  light: light.panels_le
  triggers: 
    - binary_sensor.pm_o_kw_le_raum
    - binary_sensor.pm_o_kw_le_tuer
  brightness_values:
    "00:00": 30
    "05:30": 50
    "06:30": 70
    "08:00": 80
    "09:00": 90
    "17:00": 80
    "18:00": 50
    "20:00": 40
    "21:00": 30
  min_illuminance_values:
    "00:00": 5
    "05:30": 20
    "09:00": 50
    "18:00": 20
    "21:00": 5
  illuminance_sensor: sensor.helligkeit_le_pm
  keeping_off_entities:
    - switch.le_schlaft
  special_brightness_entities:
    binary_sensor.aufwachphase_le: 10
