# - Flur EG
#auto_light_e_fl_panels:
#  module: auto_light
#  class: auto_light
#  debug: quiet
#  app_switch: input_boolean.app_switch_licht_flur_eg
#  light: light.panels_flur_eg
#  type: dim
#  triggers: 
#    - binary_sensor.pm_e_fl_treppe_og
#    - binary_sensor.pm_e_fl_windfang
#    - binary_sensor.pm_e_wf_flur
#    - binary_sensor.pm_e_wf_garderobe
#    - binary_sensor.pm_o_fl_treppe
#    - binary_sensor.pm_e_wc
#    - binary_sensor.pm_ktr_flur
#    - binary_sensor.pm_k_fl
#  brightness_values:
#    "00:00": 35
#    "03:00": 10
#    "06:30": 60
#    "09:00": 80
#    "17:00": 50
#    "18:30": 35
#  min_illuminance_values:
#    "00:00": 5
#    "06:30": 20
#    "09:00": 25
#    "17:00": 20
#    "19:00": 15
#    "23:00": 10
#  illuminance_sensor: sensor.helligkeit_flur_eg_pm
##  special_brightness_entities:
##    switch.majo_schlafen: 5
#  keeping_off_entities:
#    - switch.majo_schlafen
#    - binary_sensor.schlafen_oder_aufwachphase_majo
#    - switch.luften_ez
#    - switch.luften_sz
#  switching_off_entities:
#    - switch.majo_schlafen
#    - switch.knutschen
#    - switch.luften_ez
#    - switch.luften_sz
#auto_light_e_fl_stehlampe_oben:
#  module: auto_light
#  class: auto_light
#  debug: quiet
#  app_switch: input_boolean.app_switch_licht_flur_eg
#  light: light.innr_e27_rgb_flur_eg_oben_level_light_color_on_off
#  type: color
#  triggers: 
#    - binary_sensor.pm_e_fl_treppe_og
#    - binary_sensor.pm_e_fl_windfang
#    - binary_sensor.pm_e_wf_flur
#    - binary_sensor.pm_e_wf_garderobe
#    - binary_sensor.pm_o_fl_treppe
#    - binary_sensor.pm_e_wc
#    - binary_sensor.pm_e_sz_gang
#    - binary_sensor.pm_ktr_flur
#    - binary_sensor.pm_k_fl
#  min_illuminance_values:
#  brightness_values:
#    "00:00": [20, "orange"]
#    "06:30": [40, "orange"]
#    "09:00": [40, "pink"]
#    "17:00": [40, "orange"]
#    "19:00": [20, "orange"]
#  min_illuminance_values:
#    "00:00": 50
#  illuminance_sensor: sensor.helligkeit_flur_eg_pm
#  keeping_off_entities:
#    - switch.majo_schlafen
#    - switch.knutschen
#    - switch.luften_ez
#    - switch.luften_sz
#  switching_off_entities:
#    - switch.majo_schlafen
#    - switch.knutschen
#    - switch.luften_ez
#    - switch.luften_sz
#auto_light_e_fl_stehlampe_unten:
#  module: auto_light
#  class: auto_light
#  debug: quiet
#  app_switch: input_boolean.app_switch_licht_flur_eg
#  light: light.innr_e27_rgb_flur_eg_unten_level_light_color_on_off
#  type: color
#  triggers: 
#    - binary_sensor.pm_e_fl_treppe_og
#    - binary_sensor.pm_e_fl_windfang
#    - binary_sensor.pm_e_wf_flur
#    - binary_sensor.pm_e_wf_garderobe
#    - binary_sensor.pm_o_fl_treppe
#    - binary_sensor.pm_e_wc
#    - binary_sensor.pm_e_sz_gang
#    - binary_sensor.pm_ktr_flur
#    - binary_sensor.pm_k_fl
#  min_illuminance_values:
#  brightness_values:
#    "00:00": [20, "rot"]
#    "06:30": [40, "rot"]
#    "09:00": [40, "lila"]
#    "17:00": [40, "rot"]
#    "19:00": [20, "rot"]
#  min_illuminance_values:
#    "00:00": 50
#  illuminance_sensor: sensor.helligkeit_flur_eg_pm
#  keeping_off_entities:
#    - switch.majo_schlafen
#    - switch.knutschen
#    - switch.luften_ez
#    - switch.luften_sz
#  switching_off_entities:
#    - switch.majo_schlafen
#    - switch.knutschen
#    - switch.luften_ez
#    - switch.luften_sz
