# - Esszimmer
auto_light_e_ez_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_esszimmer
  light: light.panels_esszimmer
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 50
    "06:00": 60
    "06:30": 78
    "19:00": 70
    "21:30": 50
  min_illuminance_values:
    "00:00": 10
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "18:30": 30
    "21:30": 10
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  special_brightness_entities:
    switch.majo_schlafen: 10
    input_boolean.gaeste_abends: 45
  keeping_off_entities:
    - binary_sensor.tv_abends_an
  switching_off_entities:
    - switch.majo_schlafen
    - binary_sensor.tv_abends_an
auto_light_e_ez_wandleuchten_hell:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_esszimmer
  light: light.wandleuchten_esszimmer_hell
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 50
    "06:00": 60
    "06:30": 70
    "19:30": 55
    "21:30": 50
  min_illuminance_values:
    "00:00": 10
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "18:30": 30
    "21:30": 10
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  keeping_off_entities:
    - switch.majo_schlafen
    - binary_sensor.tv_zeit_abend
    - input_boolean.gaeste_abends
  switching_off_entities:
    - switch.majo_schlafen
    - binary_sensor.tv_zeit_abend
    - input_boolean.gaeste_abends
auto_light_e_ez_wandleuchten_warm:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_esszimmer
  light: light.wandleuchten_esszimmer_gemutlich
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 0
    "06:00": 0
  min_illuminance_values:
    "00:00": 100
    "06:30": 100
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  special_brightness_entities:
    switch.majo_schlafen: 20
    binary_sensor.tv_zeit_abend: 80
  keeping_fix_entities:
    binary_sensor.kodi_abends: 20
  switching_off_entities:
    - switch.majo_schlafen
auto_light_e_ez_theke_warm:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_esszimmer
  light: light.bar_beleuchtung
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 0
    "06:00": 0
  min_illuminance_values:
    "00:00": 100
    "06:30": 100
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  special_brightness_entities:
    switch.majo_schlafen: 20
    binary_sensor.tv_zeit_abend: 80
  keeping_fix_entities:
    binary_sensor.kodi_abends: 20
  switching_off_entities:
    - switch.majo_schlafen
auto_light_e_ez_christbaum:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_christbaum
  light: light.sd_fussraum_bar
  type: switch
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  min_illuminance_values:
    "00:00": 400
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  keeping_off_entities:
    - binary_sensor.tv_abends_an
  switching_off_entities:
    - switch.majo_schlafen
    - binary_sensor.tv_abends_an
# - Küche
auto_light_e_ku_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_kueche
  light: light.panels_kuche
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 40
    "04:30": 50
    "06:00": 60
    "06:30": 78
    "18:30": 70
    "21:30": 40
  min_illuminance_values:
    "00:00": 10
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "09:00": 50
    "17:00": 40
    "18:30": 30
    "21:30": 10
  illuminance_sensor: sensor.helligkeit_kuche_pm
  special_brightness_entities:
    switch.majo_schlafen: 10
    input_boolean.gaeste_abends: 35
    binary_sensor.kodi_abends: 0.3
auto_light_e_ku_arbeitsplatte:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_kueche
  light: light.arbeitsplatte
  type: dim
  triggers: 
    - binary_sensor.pm_e_ku_kuche
  brightness_values:
    "00:00": 40
    "06:00": 60
    "06:30": 65
    "09:00": 80
    "17:00": 70
    "17:30": 60
    "19:30": 50
    "22:00": 40
  min_illuminance_values:
    "00:00": 80
    "06:00": 100
    "08:30": 125
    "09:00": 150
    "17:00": 125
    "20:00": 100
    "22:00": 80
  illuminance_sensor: sensor.helligkeit_kuche_pm
  special_brightness_entities:
    switch.majo_schlafen: 20
    input_boolean.gaeste_abends: 35
    binary_sensor.kodi_abends: 0.3
# - Bar Panels
auto_light_e_bar_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_kueche
  light: light.panels_bar
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 40
    "04:30": 50
    "06:00": 60
    "06:30": 78
    "18:30": 65
    "21:30": 40
  min_illuminance_values:
    "00:00": 10
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "18:30": 30
    "21:30": 10
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  special_brightness_entities:
    switch.majo_schlafen: 10
    binary_sensor.tv_pizza_abend: 50
  keeping_off_entities:
    - binary_sensor.kodi_abends
    - input_boolean.gaeste_abends
  switching_off_entities:
    - binary_sensor.kodi_abends
    - input_boolean.gaeste_abends
# - Wohnzimmer
auto_light_e_wz_panels:
  module: auto_light_beta
  class: auto_light
  debug: quiet
  constrain_input_boolean: input_boolean.app_switch_licht_wohnzimmer
  light: light.panels_wohnzimmer
  type: dim
  triggers: 
    - binary_sensor.pm_e_wz_durchgang
    - binary_sensor.pm_e_wz_couch_links
    - binary_sensor.pm_e_wz_couch_rechts
  brightness_values:
    "00:00": 50
    "06:00": 60
    "06:30": 70
    "07:00": 80
    "19:00": 50
    "20:00": 40
    "21:00": 30
    "22:00": 20
  min_illuminance_values:
    "00:00": 20
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "09:00": 50
    "17:00": 40
    "18:30": 30
    "21:30": 20
  illuminance_sensor: sensor.helligkeit_wohnzimmer_pm
  special_brightness_entities:
    binary_sensor.tv_ist_an: 50
  keeping_fix_entities:
    binary_sensor.tv_pizza_abend: 5
    binary_sensor.tv_abend_ohne_pizza: 2
  keeping_on_entities:
    - switch.bleib_so_wz_licht
  keeping_off_entities:
    - switch.bleib_so_wz_licht
