auto_light_k_vorratsraum:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_keller
  light: light.vorratsraum
  type: switch
  triggers: 
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_83155c04_on_off
    - binary_sensor.pm_k_timer_magnetsensor_vorratsraum
  min_illuminance_values:
    "00:00": 1
auto_light_k_werkelraum:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_keller
  light: light.werkelraum
  type: switch
  triggers: 
    - binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy
    - binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone
  min_illuminance_values:
    "00:00": 1
