# - Esszimmer
auto_light_e_ez_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_esszimmer
  light: light.panels_esszimmer
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 50
    "06:00": 80
    "06:30": 85
    "09:00": 90
    "19:00": 78
    "21:30": 50
  min_illuminance_values:
    "00:00": 40
    "07:00": 60
    "08:00": 80
    "18:30": 60
    "21:30": 40
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  special_brightness_entities:
    binary_sensor.nachtmodus_wohnbereich_licht: 10
    input_boolean.gaeste_abends: 50
  switching_off_entities:
    - binary_sensor.tv_abends_an
    - input_boolean.arbeit_theke
  keeping_off_entities:
    - binary_sensor.tv_abends_an
    - input_boolean.arbeit_theke
auto_light_e_ez_wandleuchten_hell:
  module: auto_light_beta
  class: auto_light
  debug: few
  app_switch: input_boolean.app_switch_licht_esszimmer
  light: light.wandleuchten_esszimmer_hell
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 50
    "06:00": 60
    "06:30": 70
    "19:30": 55
    "21:30": 50
  min_illuminance_values:
    "00:00": 40
    "07:00": 60
    "08:00": 80
    "18:30": 60
    "21:30": 40
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  keeping_off_entities:
    - binary_sensor.nachtmodus_wohnbereich_licht
    - binary_sensor.tv_zeit_abend
    - input_boolean.gaeste_abends
    - input_boolean.arbeit_theke
  switching_off_entities:
    - binary_sensor.tv_zeit_abend
    - input_boolean.gaeste_abends
    - input_boolean.arbeit_theke
auto_light_e_ez_wandleuchten_warm:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_esszimmer
  light: light.wandleuchten_esszimmer_gemutlich
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 60
    "04:00": 0
    "18:55": 60
  min_illuminance_values:
    "00:00": 60
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  special_brightness_entities:
    binary_sensor.nachtmodus_wohnbereich_licht: 20
#    binary_sensor.tv_zeit_abend: 60
    input_boolean.gaeste_abends: 70
  switching_off_entities:
    - binary_sensor.kodi_abends
    - input_boolean.arbeit_theke
  keeping_off_entities:
    - input_boolean.arbeit_theke
auto_light_e_ez_theke_warm:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_esszimmer
  light: light.bar_beleuchtung
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 40
    "06:00": 50
  min_illuminance_values:
    "00:00": 60
  switching_off_offset: 60
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  special_brightness_entities:
    binary_sensor.nachtmodus_wohnbereich_licht: 20
    binary_sensor.tv_zeit_abend: 60
    input_boolean.gaeste_abends: 55
  keeping_off_entities:
    - input_boolean.arbeit_theke
  switching_off_entities:
    - input_boolean.arbeit_theke
auto_light_e_ez_christbaum:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_christbaum
  light: light.sd_fussraum_bar
  type: switch
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  min_illuminance_values:
    "00:00": 400
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  keeping_off_entities:
    - binary_sensor.tv_abends_an
  switching_off_entities:
    - binary_sensor.tv_abends_an
# - Küche
auto_light_e_ku_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_kueche
  light: light.panels_kuche
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 40
    "04:30": 50
    "06:00": 60
    "06:30": 78
    "18:30": 70
    "21:30": 40
  min_illuminance_values:
    "00:00": 10
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "09:00": 50
    "17:00": 40
    "18:30": 30
    "21:30": 10
  illuminance_sensor: sensor.helligkeit_kuche_pm
  special_brightness_entities:
    binary_sensor.nachtmodus_wohnbereich_licht: 10
    input_boolean.gaeste_abends: 35
    binary_sensor.tv_abends_an: 25
  switching_off_entities:
    - binary_sensor.kodi_abends
    - input_boolean.arbeit_theke
  keeping_off_entities:
    - input_boolean.arbeit_theke
auto_light_e_ku_arbeitsplatte:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_kueche
  light: light.arbeitsplatte
  type: dim
  triggers: 
    - binary_sensor.pm_e_ku_kuche
  brightness_values:
    "00:00": 40
    "06:00": 60
    "06:30": 65
    "09:00": 80
    "17:30": 70
    "19:30": 60
    "22:00": 40
  min_illuminance_values:
    "00:00": 80
    "06:00": 150
    "08:30": 250
    "09:00": 300
    "20:00": 200
    "22:00": 80
  illuminance_sensor: sensor.helligkeit_kuche_pm
  special_brightness_entities:
    binary_sensor.nachtmodus_wohnbereich_licht: 20
    input_boolean.gaeste_abends: 35
    binary_sensor.kodi_abends: 5
    binary_sensor.tv_abends_an: 30
  switching_off_offset: 200
auto_light_e_ku_sockel:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_kueche
  light: light.sockelbeleuchtung
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 45
    "09:00": 0
    "19:00": 45
  min_illuminance_values:
    "00:00": 100
    "09:00": 0
    "19:00": 100
  illuminance_sensor: sensor.helligkeit_kuche_pm
  special_brightness_entities:
    binary_sensor.nachtmodus_wohnbereich_licht: 20
    input_boolean.gaeste_abends: 40
    binary_sensor.kodi_abends: 20
    binary_sensor.tv_abends_an: 20
  switching_off_entities:
    - binary_sensor.kodi_abends
    - input_boolean.arbeit_theke
  keeping_off_entities:
    - input_boolean.arbeit_theke
# - Bar Panels
auto_light_e_bar_panels:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_kueche
  light: light.panels_bar
  type: dim
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
  brightness_values:
    "00:00": 40
    "04:30": 50
    "06:00": 60
    "06:30": 78
    "18:30": 65
    "21:30": 40
  min_illuminance_values:
    "00:00": 10
    "06:30": 20
    "07:00": 30
    "08:00": 40
    "18:30": 30
    "21:30": 10
  illuminance_sensor: sensor.helligkeit_esszimmer_pm
  special_brightness_entities:
    binary_sensor.nachtmodus_wohnbereich_licht: 10
    binary_sensor.tv_pizza_abend: 50
  keeping_off_entities:
    - binary_sensor.kodi_abends
    - input_boolean.gaeste_abends
  switching_off_entities:
    - binary_sensor.kodi_abends
    - input_boolean.gaeste_abends
# - Wohnzimmer
auto_light_e_wz_panels:
  module: auto_light_beta
  class: auto_light
  debug: few
  app_switch: input_boolean.app_switch_licht_wohnzimmer
  light: light.panels_wohnzimmer
  type: dim
  triggers: 
    - binary_sensor.pm_e_wz_durchgang
    - binary_sensor.pm_e_wz_couch_links
    - binary_sensor.pm_e_wz_couch_rechts
  brightness_values:
    "00:00": 50
    "06:00": 60
    "06:30": 70
    "07:00": 80
    "19:00": 50
    "20:00": 40
    "21:00": 30
    "22:00": 20
  min_illuminance_values:
    "00:00": 20
    "07:00": 30
    "08:00": 40
    "09:00": 50
    "17:00": 40
    "18:30": 30
    "21:30": 20
  illuminance_sensor: sensor.helligkeit_wohnzimmer_pm
  special_brightness_entities:
    binary_sensor.tv_ist_an: 55
  keeping_on_entities:
    - switch.bleib_so_wz_licht
  keeping_off_entities:
    - switch.bleib_so_wz_licht
    - binary_sensor.tv_zeit_abend
  switching_off_entities:
    - binary_sensor.tv_zeit_abend
auto_light_e_wz_schrankbeleuchtung:
  module: auto_light_beta
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_wohnzimmer
  light: light.schrankbeleuchtung_wohnzimmer
  type: dim
  triggers: 
  triggers: 
    - binary_sensor.pm_e_wz_durchgang
    - binary_sensor.pm_e_wz_couch_links
    - binary_sensor.pm_e_wz_couch_rechts
  brightness_values:
    "00:00": 40
    "19:00": 80
    "22:00": 50
  min_illuminance_values:
    "00:00": 150
  illuminance_sensor: sensor.helligkeit_wohnzimmer_pm
  keeping_fix_entities:
    binary_sensor.tv_pizza_abend: 30
    binary_sensor.tv_abend_ohne_pizza: 20
    input_boolean.gaeste_abends: 80
auto_light_e_wz_stehlampe:
  module: auto_light_beta
  class: auto_light
  debug: few
  app_switch: input_boolean.app_switch_licht_wohnzimmer
  light: light.innr_e27_color_stehlampe_wz_level_light_color_on_off
  type: color
  rgb_color: [255, 127, 0]
  triggers: 
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_wz_durchgang
    - binary_sensor.pm_e_wz_couch_links
    - binary_sensor.pm_e_wz_couch_rechts
  brightness_values:
    "00:00": 50
    "19:00": 70
    "22:00": 50
  min_illuminance_values:
    "00:00": 150
  illuminance_sensor: sensor.helligkeit_wohnzimmer_pm
  keeping_fix_entities:
    binary_sensor.tv_pizza_abend: 20
    binary_sensor.tv_abend_ohne_pizza: 1
    input_boolean.gaeste_abends: 80
dim_steps_wz:
  module: dimmer_steps
  class: dimmer_steps
  light_entity: light.panels_wohnzimmer
  steps:
    - 0
    - 5
    - 30
    - 85
    - 100
  command_ga: "15/0/58"
