# - LED-Streifen Carport
#auto_light_a_cp_led_streifen:
#  module: auto_light
#  class: auto_light
#  debug: quiet
#  app_switch: input_boolean.app_switch_licht_aussen_carport
#  light: light.led_streifen_carport
#  type: dim
#  triggers: 
#    - binary_sensor.pm_a_eg
#    - binary_sensor.pm_a_cp
#  keeping_on_entities:
#    - binary_sensor.pm_a_ar
#  brightness_values:
#    "00:00": 60
#  min_illuminance_values:
#    "00:00": 800
#  illuminance_sensor: sensor.helligkeit_wetterstation
auto_light_a_eg_bodenlicht:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.bodenlicht_eingang
  type: dim
  triggers: 
    - binary_sensor.pm_a_eg
    - binary_sensor.pm_a_cp
  keeping_on_entities:
    - binary_sensor.pm_a_ar
  brightness_values:
    "00:00": 70
  min_illuminance_values:
    "00:00": 800
  illuminance_sensor: sensor.helligkeit_wetterstation
# - Spots Carport
auto_light_a_cp_spots:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.spots_carport_2
  type: dim
  triggers: 
    - binary_sensor.pm_a_eg
    - binary_sensor.pm_a_cp
  keeping_on_entities:
    - binary_sensor.pm_a_ar
  brightness_values:
    "00:00": 80
  min_illuminance_values:
    "00:00": 2000
  illuminance_sensor: sensor.helligkeit_wetterstation
# - Abstellraum
#auto_light_a_abstellraum:
#  module: auto_light
#  class: auto_light
#  debug: quiet
#  app_switch: input_boolean.app_switch_licht_aussen_carport
#  light: light.abstellraum_carport
#  type: switch
#  triggers: 
#    - binary_sensor.pm_a_ar
#  keeping_on_entities:
#    - binary_sensor.pm_a_eg
#    - binary_sensor.pm_a_cp
#  min_illuminance_values:
#    "00:00": 4000000
#  illuminance_sensor: sensor.helligkeit_wetterstation
# - Leuchtwürfel Terrasse
auto_light_a_tr_wurfel_feuerplatz:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.innr_e27_color_terrasse_feuerplatz_level_light_color_on_off
  type: color
  triggers: 
    - binary_sensor.hst_offen
  min_illuminance_values:
    "00:00": 2000
  brightness_values:
    "00:00": [85, "rot"]
  illuminance_sensor: sensor.helligkeit_wetterstation
auto_light_a_tr_wurfel_ecke_klein:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.innr_rb_285_c_55f50405_level_light_color_on_off
  type: color
  triggers: 
    - binary_sensor.hst_offen
  min_illuminance_values:
    "00:00": 2000
  brightness_values:
    "00:00": [80, "orange"]
  illuminance_sensor: sensor.helligkeit_wetterstation
auto_light_a_tr_wurfel_ecke_gross:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_aussen_carport
  light: light.innr_rb_285_c_7cc30105_level_light_color_on_off
  type: color
  triggers: 
    - binary_sensor.hst_offen
  min_illuminance_values:
    "00:00": 2000
  brightness_values:
    "00:00": [85, "pink"]
  illuminance_sensor: sensor.helligkeit_wetterstation
# - Stern Blumenbeet
#auto_light_a_tr_blumenbeet:
#  module: auto_light
#  class: auto_light
#  debug: few
#  app_switch: input_boolean.app_switch_licht_aussen_carport
#  light: light.licht_blumenbeet
#  type: switch
#  triggers: 
#    - binary_sensor.zeit_stern
#  min_illuminance_values:
#    "00:00": 5000
#  illuminance_sensor: sensor.helligkeit_wetterstation
auto_light_a_tr_bodenstrahler_blumenbeet:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_bodenstrahler_blumenbeet
  light: light.bodenstrahler_blumenbeet
  type: switch
  triggers: 
    - binary_sensor.bodenstrahler_blumenbeet_soll_an_sein
  min_illuminance_values:
    "00:00": 200
  illuminance_sensor: sensor.helligkeit_wetterstation
auto_light_a_tr_stern_blumenbeet:
  module: auto_light
  class: auto_light
  debug: quiet
  app_switch: input_boolean.app_switch_licht_stern_blumenbeet
  light: light.stern_blumenbeet
  type: switch
  triggers: 
    - binary_sensor.zeit_stern
  min_illuminance_values:
    "00:00": 10000
  illuminance_sensor: sensor.helligkeit_wetterstation
