luftentfeuchter_waschkueche:
  module: air_dryer_and_humidifier
  class: air_dryer_and_humidifier
  machine_type: dryer
  air_dryer_or_humidifier_switch: switch.innr_sp_120_luftentfeuchter_waschkuche_on_off
  energy_measurement_sensor: sensor.innr_sp_120_luftentfeuchter_waschkuche_electrical_measurement
  humidity_sensor: sensor.luftfeuchtigkeit_waschkuche
#  humidity_sensor: sensor.dht22_waschkueche_humidity
  humidity_standard_max: 59
  humidity_standard_min: 54
  humidity_special_max: 54
  humidity_special_min: 49
  zigbee: True
  zha_device_ieee: '00:15:8d:00:04:0b:11:2f'
  zha_device_command_time_1: left_single
  time_1_hours: 4
  zha_device_command_time_2: left_double
  time_2_hours: 8
  input_number_timer_special_humidity: input_number.timer_spezial_luftf_waschk
  name_reminder_switch_tank: switch.reminder_luftentfeuchter_waschkueche_tank
  text_reminder_switch_tank: "Tank Luftentfeucher Waschküche leeren"
luftentfeuchter_partyraum:
  module: air_dryer_and_humidifier
  class: air_dryer_and_humidifier
  machine_type: dryer
  air_dryer_or_humidifier_switch: switch.innr_sp_120_test_on_off
  energy_measurement_sensor: sensor.innr_sp_120_test_electrical_measurement
  humidity_sensor: sensor.luftfeuchtigkeit_partyraum
  humidity_standard_max: 58
  humidity_standard_min: 56
  humidity_special_max: 53
  humidity_special_min: 51
  zigbee: False
  input_number_timer_special_humidity: input_number.timer_spezial_luftf_werkelraum
  name_reminder_switch_tank: switch.reminder_luftentfeuchter_werkelraum_tank
  text_reminder_switch_tank: "Tank Luftentfeucher Werkelraum leeren"
luftbefeuchter_wz:
  module: air_dryer_and_humidifier
  class: air_dryer_and_humidifier
  machine_type: humidifier
  air_dryer_or_humidifier_switch: switch.tasmota_sd_2
  energy_measurement_sensor: sensor.tasmota_sd_2_wirkleistung
  humidity_sensor: sensor.luftfeuchtigkeit_kuche_aqara
  humidity_standard_max: 50
  humidity_standard_min: 46
  humidity_special_max: 55
  humidity_special_min: 51
  zigbee: False
  input_number_timer_special_humidity: input_number.timer_spezial_luftf_wz
  name_reminder_switch_tank: switch.reminder_luftbefeuchter_wz_tank
  text_reminder_switch_tank: "Luftbefeuchter WZ füllen"
