luftentfeuchter_waschkueche:
  module: air_dryer_and_humidifier
  class: air_dryer_and_humidifier
  machine_type: dryer
  air_dryer_or_humidifier_switch: switch.innr_sp_120_luftentfeuchter_waschkuche_on_off
  energy_measurement_sensor: sensor.el_leistung_innr_sp_120_luftentfeuchter_waschkuche
  humidity_sensor: sensor.luftfeuchtigkeit_waschkuche
#  humidity_sensor: sensor.dht22_waschkueche_humidity
  humidity_standard_max: 50
  humidity_standard_min: 45
  humidity_special_max: 47
  humidity_special_min: 42
  use_pv_power: True
  pv_power_sensor: sensor.statistics_el_leistung_einspeisung_letzte_3_min
  pv_power_for_step_1: 300
  humidity_change_step_1: 5
  zigbee: True
  zha_device_ieee: '00:15:8d:00:04:0b:11:2f'
  zha_device_command_time_1: left_single
  time_1_hours: 4
  zha_device_command_time_2: left_double
  time_2_hours: 8
  input_number_timer_special_humidity: input_number.timer_spezial_luftf_waschk
  name_reminder_switch_tank: switch.reminder_luftentfeuchter_waschkueche_tank
  text_reminder_switch_tank: "Luftentfeucher Waschküche leeren"
luftentfeuchter_partyraum:
  module: air_dryer_and_humidifier
  class: air_dryer_and_humidifier
  machine_type: dryer
  air_dryer_or_humidifier_switch: switch.innr_sp_120_luftentfeuchter_partyraum
  energy_measurement_sensor: sensor.el_leistung_innr_sp_120_luftentfeuchter_partyraum
  humidity_sensor: sensor.luftfeuchtigkeit_partyraum
  humidity_standard_max: 58
  humidity_standard_min: 56
  humidity_special_max: 53
  humidity_special_min: 51
  use_pv_power: True
  pv_power_sensor: sensor.statistics_el_leistung_einspeisung_letzte_3_min
  pv_power_for_step_1: 500
  humidity_change_step_1: 10
  zigbee: False
  input_number_timer_special_humidity: input_number.timer_spezial_luftf_werkelraum
  name_reminder_switch_tank: switch.reminder_luftentfeuchter_werkelraum_tank
  text_reminder_switch_tank: "Luftentfeuchter Partyraum leeren"
luftentfeuchter_speis:
  module: air_dryer_and_humidifier
  class: air_dryer_and_humidifier
  machine_type: dryer
  air_dryer_or_humidifier_switch: switch.kuhlschrank_keller
  energy_measurement_sensor: sensor.el_leistung_kuhlschrank_keller
  humidity_sensor: sensor.luftfeuchtigkeit_vorratsraum
  humidity_standard_max: 52
  humidity_standard_min: 48
  humidity_special_max: 48
  humidity_special_min: 42
  use_pv_power: True
  pv_power_sensor: sensor.statistics_el_leistung_einspeisung_letzte_3_min
  pv_power_for_step_1: 100
  humidity_change_step_1: 8
  zigbee: False
  input_number_timer_special_humidity: input_number.timer_spezial_luftf_vorratsraum
  name_reminder_switch_tank: switch.reminder_luftentfeuchter_vorratsraum_tank
  text_reminder_switch_tank: "Luftentfeuchter Speis leeren"
#luftbefeuchter_wz:
#  module: air_dryer_and_humidifier
#  class: air_dryer_and_humidifier
#  machine_type: humidifier
#  air_dryer_or_humidifier_switch: switch.esp_sd_2_relais
#  energy_measurement_sensor: sensor.el_leistung_esp_sd_2
#  humidity_sensor: sensor.luftfeuchtigkeit_kuche_aqara
#  humidity_standard_max: 50
#  humidity_standard_min: 46
#  humidity_special_max: 55
#  humidity_special_min: 51
#  use_pv_power: False
#  zigbee: False
#  input_number_timer_special_humidity: input_number.timer_spezial_luftf_wz
#  name_reminder_switch_tank: switch.reminder_luftbefeuchter_wz_tank
#  text_reminder_switch_tank: "Luftbefeuchter WZ füllen"
