counter_to_power_meter_wp_heizstab:
  module: counter_to_power_meter
  class: counter_to_power_meter
  debug: False
  offset_kwh: 24.1
  knx_counter: sensor.stromzahler_wp_heizstab_rohdaten
  input_number_raw_value_persistent: input_number.speicher_stromzaehler_rohdaten_wp_heizstab
  ha_electricity_sensor_name: sensor.stromzahler_wp_heizstab
  ha_electricity_sensor_friendly_name: Stromz채hler WP Heizstab
  ha_power_sensor_name: sensor.el_leistung_wp_heizstab
  ha_power_sensor_friendly_name: El. Leistung WP Heizstab
  phases: 3
  energy_per_pulse: 0.0005
  knx_sending_every: 50
  cut_power_below: 10
counter_to_power_meter_wp_innenteil:
  module: counter_to_power_meter
  class: counter_to_power_meter
  debug: False
  offset_kwh: 98.1
  knx_counter: sensor.stromzahler_wp_innenteil_rohdaten
  input_number_raw_value_persistent: input_number.speicher_stromzaehler_rohdaten_wp_innen
  ha_electricity_sensor_name: sensor.stromzahler_wp_innenteil
  ha_electricity_sensor_friendly_name: Stromz채hler WP Innenteil
  ha_power_sensor_name: sensor.el_leistung_wp_innenteil
  ha_power_sensor_friendly_name: El. Leistung WP Innenteil
  phases: 1
  energy_per_pulse: 0.0005
  knx_sending_every: 2
  cut_power_below: 2
counter_to_power_meter_wp_aussenteil:
  module: counter_to_power_meter
  class: counter_to_power_meter
  debug: True
  offset_kwh: 1085.8
  knx_counter: sensor.stromzahler_wp_aussenteil_rohdaten
  input_number_raw_value_persistent: input_number.speicher_stromzaehler_rohdaten_wp_aussen
  ha_electricity_sensor_name: sensor.stromzahler_wp_aussenteil
  ha_electricity_sensor_friendly_name: Stromz채hler WP Aussenteil
  ha_power_sensor_name: sensor.el_leistung_wp_aussenteil
  ha_power_sensor_friendly_name: El. Leistung WP Aussenteil
  phases: 1
  energy_per_pulse: 0.001
  knx_sending_every: 10
  cut_power_below: 5
counter_to_power_meter_kochfeld:
  module: counter_to_power_meter
  class: counter_to_power_meter
  debug: False
  offset_kwh: 81.1
  knx_counter: sensor.stromzahler_kochfeld_rohdaten
  input_number_raw_value_persistent: input_number.speicher_stromzaehler_rohdaten_kochfeld
  ha_electricity_sensor_name: sensor.stromzahler_kochfeld
  ha_electricity_sensor_friendly_name: Stromz채hler Kochfeld
  ha_power_sensor_name: sensor.el_leistung_kochfeld
  ha_power_sensor_friendly_name: El. Leistung Kochfeld
  phases: 3
  energy_per_pulse: 0.0005
  knx_sending_every: 10
  cut_power_below: 10
