cover_blocking:
  module: cover_blocking
  class: cover_blocking
  outside_humidity_sensor: sensor.luftfeuchtigkeit_aussen
  outside_temperature_sensor: sensor.temp_aussen
  ice_blocking_switch: input_boolean.eisschutz_jalousien
  ice_blocking_automation_switch: input_boolean.automatik_eisschutz_jalousien
  rain_entity: binary_sensor.regenalarm
  temp_blocking_rain: 2
  temp_blocking_humidity: 0
  humidity_blocking: 95
  temp_release: 3
