jal_bad_kinder_abends_zeit:
  module: cover_timer
  class: cover_timer
  constrain_input_boolean: input_boolean.app_switch_jalousie_bad_og
  cover_entity: cover.jalousie_bad_og
  time: "18:30"
  position: 100
  tilt: 17
jal_bad_kinder_morgen_zeit:
  module: cover_timer
  class: cover_timer
  constrain_input_boolean: input_boolean.app_switch_jalousie_bad_og
  cover_entity: cover.jalousie_bad_og
  time: "08:00"
  position: 0
  tilt: 0
jal_schlafzimmer_abends_zeit:
  module: cover_timer
  class: cover_timer
  constrain_input_boolean: input_boolean.app_switch_jalousie_schlafzimmer
  cover_entity: cover.jalousie_schlafzimmer
  time: "21:30"
  position: 100
  tilt: 100
