jal_bad_og_sichtschutz_morgens:
  module: cover_tilt_pos_when_state_matched
  class: cover_tilt_pos_when_state_matched
  constrain_input_boolean: input_boolean.app_switch_jalousie_bad_og
  constrain_start_time: "04:00:00"
  constrain_end_time: "11:00:00"
  cover_entity: cover.jalousie_bad_og
  mode: tilt
  target_tilt: 17
  match_entity: switch.bad_og_nachtmodus
  match_state_new: 'off'
  match_state_old: 'on'
jal_ku_sichtschutz_morgens:
  module: cover_tilt_pos_when_state_matched
  class: cover_tilt_pos_when_state_matched
  constrain_input_boolean: input_boolean.app_switch_jalousie_kueche
  constrain_start_time: "04:00:00"
  constrain_end_time: "11:00:00"
  cover_entity: cover.jalousie_kuche
  mode: tilt
  target_tilt: 80
  match_entity: binary_sensor.nachtmodus_wohnbereich_jalousie
  match_state_new: 'off'
  match_state_old: 'on'
jal_hst_sichtschutz_morgens:
  module: cover_tilt_pos_when_state_matched
  class: cover_tilt_pos_when_state_matched
  constrain_input_boolean: input_boolean.app_switch_jalousie_esszimmer
  constrain_start_time: "04:00:00"
  constrain_end_time: "11:00:00"
  cover_entity: cover.jalousie_hst
  mode: tilt
  target_tilt: 80
  match_entity: binary_sensor.nachtmodus_wohnbereich_jalousie
  match_state_new: 'off'
  match_state_old: 'on'
jal_wz_bodent_sichtschutz_morgens:
  module: cover_tilt_pos_when_state_matched
  class: cover_tilt_pos_when_state_matched
  constrain_input_boolean: input_boolean.app_switch_jalousie_wohnzimmer
  constrain_start_time: "04:00:00"
  constrain_end_time: "11:00:00"
  cover_entity: cover.jalousie_wz_bodentiefes
  mode: tilt
  target_tilt: 80
  match_entity: binary_sensor.nachtmodus_wohnbereich_jalousie
  match_state_new: 'off'
  match_state_old: 'on'
jal_wz_couch_sichtschutz_morgens:
  module: cover_tilt_pos_when_state_matched
  class: cover_tilt_pos_when_state_matched
  constrain_input_boolean: input_boolean.app_switch_jalousie_wohnzimmer
  constrain_start_time: "04:00:00"
  constrain_end_time: "11:00:00"
  cover_entity: cover.jalousie_wz_couch
  mode: tilt
  target_tilt: 80
  match_entity: binary_sensor.nachtmodus_wohnbereich_jalousie
  match_state_new: 'off'
  match_state_old: 'on'
jal_sz_sichtschutz_morgens:
  module: cover_tilt_pos_when_state_matched
  class: cover_tilt_pos_when_state_matched
  constrain_input_boolean: input_boolean.app_switch_jalousie_schlafzimmer
  constrain_start_time: "04:00:00"
  constrain_end_time: "11:00:00"
  cover_entity: cover.jalousie_schlafzimmer
  mode: tilt
  target_tilt: 80
  match_entity: switch.majo_schlafen
  match_state_new: 'off'
  match_state_old: 'on'
