energy_consumption_from_power_logs:
  module: energy_consumption_from_power_logs
  class: energy_consumption_from_power_logs
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.el_leistung_luftungsanlage
  db_field: state_float
