energy_consumption_daily:
  module: energy_consumption_daily
  class: energy_consumption_daily
  price_per_kWh: 0.2809
  sensor_consumption_total: sensor.stromverbrauch_netzbezug_vortag
  sensors_consumption_detail:
    sensor.stromverbrauch_backofen_vortag: Backofen
    sensor.stromverbrauch_bildschirm_theke_vortag: Bildschirm Theke
    sensor.stromverbrauch_dauerverbraucher_vortag: Dauerverbraucher
    sensor.stromverbrauch_gefrierschrank_vortag: Gefrierschrank
    sensor.stromverbrauch_kochfeld_vortag: Kochfeld
    sensor.stromverbrauch_kuhlschrank_keller_vortag: Kühlschr. Keller
    sensor.stromverbrauch_kuhlschrank_kuche_vortag: Kühlschrank
    sensor.stromverbrauch_lg_anlage_vortag: LG-Anlage
    sensor.stromverbrauch_licht_gesamt_vortag: Licht
    sensor.stromverbrauch_luftentf_waschk_vortag: Luftentf. Waschk.
    sensor.stromverbrauch_luftentf_werkelraum_vortag: Luftentf. Partyr.
    sensor.stromverbrauch_luftungsanlage_vortag: Lüftungsanlage
    sensor.stromverbrauch_mixi_vortag: Mixi
    sensor.stromverbrauch_spulmaschine_vortag: Spülmaschine
    sensor.stromverbrauch_trockner_vortag: Trockner
    sensor.stromverbrauch_tv_vortag: TV
    sensor.stromverbrauch_waschmaschine_vortag: Waschmaschine
    sensor.stromverbrauch_wp_aussenteil_vortag: WP Außen
    sensor.stromverbrauch_wp_heizstab_vortag: WP Heizstab
    sensor.stromverbrauch_wp_innenteil_vortag: WP Innen
