global_vars:
  module: global_vars
  class: global_vars
  # permanent recorder db
  db_host: "a0d7b954-influxdb"
  db_port: 8086
  db_user: "appdaemon"
  db_name: "homeassistant_permanent"
  db_passwd: !secret permanent_db_passwd
  db_field_float: state_float
  # namespace
  ad_namespace: "ad_namespace"
  # energy prices and consumption
  input_number_entity_price_per_kwh: input_number.strompreis
  input_number_entity_compensation_per_kwh: input_number.pv_einspeiseverguetung
