gz_zigbee_button:
  module: gz_zigbee_button
  class: gz_zigbee_button
  sensor_entity: sensor.aqara_button_gaeste_click
  sleep_mode_switch_entity: switch.gaste_schlafen
  light_entity: light.innr_rb_245_97884103_level_on_off
