heating_controller_foresight_ez:
  module: heating_controller_foresight
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.temp_esszimmer_pm
  db_field: state_float
  number_of_derivatives_for_average: 5
  multiplicator: 8
  limit_max: 1.7
  limit_min: -1.7
  ga_setpoint_shift: "10/0/21"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_ez
  log_measurement: shift_heating_setpoint_ez
heating_controller_foresight_ku:
  module: heating_controller_foresight
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.temp_esszimmer_pm
  db_field: state_float
  number_of_derivatives_for_average: 5
  multiplicator: 8
  limit_max: 1.7
  limit_min: -1.7
  ga_setpoint_shift: "10/0/1"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_ez
  log_measurement: shift_heating_setpoint_ku
heating_controller_foresight_wz:
  module: heating_controller_foresight
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.temp_esszimmer_pm
  db_field: state_float
  number_of_derivatives_for_average: 5
  multiplicator: 8
  limit_max: 1.7
  limit_min: -1.7
  ga_setpoint_shift: "10/0/41"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_ez
  log_measurement: shift_heating_setpoint_wz
heating_controller_foresight_sz:
  module: heating_controller_foresight
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.temp_schlafzimmer_pm
  db_field: state_float
  number_of_derivatives_for_average: 5
  multiplicator: 7
  limit_max: 1.5
  limit_min: -1.5
  ga_setpoint_shift: "10/0/61"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_sz
  log_measurement: shift_heating_setpoint_sz
heating_controller_foresight_bad_eg:
  module: heating_controller_foresight
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.temp_bad_eg_pm
  db_field: state_float
  number_of_derivatives_for_average: 3
  minutes_for_evaltuation: [60, 90, 120, 150, 180]
  multiplicator: 6
  limit_max: 1
  limit_min: -1
  ga_setpoint_shift: "10/0/81"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_bad_eg
  log_measurement: shift_heating_setpoint_bad_eg
heating_controller_foresight_wf_wc:
  module: heating_controller_foresight_beta
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.onewire_15_estrich_wc_1
  db_field: state_float
  number_of_derivatives_for_average: 2
  multiplicator: 2
  limit_max: 1
  limit_min: -1
  ga_setpoint_shift: "10/0/101"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_wf_wc
  log_measurement: shift_heating_setpoint_wf_wc
heating_controller_foresight_le:
  module: heating_controller_foresight
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.temp_le_pm
  db_field: state_float
  number_of_derivatives_for_average: 5
  multiplicator: 7
  limit_max: 1.5
  limit_min: -1.5
  ga_setpoint_shift: "10/0/161"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_le
  log_measurement: shift_heating_setpoint_le
heating_controller_foresight_la:
  module: heating_controller_foresight
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.temp_la_pm
  db_field: state_float
  number_of_derivatives_for_average: 5
  multiplicator: 7
  limit_max: 1.5
  limit_min: -1.5
  ga_setpoint_shift: "10/0/121"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_la
  log_measurement: shift_heating_setpoint_la
heating_controller_foresight_nz:
  module: heating_controller_foresight
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.temp_nahzimmer_pm
  db_field: state_float
  number_of_derivatives_for_average: 5
  multiplicator: 7
  limit_max: 1.5
  limit_min: -1.5
  ga_setpoint_shift: "10/0/141"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_nz
  log_measurement: shift_heating_setpoint_nz
heating_controller_foresight_gz:
  module: heating_controller_foresight
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.temp_gastezimmer_pm
  db_field: state_float
  number_of_derivatives_for_average: 5
  multiplicator: 7
  limit_max: 1.5
  limit_min: -1.5
  ga_setpoint_shift: "10/0/181"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_gz
  log_measurement: shift_heating_setpoint_gz
heating_controller_foresight_flur_og:
  module: heating_controller_foresight
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.temp_flur_og_pm
  db_field: state_float
  number_of_derivatives_for_average: 5
  multiplicator: 7
  limit_max: 1.5
  limit_min: -1.5
  ga_setpoint_shift: "10/0/201"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_flur_og
  log_measurement: shift_heating_setpoint_flur_og
heating_controller_foresight_bad_og:
  module: heating_controller_foresight
  class: heating_controller_foresight
  db_passwd: !secret permanent_db_passwd
  db_measurement: sensor.temp_bad_og_pm
  db_field: state_float
  number_of_derivatives_for_average: 5
  multiplicator: 7
  limit_max: 1.5
  limit_min: -1.5
  ga_setpoint_shift: "10/0/221"
  shift_value: 0.1
  mode: active
  on_off_switch: input_boolean.korrektur_heizung_bad_og
  log_measurement: shift_heating_setpoint_bad_og
