humidity_manager_partyraum:
  module: humidity_manager
  class: humidity_manager
  sensor_humidity_inside: sensor.luftfeuchtigkeit_partyraum
  sensor_temp_inside: sensor.temp_partyraum
  sensor_humidity_outside: sensor.humidity_outside_internet
  sensor_temp_outside: sensor.temp_outside_internet
  max_humidity_inside: 65
  notification_entity: sensor.humidity_manager_partyraum
  notification_friendly_name: "Luft Partyraum"
humidity_manager_werkelraum:
  module: humidity_manager
  class: humidity_manager
  sensor_humidity_inside: sensor.luftfeuchtigkeit_werkelraum
  sensor_temp_inside: sensor.temp_werkelraum
  sensor_humidity_outside: sensor.humidity_outside_internet
  sensor_temp_outside: sensor.temp_outside_internet
  max_humidity_inside: 65
  notification_entity: sensor.humidity_manager_werkelraum
  notification_friendly_name: "Luft Werkelraum"
