permanent_recorder:
  module: permanent_recorder
  class: permanent_recorder
  db_passwd: !secret permanent_db_passwd
  plugin: NONE
  state_boolean:
    - binary_sensor.anwesenheit_bildschirm
    - binary_sensor.anwesenheit_haus
    - binary_sensor.backofen_ist_an
    - binary_sensor.eimer_hebeanlage_voll
    - binary_sensor.gaeste_nur_abends
    - binary_sensor.heizungsanforderung_eg
    - binary_sensor.heizungsanforderung_og
    - binary_sensor.hst_offen
    - binary_sensor.jemand_schlaeft
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_83155c04_on_off
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
    - binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone
    - binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy
    - binary_sensor.mixi_ist_an
    - binary_sensor.nachtmodus_wohnbereich_jalousie
    - binary_sensor.nachtmodus_wohnbereich_licht
    - binary_sensor.o_fl_logik_bewegung_rund_um_treppe
    - binary_sensor.ping_fritzbox
    - binary_sensor.ping_odroidxu4
    - binary_sensor.pm_a_eg
    - binary_sensor.pm_a_cp
    - binary_sensor.pm_a_ar
    - binary_sensor.pm_e_ba
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_fl_flur
    - binary_sensor.pm_e_fl_treppe_og
    - binary_sensor.pm_e_fl_windfang
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_sz_bett
    - binary_sensor.pm_e_sz_gang
    - binary_sensor.pm_e_wc
    - binary_sensor.pm_e_wf_flur
    - binary_sensor.pm_e_wf_garderobe
    - binary_sensor.pm_e_wf_haustur
    - binary_sensor.pm_e_wz_couch_links
    - binary_sensor.pm_e_wz_couch_rechts
    - binary_sensor.pm_e_wz_durchgang
    - binary_sensor.pm_k_fl
    - binary_sensor.pm_k_te
    - binary_sensor.pm_k_timer_magnetsensor_vorratsraum
    - binary_sensor.pm_ktr_flur
    - binary_sensor.pm_ktr_treppe
    - binary_sensor.pm_o_ba
    - binary_sensor.pm_o_fl_flur
    - binary_sensor.pm_o_fl_treppe
    - binary_sensor.pm_o_gz
    - binary_sensor.pm_o_ko_la_raum
    - binary_sensor.pm_o_ko_la_tuer
    - binary_sensor.pm_o_kw_le_raum
    - binary_sensor.pm_o_kw_le_tuer
    - binary_sensor.pm_o_nz
    - binary_sensor.regenalarm
    - binary_sensor.remote_ui
    - binary_sensor.schlafen_oder_aufwachphase_la
    - binary_sensor.schlafen_oder_aufwachphase_le
    - binary_sensor.schlafen_oder_aufwachphase_majo
    - binary_sensor.schlafen_oder_licht_noch_aus_lassen_majo
    - binary_sensor.sicherung_keller_sd_rausgeflogen
    - binary_sensor.status_24v_led_aktor_1
    - binary_sensor.status_24v_led_aktor_2
    - binary_sensor.status_24v_led_aktor_3
    - binary_sensor.status_24v_led_aktor_4
    - binary_sensor.status_24v_led_aktor_5
    - binary_sensor.status_24v_led_aktor_6
    - binary_sensor.status_24v_led_aktor_7
    - binary_sensor.status_waermegewinnung
    - binary_sensor.status_waermeschutz
    - binary_sensor.storung_heizaktor_eg
    - binary_sensor.storung_heizaktor_og
    - binary_sensor.tag_nacht_wetterstation
    - binary_sensor.temperaturalarm_wetterstation
    - binary_sensor.trockner_ist_an
    - binary_sensor.trockner_ist_geleert
    - binary_sensor.tv_ist_an
    - binary_sensor.tv_pizza_abend
    - binary_sensor.uberstromalarm_led_aktor_1
    - binary_sensor.uberstromalarm_led_aktor_2
    - binary_sensor.uberstromalarm_led_aktor_3
    - binary_sensor.uberstromalarm_led_aktor_4
    - binary_sensor.uberstromalarm_led_aktor_5
    - binary_sensor.uberstromalarm_led_aktor_6
    - binary_sensor.uberstromalarm_led_aktor_7
    - binary_sensor.ubertemperaturalarm_led_aktor_1
    - binary_sensor.ubertemperaturalarm_led_aktor_2
    - binary_sensor.ubertemperaturalarm_led_aktor_3
    - binary_sensor.ubertemperaturalarm_led_aktor_4
    - binary_sensor.ubertemperaturalarm_led_aktor_5
    - binary_sensor.ubertemperaturalarm_led_aktor_6
    - binary_sensor.ubertemperaturalarm_led_aktor_7
    - binary_sensor.waschmaschine_ist_an
    - binary_sensor.wasser_boden_bei_hebeanlage
    - binary_sensor.wasser_unter_spule
    - binary_sensor.wetterstation_status_gps_signal
    - binary_sensor.windalarm_1
    - binary_sensor.windalarm_2
    - binary_sensor.windalarm_3
    - switch.backofen
    - switch.bad_og_nachtmodus
    - switch.bleib_so_la_licht
    - switch.bleib_so_le_licht
    - switch.bleib_so_wz_licht
    - switch.gaste_schlafen
    - switch.gefrierschrank
    - switch.innr_sp_120_luftentfeuchter_waschkuche_on_off
    - switch.innr_sp_120_test_on_off
    - switch.innr_sp_220_repeater_garderobenschrank_on_off
    - switch.innr_sp_220_repeater_waschkuche_on_off
    - switch.kinder_schon_wach
    - switch.knutschen
    - switch.kuhlschrank_keller
    - switch.kuhlschrank_kuche
    - switch.la_schlaft
    - switch.le_schlaft
    - switch.led_netzteil_8
    - switch.luftungsanlage
    - switch.lumi_lumi_plug_mmeu01_on_off
    - switch.majo_schlafen
    - switch.mixi
    - switch.spulmaschine
    - switch.trockner
    - switch.tv
    - switch.waschmaschine
    - switch.wz_steckdose
    - sensor.status_amtzell
    - sensor.status_aral_mecka
    - sensor.status_hannober
    - sensor.status_jet_fn
    - sensor.status_marktkauf
    - sensor.status_schindele
  heating_target_temperature:
    - climate.bad_eg
    - climate.bad_og
    - climate.esszimmer
    - climate.flur_og
    - climate.gastezimmer
    - climate.kuche
    - climate.la
    - climate.le
    - climate.nahzimmer
    - climate.schlafzimmer
    - climate.windfang_wc
    - climate.wohnzimmer
  cover:
    - cover.jalousie_bad_og
    - cover.jalousie_gastezimmer
    - cover.jalousie_hst
    - cover.jalousie_kuche
    - cover.jalousie_la_bodentiefes
    - cover.jalousie_la_lichtband
    - cover.jalousie_le_bodentiefes
    - cover.jalousie_le_lichtband
    - cover.jalousie_nahzimmer
    - cover.jalousie_schlafzimmer
    - cover.jalousie_wz_bodentiefes
    - cover.jalousie_wz_couch
  state_float:
    - sensor.anteil_el_leistung_*
    - sensor.bme280*
    - sensor.bosch_outdoor_temperature
    - sensor.diesel_*
    - sensor.e10_*
    - sensor.e5_*
    - sensor.el_leistung_*
    - sensor.helligkeit_*
    - sensor.humidity_outside_internet
    - sensor.luftdruck_kuche_aqara
    - sensor.luftfeuchtigkeit_*
    - sensor.lumi_lumi_remote_b286acn01_power
    - sensor.lumi_lumi_sensor_magnet_aq2_83155c04_power
    - sensor.lumi_lumi_sensor_magnet_aq2_power
    - sensor.lumi_lumi_sensor_motion_aq2_illuminance
    - sensor.lumi_lumi_sensor_motion_aq2_power
    - sensor.lumi_lumi_weather_57dc3d03_humidity
    - sensor.lumi_lumi_weather_57dc3d03_power
    - sensor.lumi_lumi_weather_57dc3d03_temperature
    - sensor.lumi_lumi_weather_humidity
    - sensor.lumi_lumi_weather_power
    - sensor.lumi_lumi_weather_temperature
    - sensor.onewire_*
    - sensor.shellydimmer_d472fe_power
    - sensor.shellyplug_s_169d16_power
    - sensor.sollwert_heizung_*
    - sensor.sonoff_pow_*
    - sensor.stellwert_heizung_*
    - input_number.strompreis
    - sensor.strompreis_aktuell_effektiv_euro
    - sensor.strompreis_aktuell_abrechnung_euro
    - sensor.stromzaehler_netzbezug
    - sensor.temp_*
    - sensor.windgeschwindigkeit_wetterstation
    - sensor.windgeschwindigkeit_wetterstation_kmh
  state_string:
    - sensor.diagnose_heizkreis_bad_eg
    - sensor.diagnose_heizkreis_bad_og
    - sensor.diagnose_heizkreis_esszimmer
    - sensor.diagnose_heizkreis_flur_og
    - sensor.diagnose_heizkreis_gastezimmer
    - sensor.diagnose_heizkreis_kuche
    - sensor.diagnose_heizkreis_la
    - sensor.diagnose_heizkreis_le
    - sensor.diagnose_heizkreis_nahzimmer
    - sensor.diagnose_heizkreis_schlafzimmer
    - sensor.diagnose_heizkreis_wc_wf
    - sensor.diagnose_heizkreis_wohnzimmer
