permanent_recorder:
  module: permanent_recorder
  class: permanent_recorder
  db_passwd: !secret permanent_db_passwd
  plugin: NONE
  light_brightness:
    - light.abstellraum_carport
    - light.arbeitsplatte
    - light.bar_beleuchtung
    - light.bettbeleuchtung
    - light.bodenlicht_eingang
    - light.brettlicht_windfang
    - light.flur_keller
    - light.gastezimmer
    - light.lagerraum
    - light.led_auf_spiegelschrank_bad_eg
    - light.led_auf_spiegelschrank_bad_og
    - light.led_streifen_carport
    - light.nahtisch_decke
    - light.panels_bad_eg
    - light.panels_bad_og
    - light.panels_bar
    - light.panels_esszimmer
    - light.panels_flur_eg
    - light.panels_flur_og
    - light.panels_kuche
    - light.panels_la
    - light.panels_le
    - light.panels_schlafzimmer
    - light.panels_treppe_og
    - light.panels_wc
    - light.panels_windfang
    - light.panels_wohnzimmer
    - light.regal_bad_eg
    - light.schrankbeleuchtung_esszimmer
    - light.schrankbeleuchtung_wohnzimmer
    - light.schreibtisch_decke
    - light.sockelbeleuchtung
    - light.spiegel_bad_eg
    - light.spiegel_bad_og
    - light.spiegel_wc
    - light.spots_carport
    - light.stehlampe_la
    - light.stehlampe_le
    - light.stufenbeleuchtung_treppe
    - light.technikraum
    - light.vorratsraum
    - light.wandleuchten_esszimmer_gemutlich
    - light.wandleuchten_esszimmer_hell
    - light.wandwurfel_la
    - light.wandwurfel_le
    - light.wandwurfel_suden
    - light.wandwurfel_westen
    - light.werkelraum
    - light.innr_e14_tw_kugellampe_schlafzimmer_level_light_color_on_off
    - light.innr_e14_tw_stehlampe_lea_level_light_color_on_off
    - light.innr_e14_ww_decke_gastezimmer_level_on_off
    - light.innr_e14_ww_stehlampe_lara_level_on_off
    - light.innr_e27_color_terrasse_ecke_gross_level_light_color_on_off
    - light.innr_rb_285_c_55f50405_level_light_color_on_off
    - light.innr_rb_285_c_7cc30105_level_light_color_on_off
    - light.shellydimmer_d472fe_light_0
  state_boolean:
    - binary_sensor.anwesenheit_bildschirm
    - binary_sensor.anwesenheit_haus
    - binary_sensor.backofen_ist_an
    - binary_sensor.eimer_hebeanlage_voll
    - binary_sensor.gaeste_nur_abends
    - binary_sensor.heizungsanforderung_eg
    - binary_sensor.heizungsanforderung_og
    - binary_sensor.hst_offen
    - binary_sensor.jemand_schlaeft
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_83155c04_on_off
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
    - binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone
    - binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy
    - binary_sensor.mixi_ist_an
    - binary_sensor.nachtmodus_wohnbereich_jalousie
    - binary_sensor.nachtmodus_wohnbereich_licht
    - binary_sensor.o_fl_logik_bewegung_rund_um_treppe
    - binary_sensor.ping_fritzbox
    - binary_sensor.ping_odroidxu4
    - binary_sensor.pm_a_eg
    - binary_sensor.pm_a_cp
    - binary_sensor.pm_a_ar
    - binary_sensor.pm_e_ba
    - binary_sensor.pm_e_ez_bar_kuche
    - binary_sensor.pm_e_ez_esstisch
    - binary_sensor.pm_e_fl_flur
    - binary_sensor.pm_e_fl_treppe_og
    - binary_sensor.pm_e_fl_windfang
    - binary_sensor.pm_e_ku_bar_ez
    - binary_sensor.pm_e_ku_kuche
    - binary_sensor.pm_e_sz_bett
    - binary_sensor.pm_e_sz_gang
    - binary_sensor.pm_e_wc
    - binary_sensor.pm_e_wf_flur
    - binary_sensor.pm_e_wf_garderobe
    - binary_sensor.pm_e_wf_haustur
    - binary_sensor.pm_e_wz_couch_links
    - binary_sensor.pm_e_wz_couch_rechts
    - binary_sensor.pm_e_wz_durchgang
    - binary_sensor.pm_k_fl
    - binary_sensor.pm_k_te
    - binary_sensor.pm_k_timer_magnetsensor_vorratsraum
    - binary_sensor.pm_ktr_flur
    - binary_sensor.pm_ktr_treppe
    - binary_sensor.pm_o_ba
    - binary_sensor.pm_o_fl_flur
    - binary_sensor.pm_o_fl_treppe
    - binary_sensor.pm_o_gz
    - binary_sensor.pm_o_ko_la_raum
    - binary_sensor.pm_o_ko_la_tuer
    - binary_sensor.pm_o_kw_le_raum
    - binary_sensor.pm_o_kw_le_tuer
    - binary_sensor.pm_o_nz
    - binary_sensor.regenalarm
    - binary_sensor.remote_ui
    - binary_sensor.schlafen_oder_aufwachphase_la
    - binary_sensor.schlafen_oder_aufwachphase_le
    - binary_sensor.schlafen_oder_aufwachphase_majo
    - binary_sensor.schlafen_oder_licht_noch_aus_lassen_majo
    - binary_sensor.sicherung_keller_sd_rausgeflogen
    - binary_sensor.status_24v_led_aktor_1
    - binary_sensor.status_24v_led_aktor_2
    - binary_sensor.status_24v_led_aktor_3
    - binary_sensor.status_24v_led_aktor_4
    - binary_sensor.status_24v_led_aktor_5
    - binary_sensor.status_24v_led_aktor_6
    - binary_sensor.status_24v_led_aktor_7
    - binary_sensor.status_waermegewinnung
    - binary_sensor.status_waermeschutz
    - binary_sensor.storung_heizaktor_eg
    - binary_sensor.storung_heizaktor_og
    - binary_sensor.tag_nacht_wetterstation
    - binary_sensor.temperaturalarm_wetterstation
    - binary_sensor.trockner_ist_an
    - binary_sensor.trockner_ist_geleert
    - binary_sensor.tv_ist_an
    - binary_sensor.tv_pizza_abend
    - binary_sensor.uberstromalarm_led_aktor_1
    - binary_sensor.uberstromalarm_led_aktor_2
    - binary_sensor.uberstromalarm_led_aktor_3
    - binary_sensor.uberstromalarm_led_aktor_4
    - binary_sensor.uberstromalarm_led_aktor_5
    - binary_sensor.uberstromalarm_led_aktor_6
    - binary_sensor.uberstromalarm_led_aktor_7
    - binary_sensor.ubertemperaturalarm_led_aktor_1
    - binary_sensor.ubertemperaturalarm_led_aktor_2
    - binary_sensor.ubertemperaturalarm_led_aktor_3
    - binary_sensor.ubertemperaturalarm_led_aktor_4
    - binary_sensor.ubertemperaturalarm_led_aktor_5
    - binary_sensor.ubertemperaturalarm_led_aktor_6
    - binary_sensor.ubertemperaturalarm_led_aktor_7
    - binary_sensor.waschmaschine_ist_an
    - binary_sensor.wasser_boden_bei_hebeanlage
    - binary_sensor.wasser_unter_spule
    - binary_sensor.wetterstation_status_gps_signal
    - binary_sensor.windalarm_1
    - binary_sensor.windalarm_2
    - binary_sensor.windalarm_3
    - switch.backofen
    - switch.bad_og_nachtmodus
    - switch.bleib_so_la_licht
    - switch.bleib_so_le_licht
    - switch.bleib_so_wz_licht
    - switch.gaste_schlafen
    - switch.gefrierschrank
    - switch.innr_sp_120_luftentfeuchter_waschkuche_on_off
    - switch.innr_sp_120_test_on_off
    - switch.innr_sp_220_repeater_garderobenschrank_on_off
    - switch.innr_sp_220_repeater_waschkuche_on_off
    - switch.kinder_schon_wach
    - switch.knutschen
    - switch.kuhlschrank_keller
    - switch.kuhlschrank_kuche
    - switch.la_schlaft
    - switch.le_schlaft
    - switch.led_netzteil_8
    - switch.luftungsanlage
    - switch.lumi_lumi_plug_mmeu01_on_off
    - switch.majo_schlafen
    - switch.mixi
    - switch.spulmaschine
    - switch.trockner
    - switch.tv
    - switch.waschmaschine
    - switch.wz_steckdose
    - sensor.status_amtzell
    - sensor.status_aral_mecka
    - sensor.status_hannober
    - sensor.status_jet_fn
    - sensor.status_marktkauf
    - sensor.status_schindele
  heating_target_temperature:
    - climate.bad_eg
    - climate.bad_og
    - climate.esszimmer
    - climate.flur_og
    - climate.gastezimmer
    - climate.kuche
    - climate.la
    - climate.le
    - climate.nahzimmer
    - climate.schlafzimmer
    - climate.windfang_wc
    - climate.wohnzimmer
  cover:
    - cover.jalousie_bad_og
    - cover.jalousie_gastezimmer
    - cover.jalousie_hst
    - cover.jalousie_kuche
    - cover.jalousie_la_bodentiefes
    - cover.jalousie_la_lichtband
    - cover.jalousie_le_bodentiefes
    - cover.jalousie_le_lichtband
    - cover.jalousie_nahzimmer
    - cover.jalousie_schlafzimmer
    - cover.jalousie_wz_bodentiefes
    - cover.jalousie_wz_couch
  state_float:
    - sensor.dht22_waschkueche_humidity
    - sensor.dht22_waschkueche_temperature
    - sensor.diesel_amtzell
    - sensor.diesel_aral_mecka
    - sensor.diesel_hannober
    - sensor.diesel_jet_fn
    - sensor.diesel_marktkauf
    - sensor.diesel_pinoil_tt
    - sensor.diesel_schindele
    - sensor.e10_amtzell
    - sensor.e10_aral_mecka
    - sensor.e10_hannober
    - sensor.e10_jet_fn
    - sensor.e10_marktkauf
    - sensor.e10_pinoil_tt
    - sensor.e10_schindele
    - sensor.e5_amtzell
    - sensor.e5_aral_mecka
    - sensor.e5_hannober
    - sensor.e5_jet_fn
    - sensor.e5_marktkauf
    - sensor.e5_pinoil_tt
    - sensor.e5_schindele
    - sensor.el_leistung_backofen
    - sensor.el_leistung_gefrierschrank
    - sensor.el_leistung_kochfeld
    - sensor.el_leistung_kuhlschrank_keller
    - sensor.el_leistung_kuhlschrank_kuche
    - sensor.el_leistung_luftungsanlage
    - sensor.el_leistung_mixi
    - sensor.el_leistung_spulmaschine
    - sensor.el_leistung_trockner
    - sensor.el_leistung_tv
    - sensor.el_leistung_waschmaschine
    - sensor.el_leistung_wp_aussenteil
    - sensor.el_leistung_wp_heizstab
    - sensor.el_leistung_wp_innenteil
    - sensor.helligkeit_bad_eg_pm
    - sensor.helligkeit_bad_og_pm
    - sensor.helligkeit_esszimmer_pm
    - sensor.helligkeit_flur_eg_pm
    - sensor.helligkeit_flur_og_pm
    - sensor.helligkeit_gastezimmer_pm
    - sensor.helligkeit_kuche_pm
    - sensor.helligkeit_la_pm
    - sensor.helligkeit_le_pm
    - sensor.helligkeit_nahzimmer_pm
    - sensor.helligkeit_schlafzimmer_pm
    - sensor.helligkeit_wc_pm
    - sensor.helligkeit_wetterstation
    - sensor.helligkeit_windfang_pm
    - sensor.helligkeit_wohnzimmer_pm
    - sensor.innr_sp_120_luftentfeuchter_waschkuche_electrical_measurement
    - sensor.innr_sp_120_test_electrical_measurement
    - sensor.luftdruck_kuche_aqara
    - sensor.luftfeuchtigkeit_kuche_aqara
    - sensor.lumi_lumi_remote_b286acn01_power
    - sensor.lumi_lumi_sensor_magnet_aq2_83155c04_power
    - sensor.lumi_lumi_sensor_magnet_aq2_power
    - sensor.lumi_lumi_sensor_motion_aq2_illuminance
    - sensor.lumi_lumi_sensor_motion_aq2_power
    - sensor.lumi_lumi_weather_57dc3d03_humidity
    - sensor.lumi_lumi_weather_57dc3d03_power
    - sensor.lumi_lumi_weather_57dc3d03_temperature
    - sensor.lumi_lumi_weather_humidity
    - sensor.lumi_lumi_weather_power
    - sensor.lumi_lumi_weather_temperature
    - sensor.onewire_07_estrich_kueche
    - sensor.onewire_14_estrich_wohnzimmer
    - sensor.onewire_15_estrich_wc_1
    - sensor.onewire_16_estrich_esszimmer
    - sensor.onewire_20_estrich_bad_eg
    - sensor.onewire_21_estrich_wc_2
    - sensor.onewire_25_estrich_schlafzimmer
    - sensor.onewire_serverschrank
    - sensor.shellydimmer_d472fe_energy
    - sensor.sollwert_heizung_bad_eg
    - sensor.sollwert_heizung_bad_og
    - sensor.sollwert_heizung_esszimmer
    - sensor.sollwert_heizung_flur_og
    - sensor.sollwert_heizung_gastezimmer
    - sensor.sollwert_heizung_kuche
    - sensor.sollwert_heizung_la
    - sensor.sollwert_heizung_le
    - sensor.sollwert_heizung_nahzimmer
    - sensor.sollwert_heizung_schlafzimmer
    - sensor.sollwert_heizung_windfang_wc
    - sensor.sollwert_heizung_wohnzimmer
    - sensor.stellwert_heizung_bad_eg
    - sensor.stellwert_heizung_bad_og
    - sensor.stellwert_heizung_esszimmer
    - sensor.stellwert_heizung_flur_og
    - sensor.stellwert_heizung_gastezimmer
    - sensor.stellwert_heizung_kuche
    - sensor.stellwert_heizung_la
    - sensor.stellwert_heizung_le
    - sensor.stellwert_heizung_nahzimmer
    - sensor.stellwert_heizung_schlafzimmer
    - sensor.stellwert_heizung_windfang_wc
    - sensor.stellwert_heizung_wohnzimmer
    - sensor.stromzahler_backofen
    - sensor.stromzahler_gefrierschrank
    - sensor.stromzahler_kochfeld
    - sensor.stromzahler_kochfeld_rohdaten
    - sensor.stromzahler_kuhlschrank_keller
    - sensor.stromzahler_kuhlschrank_kuche
    - sensor.stromzahler_luftungsanlage
    - sensor.stromzahler_mixi
    - sensor.stromzahler_spulmaschine
    - sensor.stromzahler_trockner
    - sensor.stromzahler_tv
    - sensor.stromzahler_waschmaschine
    - sensor.stromzahler_wp_aussenteil
    - sensor.stromzahler_wp_aussenteil_rohdaten
    - sensor.stromzahler_wp_heizstab
    - sensor.stromzahler_wp_heizstab_rohdaten
    - sensor.stromzahler_wp_innenteil
    - sensor.stromzahler_wp_innenteil_rohdaten
    - sensor.temp_bad_eg_pm
    - sensor.temp_bad_eg_taster
    - sensor.temp_bad_og_pm
    - sensor.temp_bad_og_taster
    - sensor.temp_esszimmer_pm
    - sensor.temp_esszimmer_taster
    - sensor.temp_flur_eg_pm
    - sensor.temp_flur_og_pm
    - sensor.temp_gastezimmer_pm
    - sensor.temp_gastezimmer_taster
    - sensor.temp_kuche_aqara
    - sensor.temp_kuche_pm
    - sensor.temp_la_pm
    - sensor.temp_la_taster
    - sensor.temp_le_pm
    - sensor.temp_le_taster
    - sensor.temp_nahzimmer_pm
    - sensor.temp_schlafzimmer_pm
    - sensor.temp_schlafzimmer_taster
    - sensor.temp_wc_pm
    - sensor.temp_wetterstation
    - sensor.temp_windfang_pm
    - sensor.temp_wohnzimmer_pm
    - sensor.windgeschwindigkeit_wetterstation
    - sensor.windgeschwindigkeit_wetterstation_kmh
  state_string:
    - sensor.diagnose_heizkreis_bad_eg
    - sensor.diagnose_heizkreis_bad_og
    - sensor.diagnose_heizkreis_esszimmer
    - sensor.diagnose_heizkreis_flur_og
    - sensor.diagnose_heizkreis_gastezimmer
    - sensor.diagnose_heizkreis_kuche
    - sensor.diagnose_heizkreis_la
    - sensor.diagnose_heizkreis_le
    - sensor.diagnose_heizkreis_nahzimmer
    - sensor.diagnose_heizkreis_schlafzimmer
    - sensor.diagnose_heizkreis_wc_wf
    - sensor.diagnose_heizkreis_wohnzimmer
