pv:
  module: pv
  class: pv
  dependencies: global_vars
  # daily counter values => daily production
  # produced
  sensor_name_counter_pv_produced_midnight: "sensor.counter_pv_produced_midnight"
  counter_entity_pv_produced: "sensor.stromzaehler_pv_ac_gesamt"
  counter_entity_pv_produced_day: "sensor.pv_erzeugung_tag"
  # sold
  sensor_name_counter_pv_sold_midnight: "sensor.counter_pv_sold_midnight"
  counter_entity_pv_sold: "sensor.stromzaehler_netzeinspeisung"
  counter_entity_pv_sold_day: "sensor.pv_netzeinspeisung_tag"
  # own consumption
  counter_entity_pv_used_day: "sensor.pv_eigenverbrauch_tag"
  # saved money
  entity_pv_saved_money_by_selling_day: "sensor.pv_geldertrag_durch_einspeisung_tag"
  entity_pv_saved_money_by_selling_yesterday: "sensor.pv_geldertrag_durch_einspeisung_gestern"
  entity_pv_saved_money_by_consuming_day: "sensor.pv_geldertrag_durch_eigenverbrauch_tag"
  entity_pv_saved_money_by_consuming_yesterday: "sensor.pv_geldertrag_durch_eigenverbrauch_gestern"
  entity_pv_saved_money_total_day: "sensor.pv_geldertrag_gesamt_tag"
  entity_pv_saved_money_total_yesterday: "sensor.pv_geldertrag_gesamt_gestern"
  # water heater
  water_temp_heating_will_start_on_eco: 42
  water_temp_heating_will_start_on_hot: 46
  water_temp_heating_will_not_start_on_hot: 49
  temp_loss_per_hour: 0.3
  pv_boost_minimum_minutes: 59
  entity_water_temp_current: "sensor.water_heater_current_temp"
  minimum_pv_power_for_increasing_water_temp: 1600
  entity_pv_power: sensor.statistics_el_leistung_netz_letzte_3_min
  entity_water_heater: "water_heater.dhw1"
  program_eco: "eco"
  program_hot: "on"
