statistics_helper_pv_leistung_letzte_3_min:
  module: statistics_helper
  class: statistics_helper
  input_entity: sensor.el_leistung_pv_ac
  output_entity: sensor.statistics_el_leistung_pv_letzte_3_min
  number_of_values: 6
  time_interval_sec: 30
  startup_delay: 10
  function_type: "mean"
  trigger_type: "fixed_timestep"
statistics_helper_pv_einspeisung_letzte_3_min:
  module: statistics_helper
  class: statistics_helper
  input_entity: sensor.el_leistung_einspeisung
  output_entity: sensor.statistics_el_leistung_einspeisung_letzte_3_min
  number_of_values: 6
  time_interval_sec: 30
  startup_delay: 11
  function_type: "mean"
  trigger_type: "fixed_timestep"
statistics_helper_pv_einspeisung_letzte_10_min:
  module: statistics_helper
  class: statistics_helper
  input_entity: sensor.el_leistung_einspeisung
  output_entity: sensor.statistics_el_leistung_einspeisung_letzte_10_min
  number_of_values: 20
  time_interval_sec: 30
  startup_delay: 12
  function_type: "mean"
  trigger_type: "fixed_timestep"
statistics_helper_strompreis_effektiv_letzte_3_min:
  module: statistics_helper
  class: statistics_helper
  input_entity: sensor.strompreis_aktuell_effektiv_euro
  output_entity: sensor.strompreis_effektiv_letzte_3_minuten
  number_of_values: 6
  time_interval_sec: 30
  startup_delay: 13
  function_type: "mean"
  trigger_type: "fixed_timestep"
statistics_helper_leistung_netz_letzte_3_min:
  module: statistics_helper
  class: statistics_helper
  input_entity: sensor.el_leistung_netz
  output_entity: sensor.statistics_el_leistung_netz_letzte_3_min
  number_of_values: 6
  time_interval_sec: 30
  startup_delay: 14
  function_type: "mean"
  trigger_type: "fixed_timestep"
statistics_helper_leistung_netz_letzte_10_min:
  module: statistics_helper
  class: statistics_helper
  input_entity: sensor.el_leistung_netz
  output_entity: sensor.statistics_el_leistung_netz_letzte_10_min
  number_of_values: 20
  time_interval_sec: 30
  startup_delay: 15
  function_type: "mean"
  trigger_type: "fixed_timestep"
