# strings to replace:
#
# friendly name: Licht EG EZ Panels
# id name: e_ez_panels
# light: light.panels_esszimmer

input_boolean:
  automation_switch_light_e_ez_panels:
    name: Auto Licht EG EZ Panels
    icon: mdi:auto-fix
  helper_light_auto_switched_e_ez_panels:
    name: Helper - Auto Switched - Licht EG EZ Panels
    initial: off
  helper_light_manually_switched_on_e_ez_panels:
    name: Helper - Man Switched on - Licht EG EZ Panels
    initial: off
  helper_light_manually_switched_off_e_ez_panels:
    name: Helper - Man Switched off - Licht EG EZ Panels
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_ez_panels
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','04:59',50],
            ['05:00','05:59',60],
            ['06:00','08:59',60],
            ['09:00','16:59',60],
            ['17:00','21:29',65],
            ['21:30','23:59',50] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_e_ez_panels
        unit_of_measurement: "%"
        state: >
          {% if is_state('input_boolean.gaeste_abends', 'on') %}
            {{ int(70) }}
          {% elif is_state('binary_sensor.nachtmodus_wohnbereich_licht', 'on') %}
            {{ int(10) }}
          {% else %}
            {{ states('sensor.helper_light_basic_brightness_e_ez_panels') }}
          {% endif %}
        attributes:
          special_brightness: >
            {{ [states('input_boolean.gaeste_abends'),states('binary_sensor.nachtmodus_wohnbereich_licht')] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_ez_panels
        unit_of_measurement: "lx"
        state: >
          {% set hours = 
            ['00:00','06:59',40],
            ['07:00','07:59',45],
            ['08:00','18:29',50],
            ['18:30','21:29',50],
            ['21:30','23:59',40] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_switching_off_entities_e_ez_panels
        unit_of_measurement: "number"
        state: >
          {% if states('binary_sensor.tv_abends_an') in ['unavailable', 'unknown', 'none']
             or states('input_boolean.arbeit_theke') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_ez') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_switching_off_entities_e_ez_panels') }}
          {% else %}
            {{ [states('binary_sensor.tv_abends_an'),states('input_boolean.arbeit_theke'),states('switch.luften_ez')] | select('equalto', 'on') | list | count }}
          {% endif %}
    binary_sensor:
      - name: helper_stay_as_you_are_e_ez_panels
        state: >
          {{ false }}
      - name: helper_light_trigger_e_ez_panels
        state: >
          {% if states('binary_sensor.pm_e_ez_bar_kuche') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_ez_esstisch') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_ku_bar_ez') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_ku_kuche') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_wz_durchgang') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_e_ez_panels') }}
          {% else %}
            {{ is_state('binary_sensor.pm_e_ez_bar_kuche', 'on')
               or is_state('binary_sensor.pm_e_ez_esstisch', 'on')
               or is_state('binary_sensor.pm_e_ku_bar_ez', 'on')
               or is_state('binary_sensor.pm_e_ku_kuche', 'on')
               or is_state('binary_sensor.pm_e_wz_durchgang', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_e_ez_panels
        state: >
          {% if states('binary_sensor.tv_abends_an') in ['unavailable', 'unknown', 'none']
             or states('input_boolean.arbeit_theke') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_ez') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_off_entities_e_ez_panels') }}
          {% else %}
            {{ is_state('binary_sensor.tv_abends_an', 'on')
              or is_state('input_boolean.arbeit_theke', 'on')
              or is_state('switch.luften_ez', 'on') }}
          {% endif %}
      - name: helper_light_keeping_on_entities_e_ez_panels
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_e_ez_panels
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_e_ez_panels
        state: >
          {% if states('sensor.helligkeit_esszimmer_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_dark_e_ez_panels') }}
          {% else %}
            {{ (states("sensor.helligkeit_esszimmer_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_ez_panels") | float(1)) }}
          {% endif %}
      - name: helper_light_is_too_bright_e_ez_panels
        state: >
          {% if states('sensor.helligkeit_esszimmer_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_bright_e_ez_panels') }}
          {% else %}
            {{ (states("sensor.helligkeit_esszimmer_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_ez_panels") | float(1) + 100 ) }}
          {% endif %}

automation:
  - alias: Licht EG EZ Panels
    id: 'auto_light_e_ez_panels'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.panels_esszimmer
        automation_switch: input_boolean.automation_switch_light_e_ez_panels
        helper_stay_as_you_are: binary_sensor.helper_stay_as_you_are_e_ez_panels
        trigger: binary_sensor.helper_light_trigger_e_ez_panels
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_ez_panels
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_ez_panels
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_ez_panels
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_ez_panels
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_ez_panels
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_ez_panels
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_ez_panels
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_ez_panels
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_ez_panels
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_ez_panels
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_ez_panels