# strings to replace:
#
# friendly name: Licht EG WZ Schränke
# id name: e_wz_schraenke
# light: light.schrankbeleuchtung_wohnzimmer

input_boolean:
  automation_switch_light_e_wz_schraenke:
    name: Auto Licht EG WZ Schränke
    icon: mdi:auto-fix
  helper_light_auto_switched_e_wz_schraenke:
    name: Helper - Auto Switched - Licht EG WZ Schränke
    initial: off
  helper_light_manually_switched_on_e_wz_schraenke:
    name: Helper - Man Switched on - Licht EG WZ Schränke
    initial: off
  helper_light_manually_switched_off_e_wz_schraenke:
    name: Helper - Man Switched off - Licht EG WZ Schränke
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_wz_schraenke
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','18:59',40],
            ['19:00','21:59',80],
            ['22:00','23:59',50] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_e_wz_schraenke
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_e_wz_schraenke') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_wz_schraenke
        unit_of_measurement: "lx"
        state: >
          {{ int(150) }}
      - name: helper_light_switching_off_entities_e_wz_schraenke
        unit_of_measurement: "number"
        state: >
          {{ [] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_e_wz_schraenke
        state: >
          {% if states('binary_sensor.pm_e_wz_couch_links') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_wz_couch_rechts') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_wz_durchgang') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_e_wz_schraenke') }}
          {% else %}
            {{ is_state('binary_sensor.pm_e_wz_couch_links', 'on')
               or is_state('binary_sensor.pm_e_wz_couch_rechts', 'on')
               or is_state('binary_sensor.pm_e_wz_durchgang', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_e_wz_schraenke
        state: >
          {% if states('switch.bleib_so_wz_licht') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_off_entities_e_wz_schraenke') }}
          {% else %}
            {{ is_state('switch.bleib_so_wz_licht', 'on') }}
          {% endif %}
      - name: helper_light_keeping_on_entities_e_wz_schraenke
        state: >
          {% if states('switch.bleib_so_wz_licht') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_on_entities_e_wz_schraenke') }}
          {% else %}
            {{ is_state('switch.bleib_so_wz_licht', 'on') }}
          {% endif %}
      - name: helper_light_keeping_fix_entities_e_wz_schraenke
        state: >
          {% if states('binary_sensor.tv_pizza_abend') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.tv_abend_ohne_pizza') in ['unavailable', 'unknown', 'none']
             or states('input_boolean.gaeste_abends') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_fix_entities_e_wz_schraenke') }}
          {% else %}
            {{ is_state('binary_sensor.tv_pizza_abend', 'on')
              or is_state('binary_sensor.tv_abend_ohne_pizza', 'on')
              or is_state('input_boolean.gaeste_abends', 'on') }}
          {% endif %}
        attributes:
          brightness: >
            {% if states('binary_sensor.tv_pizza_abend') in ['unavailable', 'unknown', 'none']
              or states('binary_sensor.tv_abend_ohne_pizza') in ['unavailable', 'unknown', 'none'] %}
              {{ state_attr('binary_sensor.helper_light_keeping_fix_entities_e_wz_schraenke', 'brightness') }}
            {% else %}
              {% if is_state('input_boolean.gaeste_abends', 'on') %}
                {{ int(80) }}
              {% elif is_state('binary_sensor.tv_pizza_abend', 'on') %}
                {{ int(30) }}
              {% elif is_state('binary_sensor.tv_abend_ohne_pizza', 'on') %}
                {{ int(20) }}
              {% else %}
                {{ int(0) }}
              {% endif %}
            {% endif %}
      - name: helper_light_is_too_dark_e_wz_schraenke
        state: >
          {{ (states("sensor.helligkeit_wohnzimmer_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_wz_schraenke") | float(1)) }}
      - name: helper_light_is_too_bright_e_wz_schraenke
        state: >
          {{ (states("sensor.helligkeit_wohnzimmer_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_wz_schraenke") | float(1) + 100 ) }}

automation:
  - alias: Licht EG WZ Schränke
    id: 'auto_light_e_wz_schraenke'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.schrankbeleuchtung_wohnzimmer
        automation_switch: input_boolean.automation_switch_light_e_wz_schraenke
        trigger: binary_sensor.helper_light_trigger_e_wz_schraenke
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_wz_schraenke
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_wz_schraenke
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_wz_schraenke
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_wz_schraenke
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_wz_schraenke
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_wz_schraenke
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_wz_schraenke
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_wz_schraenke
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_wz_schraenke
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_wz_schraenke
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_wz_schraenke
        startup_delay_seconds: 60