# strings to replace:
#
# friendly name: Licht EG Küche Sockel
# id name: e_ku_sockel
# light: light.sockelbeleuchtung

input_boolean:
  automation_switch_light_e_ku_sockel:
    name: Auto Licht EG Küche Sockel
    icon: mdi:auto-fix
  helper_light_auto_switched_e_ku_sockel:
    name: Helper - Auto Switched - Licht EG Küche Sockel
    initial: off
  helper_light_manually_switched_on_e_ku_sockel:
    name: Helper - Man Switched on - Licht EG Küche Sockel
    initial: off
  helper_light_manually_switched_off_e_ku_sockel:
    name: Helper - Man Switched off - Licht EG Küche Sockel
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_ku_sockel
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','09:00',45],
            ['09:01','23:59',45] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_e_ku_sockel
        unit_of_measurement: "%"
        state: >
          {% if is_state('input_boolean.gaeste_abends', 'on') %}
            {{ int(40) }}
          {% elif is_state('binary_sensor.kodi_abends', 'on') %}
            {{ int(20) }}
          {% elif is_state('binary_sensor.tv_abends_an', 'on') %}
            {{ int(20) }}
          {% elif is_state('binary_sensor.nachtmodus_wohnbereich_licht', 'on') %}
            {{ int(20) }}
          {% else %}
            {{ states('sensor.helper_light_basic_brightness_e_ku_sockel') }}
          {% endif %}
        attributes:
          special_brightness: >
            {{ [states('input_boolean.gaeste_abends'),states('binary_sensor.kodi_abends'),states('binary_sensor.tv_abends_an'),states('binary_sensor.nachtmodus_wohnbereich_licht')] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_ku_sockel
        unit_of_measurement: "lx"
        state: >
          {{ int(100) }}
      - name: helper_light_switching_off_entities_e_ku_sockel
        unit_of_measurement: "number"
        state: >
          {{ [states('input_boolean.arbeit_theke'),states('switch.luften_ez'),states('binary_sensor.kodi_abends')] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_e_ku_sockel
        state: >
          {{ is_state('binary_sensor.pm_e_ez_bar_kuche', 'on')
             or is_state('binary_sensor.pm_e_ez_esstisch', 'on')
             or is_state('binary_sensor.pm_e_ku_bar_ez', 'on')
             or is_state('binary_sensor.pm_e_ku_kuche', 'on')
             or is_state('binary_sensor.pm_e_wz_durchgang', 'on') }}
      - name: helper_light_keeping_off_entities_e_ku_sockel
        state: >
          {% set h = now().hour | int(0) %}
          {{ is_state('input_boolean.arbeit_theke', 'on')
             or (h >= 9 and h <= 16)
             or is_state('switch.luften_ez', 'on') }}
      - name: helper_light_keeping_on_entities_e_ku_sockel
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_e_ku_sockel
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_e_ku_sockel
        state: >
          {{ (states("sensor.helligkeit_kuche_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_ku_sockel") | float(1)) }}
      - name: helper_light_is_too_bright_e_ku_sockel
        state: >
          {{ (states("sensor.helligkeit_kuche_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_ku_sockel") | float(1) + 60 ) }}

automation:
  - alias: Licht EG Küche Sockel
    id: 'auto_light_e_ku_sockel'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.sockelbeleuchtung
        automation_switch: input_boolean.automation_switch_light_e_ku_sockel
        trigger: binary_sensor.helper_light_trigger_e_ku_sockel
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_ku_sockel
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_ku_sockel
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_ku_sockel
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_ku_sockel
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_ku_sockel
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_ku_sockel
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_ku_sockel
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_ku_sockel
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_ku_sockel
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_ku_sockel
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_ku_sockel
        transition_time: 1