# strings to replace:
#
# friendly name: Licht EG Küche Arbeitsplatte
# id name: e_ku_arbeitsplatte
# light: light.arbeitsplatte

input_boolean:
  automation_switch_light_e_ku_arbeitsplatte:
    name: Auto Licht EG Küche Arbeitsplatte
    icon: mdi:auto-fix
  helper_light_auto_switched_e_ku_arbeitsplatte:
    name: Helper - Auto Switched - Licht EG Küche Arbeitsplatte
    initial: off
  helper_light_manually_switched_on_e_ku_arbeitsplatte:
    name: Helper - Man Switched on - Licht EG Küche Arbeitsplatte
    initial: off
  helper_light_manually_switched_off_e_ku_arbeitsplatte:
    name: Helper - Man Switched off - Licht EG Küche Arbeitsplatte
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_ku_arbeitsplatte
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','04:59',40],
            ['05:00','05:59',60],
            ['06:00','07:29',65],
            ['07:30','08:59',75],
            ['09:00','17:29',80],
            ['17:30','19:29',70],
            ['19:30','21:59',60],
            ['22:00','23:59',40] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_e_ku_arbeitsplatte
        unit_of_measurement: "%"
        state: >
          {% if states('switch.luften_ez') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_effective_brightness_e_ku_arbeitsplatte') }}
          {% else %}
            {% if is_state('switch.luften_ez', 'on') %}
              {{ int(10) }}
            {% elif is_state('input_boolean.gaeste_abends', 'on') %}
              {{ int(35) }}
            {% elif is_state('binary_sensor.kodi_abends', 'on') %}
              {{ int(5) }}
            {% elif is_state('binary_sensor.tv_abends_an', 'on') %}
              {{ int(30) }}
            {% elif is_state('binary_sensor.nachtmodus_wohnbereich_licht', 'on') %}
              {{ int(20) }}
            {% else %}
              {{ states('sensor.helper_light_basic_brightness_e_ku_arbeitsplatte') }}
            {% endif %}
          {% endif %}
        attributes:
          special_brightness: >
            {% if states('switch.luften_ez') in ['unavailable', 'unknown', 'none'] %}
              {{ state_attr('binary_sensor.helper_light_effective_brightness_e_ku_arbeitsplatte','special_brightness') }}
            {% else %}
              {{ [states('switch.luften_ez'),states('input_boolean.gaeste_abends'),states('binary_sensor.kodi_abends'),states('binary_sensor.tv_abends_an'),states('binary_sensor.nachtmodus_wohnbereich_licht')] | select('equalto', 'on') | list | count }}
            {% endif %}
      - name: helper_light_min_illuminance_e_ku_arbeitsplatte
        unit_of_measurement: "lx"
        state: >
          {% set hours = 
            ['00:00','05:59',80],
            ['06:00','08:29',150],
            ['08:30','08:59',250],
            ['09:00','19:59',300],
            ['20:00','21:59',200],
            ['22:00','23:59',80] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_switching_off_entities_e_ku_arbeitsplatte
        unit_of_measurement: "number"
        state: >
          {{ [] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_e_ku_arbeitsplatte
        state: >
          {% if states('binary_sensor.pm_e_ku_kuche') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_e_ku_arbeitsplatte') }}
          {% else %}
            {{ is_state('binary_sensor.pm_e_ku_kuche', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_e_ku_arbeitsplatte
        state: >
          {{ false }}
      - name: helper_light_keeping_on_entities_e_ku_arbeitsplatte
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_e_ku_arbeitsplatte
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_e_ku_arbeitsplatte
        state: >
          {% if states('sensor.helligkeit_kuche_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_dark_e_ku_arbeitsplatte') }}
          {% else %}
            {{ (states("sensor.helligkeit_kuche_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_ku_arbeitsplatte") | float(1)) }}
          {% endif %}
      - name: helper_light_is_too_bright_e_ku_arbeitsplatte
        state: >
          {% if states('sensor.helligkeit_kuche_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_bright_e_ku_arbeitsplatte') }}
          {% else %}
            {{ (states("sensor.helligkeit_kuche_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_ku_arbeitsplatte") | float(1) + 200 ) }}
          {% endif %}

automation:
  - alias: Licht EG Küche Arbeitsplatte
    id: 'auto_light_e_ku_arbeitsplatte'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.arbeitsplatte
        automation_switch: input_boolean.automation_switch_light_e_ku_arbeitsplatte
        trigger: binary_sensor.helper_light_trigger_e_ku_arbeitsplatte
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_ku_arbeitsplatte
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_ku_arbeitsplatte
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_ku_arbeitsplatte
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_ku_arbeitsplatte
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_ku_arbeitsplatte
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_ku_arbeitsplatte
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_ku_arbeitsplatte
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_ku_arbeitsplatte
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_ku_arbeitsplatte
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_ku_arbeitsplatte
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_ku_arbeitsplatte