# strings to replace:
#
# friendly name: Licht OG Lea Wandwürfel
# id name: o_le_wandwuerfel
# light: light.wandwurfel_le

input_boolean:
  automation_switch_light_o_le_wandwuerfel:
    name: Auto Licht OG Lea Wandwürfel
    icon: mdi:auto-fix
  helper_light_auto_switched_o_le_wandwuerfel:
    name: Helper - Auto Switched - Licht OG Lea Wandwürfel
    initial: off
  helper_light_manually_switched_on_o_le_wandwuerfel:
    name: Helper - Man Switched on - Licht OG Lea Wandwürfel
    initial: off
  helper_light_manually_switched_off_o_le_wandwuerfel:
    name: Helper - Man Switched off - Licht OG Lea Wandwürfel
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_o_le_wandwuerfel
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','05:30',30],
            ['05:31','06:30',40],
            ['06:31','08:00',50],
            ['08:01','09:00',60],
            ['09:01','17:00',70],
            ['17:01','18:00',60],
            ['18:01','20:00',50],
            ['20:01','21:00',40],
            ['21:01','23:59',30] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_o_le_wandwuerfel
        unit_of_measurement: "%"
        state: >
          {% if is_state('binary_sensor.schlafen_oder_aufwachphase_le', 'on') %}
            {{ int(30) }}
          {% else %}
            {{ states('sensor.helper_light_basic_brightness_o_le_wandwuerfel') }}
          {% endif %}
        attributes:
          special_brightness: >
            {{ [states('binary_sensor.schlafen_oder_aufwachphase_le')] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_o_le_wandwuerfel
        unit_of_measurement: "lx"
        state: >
          {% set hours = 
            ['00:00','05:30',5],
            ['05:31','09:00',20],
            ['09:01','18:00',50],
            ['18:01','21:00',20],
            ['21:01','23:59',5] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_switching_off_entities_o_le_wandwuerfel
        unit_of_measurement: "number"
        state: >
          {{ [states('switch.luften_le')] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_o_le_wandwuerfel
        state: >
          {{ is_state('binary_sensor.pm_o_kw_le_raum', 'on')
             or is_state('binary_sensor.pm_o_kw_le_tuer', 'on') }}
      - name: helper_light_keeping_off_entities_o_le_wandwuerfel
        state: >
          {{ is_state('switch.bleib_so_le_licht', 'on')
             or is_state('switch.luften_le', 'on') }}
      - name: helper_light_keeping_on_entities_o_le_wandwuerfel
        state: >
          {{ is_state('switch.bleib_so_le_licht', 'on') }}
      - name: helper_light_keeping_fix_entities_o_le_wandwuerfel
        state: >
          {{ is_state('switch.le_schlaft', 'on') }}
        attributes:
          brightness: >
            {% if is_state('switch.le_schlaft', 'on') %}
              {{ int(2) }}
            {% else %}
              {{ int(0) }}
            {% endif %}
      - name: helper_light_is_too_dark_o_le_wandwuerfel
        state: >
          {{ (states("sensor.helligkeit_le_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_o_le_wandwuerfel") | float(1)) }}
      - name: helper_light_is_too_bright_o_le_wandwuerfel
        state: >
          {{ (states("sensor.helligkeit_le_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_o_le_wandwuerfel") | float(1) + 100 ) }}

automation:
  - alias: Licht OG Lea Wandwürfel
    id: 'auto_light_o_le_wandwuerfel'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.wandwurfel_le
        automation_switch: input_boolean.automation_switch_light_o_le_wandwuerfel
        trigger: binary_sensor.helper_light_trigger_o_le_wandwuerfel
        helper_effective_brightness: sensor.helper_light_effective_brightness_o_le_wandwuerfel
        helper_basic_brightness: sensor.helper_light_basic_brightness_o_le_wandwuerfel
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_o_le_wandwuerfel
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_o_le_wandwuerfel
        helper_auto_switched: input_boolean.helper_light_auto_switched_o_le_wandwuerfel
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_o_le_wandwuerfel
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_o_le_wandwuerfel
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_o_le_wandwuerfel
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_o_le_wandwuerfel
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_o_le_wandwuerfel
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_o_le_wandwuerfel
        startup_delay_seconds: 60