# strings to replace:
#
# friendly name: Licht Carport Abstellraum Decke
# id name: a_ar_decke
# light: light.abstellraum_carport

input_boolean:
  automation_switch_light_a_ar_decke:
    name: Auto Licht Carport Abstellraum Decke
    icon: mdi:auto-fix
  helper_light_auto_switched_a_ar_decke:
    name: Helper - Auto Switched - Licht Carport Abstellraum Decke
    initial: off
  helper_light_manually_switched_on_a_ar_decke:
    name: Helper - Man Switched on - Licht Carport Abstellraum Decke
    initial: off
  helper_light_manually_switched_off_a_ar_decke:
    name: Helper - Man Switched off - Licht Carport Abstellraum Decke
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_a_ar_decke
        unit_of_measurement: "%"
        state: >
          {{ int(100 )}}
      - name: helper_light_effective_brightness_a_ar_decke
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_a_ar_decke') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_a_ar_decke
        unit_of_measurement: "lx"
        state: >
          {{ int(4000000) }}
      - name: helper_light_switching_off_entities_a_ar_decke
        unit_of_measurement: "number"
        state: >
          {{ [] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_a_ar_decke
        state: >
          {{ is_state('binary_sensor.pm_a_ar', 'on') }}
      - name: helper_light_keeping_off_entities_a_ar_decke
        state: >
          {{ False }}
      - name: helper_light_keeping_on_entities_a_ar_decke
        state: >
          {{ is_state('binary_sensor.pm_a_eg', 'on') 
             or is_state('binary_sensor.pm_a_cp', 'on') }}
      - name: helper_light_keeping_fix_entities_a_ar_decke
        state: >
          {{ False }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_a_ar_decke
        state: >
          {{ (states("sensor.helligkeit_wetterstation") | float(0)) < (states("sensor.helper_light_min_illuminance_a_ar_decke") | float(1)) }}
      - name: helper_light_is_too_bright_a_ar_decke
        state: >
          {{ (states("sensor.helligkeit_wetterstation") | float(0)) > (states("sensor.helper_light_min_illuminance_a_ar_decke") | float(1) + 10000 ) }}

automation:
  - alias: Licht Carport Abstellraum Decke
    id: 'auto_light_a_ar_decke'
    description: ''
    trace:
      stored_traces: 5
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.abstellraum_carport
        automation_switch: input_boolean.automation_switch_light_a_ar_decke
        trigger: binary_sensor.helper_light_trigger_a_ar_decke
        helper_effective_brightness: sensor.helper_light_effective_brightness_a_ar_decke
        helper_basic_brightness: sensor.helper_light_basic_brightness_a_ar_decke
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_a_ar_decke
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_a_ar_decke
        helper_auto_switched: input_boolean.helper_light_auto_switched_a_ar_decke
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_a_ar_decke
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_a_ar_decke
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_a_ar_decke
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_a_ar_decke
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_a_ar_decke
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_a_ar_decke
        startup_delay_seconds: 60