# strings to replace:
#
# friendly name: Licht Carport Bodenlicht
# id name: a_cp_bodenlicht
# light: light.bodenlicht_eingang

input_boolean:
  automation_switch_light_a_cp_bodenlicht:
    name: Auto Licht Carport Bodenlicht
    icon: mdi:auto-fix
  helper_light_auto_switched_a_cp_bodenlicht:
    name: Helper - Auto Switched - Licht Carport Bodenlicht
    initial: off
  helper_light_manually_switched_on_a_cp_bodenlicht:
    name: Helper - Man Switched on - Licht Carport Bodenlicht
    initial: off
  helper_light_manually_switched_off_a_cp_bodenlicht:
    name: Helper - Man Switched off - Licht Carport Bodenlicht
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_a_cp_bodenlicht
        unit_of_measurement: "%"
        state: >
          {{ int(70) }}
      - name: helper_light_effective_brightness_a_cp_bodenlicht
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_a_cp_bodenlicht') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_a_cp_bodenlicht
        unit_of_measurement: "lx"
        state: >
          {{ int(2000) }}
      - name: helper_light_switching_off_entities_a_cp_bodenlicht
        unit_of_measurement: "number"
        state: >
          {{ [] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_stay_as_you_are_a_cp_bodenlicht
        state: >
          {{ false }}
      - name: helper_light_trigger_a_cp_bodenlicht
        state: >
          {{ is_state('binary_sensor.pm_a_eg', 'on') 
             or is_state('binary_sensor.pm_a_cp', 'on')
             or is_state('binary_sensor.pm_a_ar', 'on') }}
      - name: helper_light_keeping_off_entities_a_cp_bodenlicht
        state: >
          {{ false }}
      - name: helper_light_keeping_on_entities_a_cp_bodenlicht
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_a_cp_bodenlicht
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_a_cp_bodenlicht
        state: >
          {{ (states("sensor.helligkeit_wetterstation") | float(0)) < (states("sensor.helper_light_min_illuminance_a_cp_bodenlicht") | float(1)) }}
      - name: helper_light_is_too_bright_a_cp_bodenlicht
        state: >
          {{ (states("sensor.helligkeit_wetterstation") | float(0)) > (states("sensor.helper_light_min_illuminance_a_cp_bodenlicht") | float(1) + 100 ) }}

automation:
  - alias: Licht Carport Bodenlicht
    id: 'auto_light_a_cp_bodenlicht'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.bodenlicht_eingang
        automation_switch: input_boolean.automation_switch_light_a_cp_bodenlicht
        helper_stay_as_you_are: binary_sensor.helper_stay_as_you_are_a_cp_bodenlicht
        trigger: binary_sensor.helper_light_trigger_a_cp_bodenlicht
        helper_effective_brightness: sensor.helper_light_effective_brightness_a_cp_bodenlicht
        helper_basic_brightness: sensor.helper_light_basic_brightness_a_cp_bodenlicht
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_a_cp_bodenlicht
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_a_cp_bodenlicht
        helper_auto_switched: input_boolean.helper_light_auto_switched_a_cp_bodenlicht
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_a_cp_bodenlicht
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_a_cp_bodenlicht
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_a_cp_bodenlicht
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_a_cp_bodenlicht
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_a_cp_bodenlicht
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_a_cp_bodenlicht