# strings to replace:
#
# friendly name: Licht Keller Flur
# id name: k_flur
# light: light.flur_keller

input_boolean:
  automation_switch_light_k_flur:
    name: Auto Licht Keller Flur
    icon: mdi:auto-fix
  helper_light_auto_switched_k_flur:
    name: Helper - Auto Switched - Licht Keller Flur
    initial: off
  helper_light_manually_switched_on_k_flur:
    name: Helper - Man Switched on - Licht Keller Flur
    initial: off
  helper_light_manually_switched_off_k_flur:
    name: Helper - Man Switched off - Licht Keller Flur
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_k_flur
        unit_of_measurement: "%"
        state: >
          {{ int(100 )}}
      - name: helper_light_effective_brightness_k_flur
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_k_flur') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_k_flur
        unit_of_measurement: "lx"
        state: >
          {{ int(100) }}
      - name: helper_light_switching_off_entities_k_flur
        unit_of_measurement: "number"
        state: >
          {{ [] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_k_flur
        state: >
          {% if states('binary_sensor.pm_ktr_treppe') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_k_fl_2') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_k_flur') }}
          {% else %}
            {{ is_state('binary_sensor.pm_ktr_treppe', 'on')
               or is_state('binary_sensor.pm_k_fl_2', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_k_flur
        state: >
          {{ False }}
      - name: helper_light_keeping_on_entities_k_flur
        state: >
          {{ False }}
      - name: helper_light_keeping_fix_entities_k_flur
        state: >
          {{ False }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_k_flur
        state: >
          {{ true }}
      - name: helper_light_is_too_bright_k_flur
        state: >
          {{ false }}

automation:
  - alias: Licht Keller Flur
    id: 'auto_light_k_flur'
    description: ''
    trace:
      stored_traces: 5
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.flur_keller
        automation_switch: input_boolean.automation_switch_light_k_flur
        trigger: binary_sensor.helper_light_trigger_k_flur
        helper_effective_brightness: sensor.helper_light_effective_brightness_k_flur
        helper_basic_brightness: sensor.helper_light_basic_brightness_k_flur
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_k_flur
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_k_flur
        helper_auto_switched: input_boolean.helper_light_auto_switched_k_flur
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_k_flur
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_k_flur
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_k_flur
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_k_flur
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_k_flur
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_k_flur