# strings to replace:
#
# friendly name: Licht EG EZ Wandleuchten hell
# id name: e_ez_wandleuchten_hell
# light: light.wandleuchten_esszimmer_hell

input_boolean:
  automation_switch_light_e_ez_wandleuchten_hell:
    name: Auto Licht EG EZ Wandleuchten hell
    icon: mdi:auto-fix
  helper_light_auto_switched_e_ez_wandleuchten_hell:
    name: Helper - Auto Switched - Licht EG EZ Wandleuchten hell
    initial: off
  helper_light_manually_switched_on_e_ez_wandleuchten_hell:
    name: Helper - Man Switched on - Licht EG EZ Wandleuchten hell
    initial: off
  helper_light_manually_switched_off_e_ez_wandleuchten_hell:
    name: Helper - Man Switched off - Licht EG EZ Wandleuchten hell
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_ez_wandleuchten_hell
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','05:00',50],
            ['05:01','06:00',60],
            ['06:01','19:30',70],
            ['19:31','21:30',55],
            ['21:31','23:59',50] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_e_ez_wandleuchten_hell
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_e_ez_wandleuchten_hell') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_ez_wandleuchten_hell
        unit_of_measurement: "lx"
        state: >
          {% set hours = 
            ['00:00','07:00',40],
            ['07:01','08:00',60],
            ['08:01','18:30',80],
            ['18:31','21:30',60],
            ['21:31','23:59',40] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_switching_off_entities_e_ez_wandleuchten_hell
        unit_of_measurement: "number"
        state: >
          {{ [states('binary_sensor.tv_zeit_abend'),states('input_boolean.gaeste_abends'),states('input_boolean.arbeit_theke'),states('switch.luften_ez')] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_e_ez_wandleuchten_hell
        state: >
          {% if states('binary_sensor.pm_e_ez_bar_kuche') in ['unavialable', 'unknown', 'none']
             or states('binary_sensor.pm_e_ez_esstisch') in ['unavialable', 'unknown', 'none']
             or states('binary_sensor.pm_e_ku_bar_ez') in ['unavialable', 'unknown', 'none']
             or states('binary_sensor.pm_e_ku_kuche') in ['unavialable', 'unknown', 'none']
             or states('binary_sensor.pm_e_wz_durchgang') in ['unavialable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_e_ez_wandleuchten_hell') }}
          {% else %}
            {{ is_state('binary_sensor.pm_e_ez_bar_kuche', 'on')
               or is_state('binary_sensor.pm_e_ez_esstisch', 'on')
               or is_state('binary_sensor.pm_e_ku_bar_ez', 'on')
               or is_state('binary_sensor.pm_e_ku_kuche', 'on')
               or is_state('binary_sensor.pm_e_wz_durchgang', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_e_ez_wandleuchten_hell
        state: >
          {{ is_state('binary_sensor.nachtmodus_wohnbereich_licht', 'on')
             or is_state('binary_sensor.tv_zeit_abend', 'on')
             or is_state('input_boolean.gaeste_abends', 'on')
             or is_state('input_boolean.arbeit_theke', 'on')
             or is_state('switch.luften_ez', 'on') }}
      - name: helper_light_keeping_on_entities_e_ez_wandleuchten_hell
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_e_ez_wandleuchten_hell
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_e_ez_wandleuchten_hell
        state: >
          {{ (states("sensor.helligkeit_esszimmer_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_ez_wandleuchten_hell") | float(1)) }}
      - name: helper_light_is_too_bright_e_ez_wandleuchten_hell
        state: >
          {{ (states("sensor.helligkeit_esszimmer_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_ez_wandleuchten_hell") | float(1) + 100 ) }}

automation:
  - alias: Licht EG EZ Wandleuchten hell
    id: 'auto_light_e_ez_wandleuchten_hell'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.wandleuchten_esszimmer_hell
        automation_switch: input_boolean.automation_switch_light_e_ez_wandleuchten_hell
        trigger: binary_sensor.helper_light_trigger_e_ez_wandleuchten_hell
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_ez_wandleuchten_hell
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_ez_wandleuchten_hell
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_ez_wandleuchten_hell
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_ez_wandleuchten_hell
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_ez_wandleuchten_hell
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_ez_wandleuchten_hell
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_ez_wandleuchten_hell
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_ez_wandleuchten_hell
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_ez_wandleuchten_hell
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_ez_wandleuchten_hell
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_ez_wandleuchten_hell
        startup_delay_seconds: 60