# strings to replace:
#
# friendly name: Licht Garten Stern Blumenbeet
# id name: a_ga_stern_blumenbeet
# light: light.stern_blumenbeet

input_boolean:
  automation_switch_light_a_ga_stern_blumenbeet:
    name: Auto Licht Garten Stern Blumenbeet
    icon: mdi:auto-fix
  helper_light_auto_switched_a_ga_stern_blumenbeet:
    name: Helper - Auto Switched - Licht Garten Stern Blumenbeet
    initial: off
  helper_light_manually_switched_on_a_ga_stern_blumenbeet:
    name: Helper - Man Switched on - Licht Garten Stern Blumenbeet
    initial: off
  helper_light_manually_switched_off_a_ga_stern_blumenbeet:
    name: Helper - Man Switched off - Licht Garten Stern Blumenbeet
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_a_ga_stern_blumenbeet
        unit_of_measurement: "%"
        state: >
          {{ int(100 )}}
      - name: helper_light_effective_brightness_a_ga_stern_blumenbeet
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_a_ga_stern_blumenbeet') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_a_ga_stern_blumenbeet
        unit_of_measurement: "lx"
        state: >
          {{ int(10000) }}
      - name: helper_light_switching_off_entities_a_ga_stern_blumenbeet
        unit_of_measurement: "number"
        state: >
          {{ [] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_a_ga_stern_blumenbeet
        state: >
          {{ is_state('binary_sensor.zeit_stern', 'on') }}
      - name: helper_light_keeping_off_entities_a_ga_stern_blumenbeet
        state: >
          {{ False }}
      - name: helper_light_keeping_on_entities_a_ga_stern_blumenbeet
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_a_ga_stern_blumenbeet
        state: >
          {{ False }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_a_ga_stern_blumenbeet
        state: >
          {{ (states("sensor.helligkeit_wetterstation") | float(0)) < (states("sensor.helper_light_min_illuminance_a_ga_stern_blumenbeet") | float(1)) }}
      - name: helper_light_is_too_bright_a_ga_stern_blumenbeet
        state: >
          {{ (states("sensor.helligkeit_wetterstation") | float(0)) > (states("sensor.helper_light_min_illuminance_a_ga_stern_blumenbeet") | float(1) + 5000 ) }}

automation:
  - alias: Licht Garten Stern Blumenbeet
    id: 'auto_light_a_ga_stern_blumenbeet'
    description: ''
    trace:
      stored_traces: 5
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.stern_blumenbeet
        automation_switch: input_boolean.automation_switch_light_a_ga_stern_blumenbeet
        trigger: binary_sensor.helper_light_trigger_a_ga_stern_blumenbeet
        helper_effective_brightness: sensor.helper_light_effective_brightness_a_ga_stern_blumenbeet
        helper_basic_brightness: sensor.helper_light_basic_brightness_a_ga_stern_blumenbeet
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_a_ga_stern_blumenbeet
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_a_ga_stern_blumenbeet
        helper_auto_switched: input_boolean.helper_light_auto_switched_a_ga_stern_blumenbeet
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_a_ga_stern_blumenbeet
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_a_ga_stern_blumenbeet
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_a_ga_stern_blumenbeet
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_a_ga_stern_blumenbeet
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_a_ga_stern_blumenbeet
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_a_ga_stern_blumenbeet