# strings to replace:
#
# friendly name: Licht EG Schlafzimmer Kugellampe
# id name: e_sz_kugellampe
# light: light.0x680ae2fffee9df98

input_boolean:
  automation_switch_light_e_sz_kugellampe:
    name: Auto Licht EG Schlafzimmer Kugellampe
    icon: mdi:auto-fix
  helper_light_auto_switched_e_sz_kugellampe:
    name: Helper - Auto Switched - Licht EG Schlafzimmer Kugellampe
    initial: off
  helper_light_manually_switched_on_e_sz_kugellampe:
    name: Helper - Man Switched on - Licht EG Schlafzimmer Kugellampe
    initial: off
  helper_light_manually_switched_off_e_sz_kugellampe:
    name: Helper - Man Switched off - Licht EG Schlafzimmer Kugellampe
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_sz_kugellampe
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','15:59',30],
            ['16:00','20:59',80],
            ['21:00','21:59',50],
            ['22:00','23:59',30] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_e_sz_kugellampe
        unit_of_measurement: "%"
        state: >
          {% if is_state('binary_sensor.schlafen_oder_aufwachphase_majo', 'on') %}
            {{ int(10) }}
          {% else %}
            {{ states('sensor.helper_light_basic_brightness_e_sz_kugellampe') }}
          {% endif %}
        attributes:
          special_brightness: >
            {{ [states('binary_sensor.schlafen_oder_aufwachphase_majo')] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_sz_kugellampe
        unit_of_measurement: "lx"
        state: >
          {{ int(20) }}
      - name: helper_light_switching_off_entities_e_sz_kugellampe
        unit_of_measurement: "number"
        state: >
          {% if states('switch.majo_schlafen') in ['unavailable', 'unknown', 'none']
             or states('switch.knutschen') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_sz') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_switching_off_entities_e_sz_kugellampe') }}
          {% else %}
            {{ [states('switch.majo_schlafen'),states('switch.knutschen'),states('switch.luften_sz')] | select('equalto', 'on') | list | count }}
          {% endif %}
    binary_sensor:
      - name: helper_light_trigger_e_sz_kugellampe
        state: >
          {% if states('binary_sensor.pm_e_sz_bett') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_sz_gang') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_e_sz_kugellampe') }}
          {% else %}
            {{ is_state('binary_sensor.pm_e_sz_bett', 'on')
               or is_state('binary_sensor.pm_e_sz_gang', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_e_sz_kugellampe
        state: >
          {% set h = now().hour | int(0) %}
          {% if states('switch.majo_schlafen') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.schlafen_oder_licht_noch_aus_lassen_majo') in ['unavailable', 'unknown', 'none']
             or states('switch.knutschen') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_sz') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_off_entities_e_sz_kugellampe') }}
          {% else %}
            {{ is_state('switch.majo_schlafen', 'on')
              or is_state('binary_sensor.schlafen_oder_licht_noch_aus_lassen_majo', 'on')
              or is_state('switch.knutschen', 'on')
              or (h >= 3 and h <= 15)
              or is_state('switch.luften_sz', 'on') }}
          {% endif %}
      - name: helper_light_keeping_on_entities_e_sz_kugellampe
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_e_sz_kugellampe
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_e_sz_kugellampe
        state: >
          {% if states('sensor.helligkeit_schlafzimmer_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_dark_e_sz_kugellampe') }}
          {% else %}
            {{ (states("sensor.helligkeit_schlafzimmer_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_sz_kugellampe") | float(1)) }}
          {% endif %}
      - name: helper_light_is_too_bright_e_sz_kugellampe
        state: >
          {% if states('sensor.helligkeit_schlafzimmer_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_bright_e_sz_kugellampe') }}
          {% else %}
            {{ (states("sensor.helligkeit_schlafzimmer_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_sz_kugellampe") | float(1) + 100 ) }}
          {% endif %}

automation:
  - alias: Licht EG Schlafzimmer Kugellampe
    id: 'auto_light_e_sz_kugellampe'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.0x680ae2fffee9df98
        automation_switch: input_boolean.automation_switch_light_e_sz_kugellampe
        trigger: binary_sensor.helper_light_trigger_e_sz_kugellampe
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_sz_kugellampe
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_sz_kugellampe
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_sz_kugellampe
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_sz_kugellampe
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_sz_kugellampe
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_sz_kugellampe
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_sz_kugellampe
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_sz_kugellampe
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_sz_kugellampe
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_sz_kugellampe
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_sz_kugellampe