# strings to replace:
#
# friendly name: Licht Garten Bodenstrahler Blumenbeet
# id name: a_ga_bodenstrahler_blumenbeet
# light: light.bodenstrahler_blumenbeet

input_boolean:
  automation_switch_light_a_ga_bodenstrahler_blumenbeet:
    name: Auto Licht Garten Bodenstrahler Blumenbeet
    icon: mdi:auto-fix
  helper_light_auto_switched_a_ga_bodenstrahler_blumenbeet:
    name: Helper - Auto Switched - Licht Garten Bodenstrahler Blumenbeet
    initial: off
  helper_light_manually_switched_on_a_ga_bodenstrahler_blumenbeet:
    name: Helper - Man Switched on - Licht Garten Bodenstrahler Blumenbeet
    initial: off
  helper_light_manually_switched_off_a_ga_bodenstrahler_blumenbeet:
    name: Helper - Man Switched off - Licht Garten Bodenstrahler Blumenbeet
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_a_ga_bodenstrahler_blumenbeet
        unit_of_measurement: "%"
        state: >
          {{ int(100 )}}
      - name: helper_light_effective_brightness_a_ga_bodenstrahler_blumenbeet
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_a_ga_bodenstrahler_blumenbeet') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_a_ga_bodenstrahler_blumenbeet
        unit_of_measurement: "lx"
        state: >
          {{ int(200) }}
      - name: helper_light_switching_off_entities_a_ga_bodenstrahler_blumenbeet
        unit_of_measurement: "number"
        state: >
          {% if states('switch.luften_ez') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_switching_off_entities_a_ga_bodenstrahler_blumenbeet') }}
          {% else %}
            {{ [states('switch.luften_ez')] | select('equalto', 'on') | list | count }}
          {% endif %}
    binary_sensor:
      - name: helper_stay_as_you_are_a_ga_bodenstrahler_blumenbeet
        state: >
          {{ false }}
      - name: helper_light_trigger_a_ga_bodenstrahler_blumenbeet
        state: >
          {{ is_state('binary_sensor.bodenstrahler_blumenbeet_soll_an_sein', 'on') }}
      - name: helper_light_keeping_off_entities_a_ga_bodenstrahler_blumenbeet
        state: >
          {% if states('switch.luften_ez') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_off_entities_a_ga_bodenstrahler_blumenbeet') }}
          {% else %}
            {{ is_state('switch.luften_ez', 'on') }}
          {% endif %}
      - name: helper_light_keeping_on_entities_a_ga_bodenstrahler_blumenbeet
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_a_ga_bodenstrahler_blumenbeet
        state: >
          {{ False }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_a_ga_bodenstrahler_blumenbeet
        state: >
          {{ (states("sensor.helligkeit_wetterstation") | float(0)) < (states("sensor.helper_light_min_illuminance_a_ga_bodenstrahler_blumenbeet") | float(1)) }}
      - name: helper_light_is_too_bright_a_ga_bodenstrahler_blumenbeet
        state: >
          {{ (states("sensor.helligkeit_wetterstation") | float(0)) > (states("sensor.helper_light_min_illuminance_a_ga_bodenstrahler_blumenbeet") | float(1) + 100 ) }}

automation:
  - alias: Licht Garten Bodenstrahler Blumenbeet
    id: 'auto_light_a_ga_bodenstrahler_blumenbeet'
    description: ''
    trace:
      stored_traces: 5
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.bodenstrahler_blumenbeet
        automation_switch: input_boolean.automation_switch_light_a_ga_bodenstrahler_blumenbeet
        helper_stay_as_you_are: binary_sensor.helper_stay_as_you_are_a_ga_bodenstrahler_blumenbeet
        trigger: binary_sensor.helper_light_trigger_a_ga_bodenstrahler_blumenbeet
        helper_effective_brightness: sensor.helper_light_effective_brightness_a_ga_bodenstrahler_blumenbeet
        helper_basic_brightness: sensor.helper_light_basic_brightness_a_ga_bodenstrahler_blumenbeet
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_a_ga_bodenstrahler_blumenbeet
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_a_ga_bodenstrahler_blumenbeet
        helper_auto_switched: input_boolean.helper_light_auto_switched_a_ga_bodenstrahler_blumenbeet
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_a_ga_bodenstrahler_blumenbeet
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_a_ga_bodenstrahler_blumenbeet
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_a_ga_bodenstrahler_blumenbeet
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_a_ga_bodenstrahler_blumenbeet
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_a_ga_bodenstrahler_blumenbeet
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_a_ga_bodenstrahler_blumenbeet