# strings to replace:
#
# friendly name: Licht EG Bad Spiegel oben
# id name: e_ba_spiegel_oben
# light: light.led_auf_spiegelschrank_bad_eg

input_boolean:
  automation_switch_light_e_ba_spiegel_oben:
    name: Auto Licht EG Bad Spiegel oben
    icon: mdi:auto-fix
  helper_light_auto_switched_e_ba_spiegel_oben:
    name: Helper - Auto Switched - Licht EG Bad Spiegel oben
    initial: off
  helper_light_manually_switched_on_e_ba_spiegel_oben:
    name: Helper - Man Switched on - Licht EG Bad Spiegel oben
    initial: off
  helper_light_manually_switched_off_e_ba_spiegel_oben:
    name: Helper - Man Switched off - Licht EG Bad Spiegel oben
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_ba_spiegel_oben
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','05:59',70],
            ['06:00','17:59',80],
            ['18:00','21:59',90],
            ['22:00','23:59',80] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_e_ba_spiegel_oben
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_e_ba_spiegel_oben') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_ba_spiegel_oben
        unit_of_measurement: "lx"
        state: >
          {% set hours = 
            ['00:00','05:59',10],
            ['06:00','06:59',25],
            ['07:00','07:59',40],
            ['08:00','16:59',50],
            ['17:00','17:59',40],
            ['18:00','23:59',30] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_switching_off_entities_e_ba_spiegel_oben
        unit_of_measurement: "number"
        state: >
          {{ [] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_e_ba_spiegel_oben
        state: >
          {% if states('binary_sensor.pm_e_ba') in ['unavialable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_e_ba_spiegel_oben') }}
          {% else %}
            {{ is_state('binary_sensor.pm_e_ba', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_e_ba_spiegel_oben
        state: >
          {% if states('switch.majo_schlafen') in ['unavialable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_off_entities_e_ba_spiegel_oben') }}
          {% else %}
            {{ is_state('switch.majo_schlafen', 'on') }}
          {% endif %}
      - name: helper_light_keeping_on_entities_e_ba_spiegel_oben
        state: >
          {{ False }}
      - name: helper_light_keeping_fix_entities_e_ba_spiegel_oben
        state: >
          {{ False }}
        attributes:
          brightness: >
            {{ 0 }}
      - name: helper_light_is_too_dark_e_ba_spiegel_oben
        state: >
          {{ (states("sensor.helligkeit_bad_eg_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_ba_spiegel_oben") | float(1)) }}
      - name: helper_light_is_too_bright_e_ba_spiegel_oben
        state: >
          {{ (states("sensor.helligkeit_bad_eg_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_ba_spiegel_oben") | float(1) + 100 ) }}

automation:
  - alias: Licht EG Bad Spiegel oben
    id: 'auto_light_e_ba_spiegel_oben'
    description: ''
    trace:
      stored_traces: 5
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.led_auf_spiegelschrank_bad_eg
        automation_switch: input_boolean.automation_switch_light_e_ba_spiegel_oben
        trigger: binary_sensor.helper_light_trigger_e_ba_spiegel_oben
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_ba_spiegel_oben
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_ba_spiegel_oben
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_ba_spiegel_oben
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_ba_spiegel_oben
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_ba_spiegel_oben
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_ba_spiegel_oben
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_ba_spiegel_oben
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_ba_spiegel_oben
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_ba_spiegel_oben
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_ba_spiegel_oben
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_ba_spiegel_oben
        startup_delay_seconds: 60