# strings to replace:
#
# friendly name: Licht EG EZ Weihnachtsbaum
# id name: e_ez_weihnachtsbaum
# light: light.sd_fussraum_bar

input_boolean:
  automation_switch_light_e_ez_weihnachtsbaum:
    name: Auto Licht EG EZ Weihnachtsbaum
    icon: mdi:auto-fix
  helper_light_auto_switched_e_ez_weihnachtsbaum:
    name: Helper - Auto Switched - Licht EG EZ Weihnachtsbaum
    initial: off
  helper_light_manually_switched_on_e_ez_weihnachtsbaum:
    name: Helper - Man Switched on - Licht EG EZ Weihnachtsbaum
    initial: off
  helper_light_manually_switched_off_e_ez_weihnachtsbaum:
    name: Helper - Man Switched off - Licht EG EZ Weihnachtsbaum
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_ez_weihnachtsbaum
        unit_of_measurement: "%"
        state: >
          {{ int(100) }}
      - name: helper_light_effective_brightness_e_ez_weihnachtsbaum
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_e_ez_weihnachtsbaum') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_ez_weihnachtsbaum
        unit_of_measurement: "lx"
        state: >
          {{ int(400) }}
      - name: helper_light_switching_off_entities_e_ez_weihnachtsbaum
        unit_of_measurement: "number"
        state: >
          {{ [states('binary_sensor.tv_abends_an')] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_e_ez_weihnachtsbaum
        state: >
          {% if states('binary_sensor.pm_e_ez_bar_kuche') in ['unavialable', 'unknown', 'none']
             or states('binary_sensor.pm_e_ez_esstisch') in ['unavialable', 'unknown', 'none']
             or states('binary_sensor.pm_e_ku_bar_ez') in ['unavialable', 'unknown', 'none']
             or states('binary_sensor.pm_e_ku_kuche') in ['unavialable', 'unknown', 'none']
             or states('binary_sensor.pm_e_wz_durchgang') in ['unavialable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_e_ez_weihnachtsbaum') }}
          {% else %}
            {{ is_state('binary_sensor.pm_e_ez_bar_kuche', 'on')
               or is_state('binary_sensor.pm_e_ez_esstisch', 'on')
               or is_state('binary_sensor.pm_e_ku_bar_ez', 'on')
               or is_state('binary_sensor.pm_e_ku_kuche', 'on')
               or is_state('binary_sensor.pm_e_wz_durchgang', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_e_ez_weihnachtsbaum
        state: >
          {{ is_state('binary_sensor.tv_abends_an', 'on') }}
      - name: helper_light_keeping_on_entities_e_ez_weihnachtsbaum
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_e_ez_weihnachtsbaum
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_e_ez_weihnachtsbaum
        state: >
          {{ (states("sensor.helligkeit_esszimmer_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_ez_weihnachtsbaum") | float(1)) }}
      - name: helper_light_is_too_bright_e_ez_weihnachtsbaum
        state: >
          {{ (states("sensor.helligkeit_esszimmer_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_ez_weihnachtsbaum") | float(1) + 100 ) }}

automation:
  - alias: Licht EG EZ Weihnachtsbaum
    id: 'auto_light_e_ez_weihnachtsbaum'
    description: ''
    trace:
      stored_traces: 5
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.sd_fussraum_bar
        automation_switch: input_boolean.automation_switch_light_e_ez_weihnachtsbaum
        trigger: binary_sensor.helper_light_trigger_e_ez_weihnachtsbaum
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_ez_weihnachtsbaum
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_ez_weihnachtsbaum
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_ez_weihnachtsbaum
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_ez_weihnachtsbaum
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_ez_weihnachtsbaum
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_ez_weihnachtsbaum
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_ez_weihnachtsbaum
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_ez_weihnachtsbaum
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_ez_weihnachtsbaum
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_ez_weihnachtsbaum
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_ez_weihnachtsbaum
        startup_delay_seconds: 60