# strings to replace:
#
# friendly name: Licht OG Lea Stehlampe
# id name: o_le_stehlampe
# light: light.innr_e14_tw_stehlampe_lea_level_light_color_on_off

input_boolean:
  automation_switch_light_o_le_stehlampe:
    name: Auto Licht OG Lea Stehlampe
    icon: mdi:auto-fix
  helper_light_auto_switched_o_le_stehlampe:
    name: Helper - Auto Switched - Licht OG Lea Stehlampe
    initial: off
  helper_light_manually_switched_on_o_le_stehlampe:
    name: Helper - Man Switched on - Licht OG Lea Stehlampe
    initial: off
  helper_light_manually_switched_off_o_le_stehlampe:
    name: Helper - Man Switched off - Licht OG Lea Stehlampe
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_o_le_stehlampe
        unit_of_measurement: "%"
        state: >
          {{ int(80) }}
      - name: helper_light_effective_brightness_o_le_stehlampe
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_o_le_stehlampe') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_o_le_stehlampe
        unit_of_measurement: "lx"
        state: >
          {{ int(100) }}
      - name: helper_light_switching_off_entities_o_le_stehlampe
        unit_of_measurement: "number"
        state: >
          {{ [states('switch.le_schlaft'),states('switch.luften_le')] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_o_le_stehlampe
        state: >
          {{ is_state('binary_sensor.pm_o_kw_le_raum', 'on')
             or is_state('binary_sensor.pm_o_kw_le_tuer', 'on') }}
      - name: helper_light_keeping_off_entities_o_le_stehlampe
        state: >
          {{ true }}
      - name: helper_light_keeping_on_entities_o_le_stehlampe
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_o_le_stehlampe
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_o_le_stehlampe
        state: >
          {{ false }}
      - name: helper_light_is_too_bright_o_le_stehlampe
        state: >
          {{ false }}

automation:
  - alias: Licht OG Lea Stehlampe
    id: 'auto_light_o_le_stehlampe'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.innr_e14_tw_stehlampe_lea_level_light_color_on_off
        automation_switch: input_boolean.automation_switch_light_o_le_stehlampe
        trigger: binary_sensor.helper_light_trigger_o_le_stehlampe
        helper_effective_brightness: sensor.helper_light_effective_brightness_o_le_stehlampe
        helper_basic_brightness: sensor.helper_light_basic_brightness_o_le_stehlampe
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_o_le_stehlampe
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_o_le_stehlampe
        helper_auto_switched: input_boolean.helper_light_auto_switched_o_le_stehlampe
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_o_le_stehlampe
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_o_le_stehlampe
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_o_le_stehlampe
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_o_le_stehlampe
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_o_le_stehlampe
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_o_le_stehlampe
        transition_time: 1