# strings to replace:
#
# friendly name: Licht Keller Partyraum Decke
# id name: k_pr_decke
# light: light.lagerraum

input_boolean:
  automation_switch_light_k_pr_decke:
    name: Auto Licht Keller Partyraum Decke
    icon: mdi:auto-fix
  helper_light_auto_switched_k_pr_decke:
    name: Helper - Auto Switched - Licht Keller Partyraum Decke
    initial: off
  helper_light_manually_switched_on_k_pr_decke:
    name: Helper - Man Switched on - Licht Keller Partyraum Decke
    initial: off
  helper_light_manually_switched_off_k_pr_decke:
    name: Helper - Man Switched off - Licht Keller Partyraum Decke
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_k_pr_decke
        unit_of_measurement: "%"
        state: >
          {{ int(100 )}}
      - name: helper_light_effective_brightness_k_pr_decke
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_k_pr_decke') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_k_pr_decke
        unit_of_measurement: "lx"
        state: >
          {{ int(100) }}
      - name: helper_light_switching_off_entities_k_pr_decke
        unit_of_measurement: "number"
        state: >
          {{ [] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_k_pr_decke
        state: >
          {% if states('binary_sensor.pm_k_timer_bewegung_partyraum') in ['unavialable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_k_pr_decke') }}
          {% else %}
            {{ is_state('binary_sensor.pm_k_timer_bewegung_partyraum', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_k_pr_decke
        state: >
          {{ False }}
      - name: helper_light_keeping_on_entities_k_pr_decke
        state: >
          {{ False }}
      - name: helper_light_keeping_fix_entities_k_pr_decke
        state: >
          {{ False }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_k_pr_decke
        state: >
          {{ true }}
      - name: helper_light_is_too_bright_k_pr_decke
        state: >
          {{ false }}

automation:
  - alias: Licht Keller Partyraum Decke
    id: 'auto_light_k_pr_decke'
    description: ''
    trace:
      stored_traces: 5
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.lagerraum
        automation_switch: input_boolean.automation_switch_light_k_pr_decke
        trigger: binary_sensor.helper_light_trigger_k_pr_decke
        helper_effective_brightness: sensor.helper_light_effective_brightness_k_pr_decke
        helper_basic_brightness: sensor.helper_light_basic_brightness_k_pr_decke
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_k_pr_decke
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_k_pr_decke
        helper_auto_switched: input_boolean.helper_light_auto_switched_k_pr_decke
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_k_pr_decke
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_k_pr_decke
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_k_pr_decke
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_k_pr_decke
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_k_pr_decke
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_k_pr_decke
        startup_delay_seconds: 60