# strings to replace:
#
# friendly name: Licht OG Lara Panels
# id name: o_la_panels
# light: light.panels_la

input_boolean:
  automation_switch_light_o_la_panels:
    name: Auto Licht OG Lara Panels
    icon: mdi:auto-fix
  helper_light_auto_switched_o_la_panels:
    name: Helper - Auto Switched - Licht OG Lara Panels
    initial: off
  helper_light_manually_switched_on_o_la_panels:
    name: Helper - Man Switched on - Licht OG Lara Panels
    initial: off
  helper_light_manually_switched_off_o_la_panels:
    name: Helper - Man Switched off - Licht OG Lara Panels
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_o_la_panels
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','05:29',25],
            ['05:30','07:29',40],
            ['07:30','07:59',50],
            ['08:00','08:59',70],
            ['09:00','16:59',90],
            ['17:00','17:59',80],
            ['18:00','19:59',70],
            ['20:00','20:59',50],
            ['21:00','23:59',30] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_o_la_panels
        unit_of_measurement: "%"
        state: >
          {% if is_state('binary_sensor.schlafen_oder_aufwachphase_la', 'on') %}
            {{ int(2) }}
          {% else %}
            {{ states('sensor.helper_light_basic_brightness_o_la_panels') }}
          {% endif %}
        attributes:
          special_brightness: >
            {{ [states('binary_sensor.schlafen_oder_aufwachphase_la')] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_o_la_panels
        unit_of_measurement: "lx"
        state: >
          {% set hours = 
            ['00:00','05:29',20],
            ['05:30','07:29',30],
            ['07:30','08:59',40],
            ['09:00','17:59',50],
            ['18:00','20:59',35],
            ['21:00','23:59',20] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_switching_off_entities_o_la_panels
        unit_of_measurement: "number"
        state: >
          {% if states('switch.la_schlaft') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_la') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_switching_off_entities_o_la_panels') }}
          {% else %}
            {{ [states('switch.la_schlaft'),states('switch.luften_la')] | select('equalto', 'on') | list | count }}
          {% endif %}
    binary_sensor:
      - name: helper_stay_as_you_are_o_la_panels
        state: >
          {{ false }}
      - name: helper_light_trigger_o_la_panels
        state: >
          {% if states('binary_sensor.pm_o_ko_la_raum') in ['unavailable', 'unknown', 'none'] 
             or states('binary_sensor.pm_o_ko_la_tuer') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_o_la_panels') }}
          {% else %}
            {{ is_state('binary_sensor.pm_o_ko_la_raum', 'on')
               or is_state('binary_sensor.pm_o_ko_la_tuer', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_o_la_panels
        state: >
          {% if states('switch.la_schlaft') in ['unavailable', 'unknown', 'none'] 
             or states('switch.bleib_so_la_licht') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_la') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_off_entities_o_la_panels') }}
          {% else %}
            {{ is_state('switch.la_schlaft', 'on')
               or is_state('switch.bleib_so_la_licht', 'on')
               or is_state('switch.luften_la', 'on') }}
          {% endif %}
      - name: helper_light_keeping_on_entities_o_la_panels
        state: >
          {% if states('switch.bleib_so_la_licht') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_on_entities_o_la_panels') }}
          {% else %}
            {{ is_state('switch.bleib_so_la_licht', 'on') }}
          {% endif %}
      - name: helper_light_keeping_fix_entities_o_la_panels
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_o_la_panels
        state: >
          {% if states('sensor.helligkeit_la_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_dark_o_la_panels') }}
          {% else %}
            {{ (states("sensor.helligkeit_la_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_o_la_panels") | float(1)) }}
          {% endif %}
      - name: helper_light_is_too_bright_o_la_panels
        state: >
          {% if states('sensor.helligkeit_la_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_bright_o_la_panels') }}
          {% else %}
            {{ (states("sensor.helligkeit_la_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_o_la_panels") | float(1) + 100 ) }}
          {% endif %}

automation:
  - alias: Licht OG Lara Panels
    id: 'auto_light_o_la_panels'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.panels_la
        automation_switch: input_boolean.automation_switch_light_o_la_panels
        helper_stay_as_you_are: binary_sensor.helper_stay_as_you_are_o_la_panels
        trigger: binary_sensor.helper_light_trigger_o_la_panels
        helper_effective_brightness: sensor.helper_light_effective_brightness_o_la_panels
        helper_basic_brightness: sensor.helper_light_basic_brightness_o_la_panels
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_o_la_panels
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_o_la_panels
        helper_auto_switched: input_boolean.helper_light_auto_switched_o_la_panels
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_o_la_panels
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_o_la_panels
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_o_la_panels
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_o_la_panels
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_o_la_panels
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_o_la_panels