# strings to replace:
#
# friendly name: Licht Keller Speis
# id name: k_speis
# light: light.vorratsraum

input_boolean:
  automation_switch_light_k_speis:
    name: Auto Licht Keller Speis
    icon: mdi:auto-fix
  helper_light_auto_switched_k_speis:
    name: Helper - Auto Switched - Licht Keller Speis
    initial: off
  helper_light_manually_switched_on_k_speis:
    name: Helper - Man Switched on - Licht Keller Speis
    initial: off
  helper_light_manually_switched_off_k_speis:
    name: Helper - Man Switched off - Licht Keller Speis
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_k_speis
        unit_of_measurement: "%"
        state: >
          {{ int(100 )}}
      - name: helper_light_effective_brightness_k_speis
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_k_speis') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_k_speis
        unit_of_measurement: "lx"
        state: >
          {{ int(100) }}
      - name: helper_light_switching_off_entities_k_speis
        unit_of_measurement: "number"
        state: >
          {{ [] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_k_speis
        state: >
          {% if states('binary_sensor.lumi_lumi_sensor_magnet_aq2_83155c04_on_off') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_k_timer_magnetsensor_vorratsraum') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_k_speis') }}
          {% else %}
            {{ is_state('binary_sensor.lumi_lumi_sensor_magnet_aq2_83155c04_on_off', 'on')
               or is_state('binary_sensor.pm_k_timer_magnetsensor_vorratsraum', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_k_speis
        state: >
          {{ False }}
      - name: helper_light_keeping_on_entities_k_speis
        state: >
          {{ False }}
      - name: helper_light_keeping_fix_entities_k_speis
        state: >
          {{ False }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_k_speis
        state: >
          {{ true }}
      - name: helper_light_is_too_bright_k_speis
        state: >
          {{ false }}

automation:
  - alias: Licht Keller Speis
    id: 'auto_light_k_speis'
    description: ''
    trace:
      stored_traces: 5
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.vorratsraum
        automation_switch: input_boolean.automation_switch_light_k_speis
        trigger: binary_sensor.helper_light_trigger_k_speis
        helper_effective_brightness: sensor.helper_light_effective_brightness_k_speis
        helper_basic_brightness: sensor.helper_light_basic_brightness_k_speis
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_k_speis
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_k_speis
        helper_auto_switched: input_boolean.helper_light_auto_switched_k_speis
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_k_speis
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_k_speis
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_k_speis
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_k_speis
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_k_speis
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_k_speis