# strings to replace:
#
# friendly name: Licht OG Arbeitszimmer Fenster
# id name: o_az_fenster
# light: light.ikea_panel_arbeitszimmer_esphome

input_boolean:
  automation_switch_light_o_az_fenster:
    name: Auto Licht OG Arbeitszimmer Fenster
    icon: mdi:auto-fix
  helper_light_auto_switched_o_az_fenster:
    name: Helper - Auto Switched - Licht OG Arbeitszimmer Fenster
    initial: off
  helper_light_manually_switched_on_o_az_fenster:
    name: Helper - Man Switched on - Licht OG Arbeitszimmer Fenster
    initial: off
  helper_light_manually_switched_off_o_az_fenster:
    name: Helper - Man Switched off - Licht OG Arbeitszimmer Fenster
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_o_az_fenster
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','03:59',30],
            ['04:00','06:29',20],
            ['06:30','07:29',40],
            ['07:30','08:59',50],
            ['09:00','17:59',80],
            ['18:00','18:59',50],
            ['19:00','23:59',40] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_o_az_fenster
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_o_az_fenster') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_o_az_fenster
        unit_of_measurement: "lx"
        state: >
          {{ int(35) }}
      - name: helper_light_switching_off_entities_o_az_fenster
        unit_of_measurement: "number"
        state: >
          {{ [states('switch.luften_la'),states('switch.luften_le')] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_o_az_fenster
        state: >
          {% if states('binary_sensor.pm_o_nz') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_o_az_fenster') }}
          {% else %}
            {{ is_state('binary_sensor.pm_o_nz', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_o_az_fenster
        state: >
          {% if states('switch.gaste_schlafen') in ['unavailable', 'unknown', 'none'] 
             or states('switch.luften_la') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_le') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_off_entities_o_az_fenster') }}
          {% else %}
            {{ is_state('switch.gaste_schlafen', 'on')
               or is_state('switch.luften_la', 'on')
               or is_state('switch.luften_le', 'on') }}
          {% endif %}
      - name: helper_light_keeping_on_entities_o_az_fenster
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_o_az_fenster
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_o_az_fenster
        state: >
          {% if states('sensor.helligkeit_nahzimmer_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_dark_o_az_fenster') }}
          {% else %}
            {{ (states("sensor.helligkeit_nahzimmer_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_o_az_fenster") | float(1)) }}
          {% endif %}
      - name: helper_light_is_too_bright_o_az_fenster
        state: >
          {% if states('sensor.helligkeit_nahzimmer_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_bright_o_az_fenster') }}
          {% else %}
            {{ (states("sensor.helligkeit_nahzimmer_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_o_az_fenster") | float(1) + 60 ) }}
          {% endif %}

automation:
  - alias: Licht OG Arbeitszimmer Fenster
    id: 'auto_light_o_az_fenster'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.ikea_panel_arbeitszimmer_esphome
        automation_switch: input_boolean.automation_switch_light_o_az_fenster
        trigger: binary_sensor.helper_light_trigger_o_az_fenster
        helper_effective_brightness: sensor.helper_light_effective_brightness_o_az_fenster
        helper_basic_brightness: sensor.helper_light_basic_brightness_o_az_fenster
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_o_az_fenster
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_o_az_fenster
        helper_auto_switched: input_boolean.helper_light_auto_switched_o_az_fenster
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_o_az_fenster
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_o_az_fenster
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_o_az_fenster
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_o_az_fenster
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_o_az_fenster
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_o_az_fenster
        startup_delay_seconds: 180