# strings to replace:
#
# friendly name: Licht EG Flur Panels
# id name: e_fl_panels
# light: light.panels_flur_eg

input_boolean:
  automation_switch_light_e_fl_panels:
    name: Auto Licht EG Flur Panels
    icon: mdi:auto-fix
  helper_light_auto_switched_e_fl_panels:
    name: Helper - Auto Switched - Licht EG Flur Panels
    initial: off
  helper_light_manually_switched_on_e_fl_panels:
    name: Helper - Man Switched on - Licht EG Flur Panels
    initial: off
  helper_light_manually_switched_off_e_fl_panels:
    name: Helper - Man Switched off - Licht EG Flur Panels
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_fl_panels
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','02:59',35],
            ['03:00','06:29',10],
            ['06:30','08:59',60],
            ['09:00','16:59',80],
            ['17:00','18:29',50],
            ['18:30','23:59',35] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_e_fl_panels
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_e_fl_panels') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_fl_panels
        unit_of_measurement: "lx"
        state: >
          {% set hours = 
            ['00:00','06:29',5],
            ['06:30','08:59',20],
            ['09:00','16:59',25],
            ['17:00','18:59',20],
            ['19:00','22:59',15],
            ['23:00','23:59',10] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_switching_off_entities_e_fl_panels
        unit_of_measurement: "number"
        state: >
          {% if states('switch.majo_schlafen') in ['unavailable', 'unknown', 'none']
             or states('switch.knutschen') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_ez') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_sz') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_switching_off_entities_e_fl_panels') }}
          {% else %}
            {{ [states('switch.majo_schlafen'),states('switch.knutschen'),states('switch.luften_ez'),states('switch.luften_sz')] | select('equalto', 'on') | list | count }}
          {% endif %}
    binary_sensor:
      - name: helper_light_trigger_e_fl_panels
        state: >
          {% if states('binary_sensor.pm_e_fl_treppe_og') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_fl_windfang') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_wf_flur') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_wf_garderobe') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_o_fl_treppe') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_wc') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_ktr_flur') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_ktr_treppe') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_k_fl_2') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_e_fl_panels') }}
          {% else %}
            {{ is_state('binary_sensor.pm_e_fl_treppe_og', 'on')
               or is_state('binary_sensor.pm_e_fl_windfang', 'on')
               or is_state('binary_sensor.pm_e_wf_flur', 'on')
               or is_state('binary_sensor.pm_e_wf_garderobe', 'on')
               or is_state('binary_sensor.pm_o_fl_treppe', 'on')
               or is_state('binary_sensor.pm_e_wc', 'on')
               or is_state('binary_sensor.pm_ktr_flur', 'on')
               or is_state('binary_sensor.pm_ktr_treppe', 'on')
               or is_state('binary_sensor.pm_k_fl_2', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_e_fl_panels
        state: >
          {% if states('switch.majo_schlafen') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.schlafen_oder_aufwachphase_majo') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_ez') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_sz') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_off_entities_e_fl_panels') }}
          {% else %}
            {{ is_state('switch.majo_schlafen', 'on')
              or is_state('binary_sensor.schlafen_oder_aufwachphase_majo', 'on')
              or is_state('switch.luften_ez', 'on')
              or is_state('switch.luften_sz', 'on') }}
          {% endif %}
      - name: helper_light_keeping_on_entities_e_fl_panels
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_e_fl_panels
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_e_fl_panels
        state: >
          {% if states('sensor.helligkeit_flur_eg_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_dark_e_fl_panels') }}
          {% else %}
            {{ (states("sensor.helligkeit_flur_eg_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_fl_panels") | float(1)) }}
          {% endif %}
      - name: helper_light_is_too_bright_e_fl_panels
        state: >
          {% if states('sensor.helligkeit_flur_eg_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_bright_e_fl_panels') }}
          {% else %}
            {{ (states("sensor.helligkeit_flur_eg_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_fl_panels") | float(1) + 100 ) }}
          {% endif %}

automation:
  - alias: Licht EG Flur Panels
    id: 'auto_light_e_fl_panels'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.panels_flur_eg
        automation_switch: input_boolean.automation_switch_light_e_fl_panels
        trigger: binary_sensor.helper_light_trigger_e_fl_panels
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_fl_panels
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_fl_panels
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_fl_panels
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_fl_panels
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_fl_panels
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_fl_panels
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_fl_panels
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_fl_panels
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_fl_panels
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_fl_panels
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_fl_panels
        startup_delay_seconds: 60