# strings to replace:
#
# friendly name: Licht OG Bad Panels
# id name: o_ba_panels
# light: light.panels_bad_og

input_boolean:
  automation_switch_light_o_ba_panels:
    name: Auto Licht OG Bad Panels
    icon: mdi:auto-fix
  helper_light_auto_switched_o_ba_panels:
    name: Helper - Auto Switched - Licht OG Bad Panels
    initial: off
  helper_light_manually_switched_on_o_ba_panels:
    name: Helper - Man Switched on - Licht OG Bad Panels
    initial: off
  helper_light_manually_switched_off_o_ba_panels:
    name: Helper - Man Switched off - Licht OG Bad Panels
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_o_ba_panels
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','05:59',50],
            ['06:00','08:59',75],
            ['09:00','20:59',90],
            ['21:00','23:59',70] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_o_ba_panels
        unit_of_measurement: "%"
        state: >
          {% if is_state('binary_sensor.aufwachphase_kinder', 'on') %}
            {{ int(15) }}
          {% else %}
            {{ states('sensor.helper_light_basic_brightness_o_ba_panels') }}
          {% endif %}
        attributes:
          special_brightness: >
            {{ [states('binary_sensor.aufwachphase_kinder')] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_o_ba_panels
        unit_of_measurement: "lx"
        state: >
          {% set hours = 
            ['00:00','05:59',25],
            ['06:00','23:59',40] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_switching_off_entities_o_ba_panels
        unit_of_measurement: "number"
        state: >
          {{ [states('switch.bad_og_nachtmodus')] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_o_ba_panels
        state: >
          {{ is_state('binary_sensor.pm_o_ba', 'on') }}
      - name: helper_light_keeping_off_entities_o_ba_panels
        state: >
          {{ is_state('switch.bad_og_nachtmodus', 'on') }}
      - name: helper_light_keeping_on_entities_o_ba_panels
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_o_ba_panels
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_o_ba_panels
        state: >
          {{ (states("sensor.helligkeit_bad_og_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_o_ba_panels") | float(1)) }}
      - name: helper_light_is_too_bright_o_ba_panels
        state: >
          {{ (states("sensor.helligkeit_bad_og_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_o_ba_panels") | float(1) + 100 ) }}

automation:
  - alias: Licht OG Bad Panels
    id: 'auto_light_o_ba_panels'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.panels_bad_og
        automation_switch: input_boolean.automation_switch_light_o_ba_panels
        trigger: binary_sensor.helper_light_trigger_o_ba_panels
        helper_effective_brightness: sensor.helper_light_effective_brightness_o_ba_panels
        helper_basic_brightness: sensor.helper_light_basic_brightness_o_ba_panels
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_o_ba_panels
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_o_ba_panels
        helper_auto_switched: input_boolean.helper_light_auto_switched_o_ba_panels
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_o_ba_panels
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_o_ba_panels
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_o_ba_panels
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_o_ba_panels
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_o_ba_panels
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_o_ba_panels