# strings to replace:
#
# friendly name: Licht EG Schlafzimmer Bettbeleuchtung
# id name: e_sz_bettbeleuchtung
# light: light.bettbeleuchtung

input_boolean:
  automation_switch_light_e_sz_bettbeleuchtung:
    name: Auto Licht EG Schlafzimmer Bettbeleuchtung
    icon: mdi:auto-fix
  helper_light_auto_switched_e_sz_bettbeleuchtung:
    name: Helper - Auto Switched - Licht EG Schlafzimmer Bettbeleuchtung
    initial: off
  helper_light_manually_switched_on_e_sz_bettbeleuchtung:
    name: Helper - Man Switched on - Licht EG Schlafzimmer Bettbeleuchtung
    initial: off
  helper_light_manually_switched_off_e_sz_bettbeleuchtung:
    name: Helper - Man Switched off - Licht EG Schlafzimmer Bettbeleuchtung
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_sz_bettbeleuchtung
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','06:29',50],
            ['06:30','08:59',70],
            ['20:00','23:59',50] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_e_sz_bettbeleuchtung
        unit_of_measurement: "%"
        state: >
          {% if is_state('binary_sensor.schlafen_oder_aufwachphase_majo', 'on') %}
            {{ int(40) }}
          {% else %}
            {{ states('sensor.helper_light_basic_brightness_e_sz_bettbeleuchtung') }}
          {% endif %}
        attributes:
          special_brightness: >
            {{ [states('binary_sensor.schlafen_oder_aufwachphase_majo')] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_sz_bettbeleuchtung
        unit_of_measurement: "lx"
        state: >
          {{ int(50) }}
      - name: helper_light_switching_off_entities_e_sz_bettbeleuchtung
        unit_of_measurement: "number"
        state: >
          {{ [states('switch.luften_sz')] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_e_sz_bettbeleuchtung
        state: >
          {{ is_state('binary_sensor.pm_e_sz_bett', 'on')
             or is_state('binary_sensor.pm_e_sz_gang', 'on') }}
      - name: helper_light_keeping_off_entities_e_sz_bettbeleuchtung
        state: >
          {% set h = now().hour | int(0) %}
          {{ is_state('switch.luften_sz', 'on') 
             or (h >= 9 and h <= 16) }}
      - name: helper_light_keeping_on_entities_e_sz_bettbeleuchtung
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_e_sz_bettbeleuchtung
        state: >
          {{ is_state('switch.majo_schlafen', 'on')
             or is_state('switch.knutschen', 'on') }}
        attributes:
          brightness: >
            {% if is_state('switch.knutschen', 'on') %}
              {{ int(70) }}
            {% elif is_state('switch.majo_schlafen', 'on') %}
              {{ int(3) }}
            {% else %}
              {{ int(0) }}
            {% endif %}
      - name: helper_light_is_too_dark_e_sz_bettbeleuchtung
        state: >
          {{ (states("sensor.helligkeit_schlafzimmer_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_sz_bettbeleuchtung") | float(1)) }}
      - name: helper_light_is_too_bright_e_sz_bettbeleuchtung
        state: >
          {{ (states("sensor.helligkeit_schlafzimmer_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_sz_bettbeleuchtung") | float(1) + 100 ) }}

automation:
  - alias: Licht EG Schlafzimmer Bettbeleuchtung
    id: 'auto_light_e_sz_bettbeleuchtung'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.bettbeleuchtung
        automation_switch: input_boolean.automation_switch_light_e_sz_bettbeleuchtung
        trigger: binary_sensor.helper_light_trigger_e_sz_bettbeleuchtung
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_sz_bettbeleuchtung
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_sz_bettbeleuchtung
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_sz_bettbeleuchtung
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_sz_bettbeleuchtung
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_sz_bettbeleuchtung
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_sz_bettbeleuchtung
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_sz_bettbeleuchtung
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_sz_bettbeleuchtung
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_sz_bettbeleuchtung
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_sz_bettbeleuchtung
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_sz_bettbeleuchtung
        transition_time: 1