# strings to replace:
#
# friendly name: Licht EG Flur Stehlampe unten
# id name: e_fl_stehlampe_unten
# light: light.innr_e27_rgb_flur_eg_unten_level_light_color_on_off

input_boolean:
  automation_switch_light_e_fl_stehlampe_unten:
    name: Auto Licht EG Flur Stehlampe unten
    icon: mdi:auto-fix
  helper_light_auto_switched_e_fl_stehlampe_unten:
    name: Helper - Auto Switched - Licht EG Flur Stehlampe unten
    initial: off
  helper_light_manually_switched_on_e_fl_stehlampe_unten:
    name: Helper - Man Switched on - Licht EG Flur Stehlampe unten
    initial: off
  helper_light_manually_switched_off_e_fl_stehlampe_unten:
    name: Helper - Man Switched off - Licht EG Flur Stehlampe unten
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_fl_stehlampe_unten
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','06:29',20],
            ['06:30','08:59',40],
            ['09:00','16:59',40],
            ['17:00','18:59',40],
            ['19:00','23:59',20] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
        attributes:
          color: >
            {% set colormap = { 'rot':[255,0,0],'grün':[0,255,0],'blau':[0,0,255],'orange':[255,127,0],'pink':[255,0,127],'lila':[255,0,255],'violett':[127,0,255],'gelb':[255,255,0],'gold':[255,215,0],'hellblau':[0,127,255],'türkis':[0,255,255],'gelbgrün':[127,255,0],'weiß':[255,255,255]} %}
            {% set hours = 
              ['00:00','06:29',colormap['rot']],
              ['06:30','08:59',colormap['rot']],
              ['09:00','16:59',colormap['lila']],
              ['17:00','18:59',colormap['rot']],
              ['19:00','23:59',colormap['rot']] %}
            {% set t = states('sensor.time').replace(':','')|int %}
            {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
                {{h[2]}}
            {% endfor %}
      - name: helper_light_effective_brightness_e_fl_stehlampe_unten
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_e_fl_stehlampe_unten') }}
        attributes:
          color: >
            {{ state_attr('sensor.helper_light_basic_brightness_e_fl_stehlampe_unten','color') }}
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_fl_stehlampe_unten
        unit_of_measurement: "lx"
        state: >
          {{ int(50) }}
      - name: helper_light_switching_off_entities_e_fl_stehlampe_unten
        unit_of_measurement: "number"
        state: >
          {% if states('switch.majo_schlafen') in ['unavailable', 'unknown', 'none']
             or states('switch.knutschen') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_ez') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_sz') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_switching_off_entities_e_fl_stehlampe_unten') }}
          {% else %}
            {{ [states('switch.majo_schlafen'),states('switch.knutschen'),states('switch.luften_ez'),states('switch.luften_sz')] | select('equalto', 'on') | list | count }}
          {% endif %}
    binary_sensor:
      - name: helper_light_trigger_e_fl_stehlampe_unten
        state: >
          {% if states('binary_sensor.pm_e_fl_treppe_og') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_fl_windfang') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_wf_flur') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_wf_garderobe') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_o_fl_treppe') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_wc') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_sz_gang') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_ktr_flur') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_ktr_treppe') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_k_fl_2') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_e_fl_stehlampe_unten') }}
          {% else %}
            {{ is_state('binary_sensor.pm_e_fl_treppe_og', 'on')
               or is_state('binary_sensor.pm_e_fl_windfang', 'on')
               or is_state('binary_sensor.pm_e_wf_flur', 'on')
               or is_state('binary_sensor.pm_e_wf_garderobe', 'on')
               or is_state('binary_sensor.pm_o_fl_treppe', 'on')
               or is_state('binary_sensor.pm_e_wc', 'on')
               or is_state('binary_sensor.pm_e_sz_gang', 'on')
               or is_state('binary_sensor.pm_ktr_flur', 'on')
               or is_state('binary_sensor.pm_ktr_treppe', 'on')
               or is_state('binary_sensor.pm_k_fl_2', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_e_fl_stehlampe_unten
        state: >
          {% if states('switch.majo_schlafen') in ['unavailable', 'unknown', 'none']
             or states('switch.knutschen') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_ez') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_sz') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_off_entities_e_fl_stehlampe_unten') }}
          {% else %}
            {{ is_state('switch.majo_schlafen', 'on')
              or is_state('switch.knutschen', 'on')
              or is_state('switch.luften_ez', 'on')
              or is_state('switch.luften_sz', 'on') }}
          {% endif %}
      - name: helper_light_keeping_on_entities_e_fl_stehlampe_unten
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_e_fl_stehlampe_unten
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
          color: >
            {% set colormap = { 'rot':[255,0,0],'grün':[0,255,0],'blau':[0,0,255],'orange':[255,127,0],'pink':[255,0,127],'lila':[255,0,255],'violett':[127,0,255],'gelb':[255,255,0],'gold':[255,215,0],'hellblau':[0,127,255],'türkis':[0,255,255],'gelbgrün':[127,255,0],'weiß':[255,255,255]} %}
            {{ colormap['orange'] }}
      - name: helper_light_is_too_dark_e_fl_stehlampe_unten
        state: >
          {% if states('sensor.helligkeit_flur_eg_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_dark_e_fl_stehlampe_unten') }}
          {% else %}
            {{ (states("sensor.helligkeit_flur_eg_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_fl_stehlampe_unten") | float(1)) }}
          {% endif %}
      - name: helper_light_is_too_bright_e_fl_stehlampe_unten
        state: >
          {% if states('sensor.helligkeit_flur_eg_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_bright_e_fl_stehlampe_unten') }}
          {% else %}
            {{ (states("sensor.helligkeit_flur_eg_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_fl_stehlampe_unten") | float(1) + 100 ) }}
          {% endif %}

automation:
  - alias: Licht EG Flur Stehlampe unten
    id: 'auto_light_e_fl_stehlampe_unten'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.innr_e27_rgb_flur_eg_unten_level_light_color_on_off
        automation_switch: input_boolean.automation_switch_light_e_fl_stehlampe_unten
        trigger: binary_sensor.helper_light_trigger_e_fl_stehlampe_unten
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_fl_stehlampe_unten
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_fl_stehlampe_unten
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_fl_stehlampe_unten
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_fl_stehlampe_unten
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_fl_stehlampe_unten
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_fl_stehlampe_unten
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_fl_stehlampe_unten
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_fl_stehlampe_unten
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_fl_stehlampe_unten
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_fl_stehlampe_unten
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_fl_stehlampe_unten
        startup_delay_seconds: 180