# strings to replace:
#
# friendly name: Licht EG Schlafzimmer Panels
# id name: e_sz_panels
# light: light.panels_schlafzimmer

input_boolean:
  automation_switch_light_e_sz_panels:
    name: Auto Licht EG Schlafzimmer Panels
    icon: mdi:auto-fix
  helper_light_auto_switched_e_sz_panels:
    name: Helper - Auto Switched - Licht EG Schlafzimmer Panels
    initial: off
  helper_light_manually_switched_on_e_sz_panels:
    name: Helper - Man Switched on - Licht EG Schlafzimmer Panels
    initial: off
  helper_light_manually_switched_off_e_sz_panels:
    name: Helper - Man Switched off - Licht EG Schlafzimmer Panels
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_sz_panels
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','06:29',30],
            ['06:30','09:29',45],
            ['09:30','16:59',90],
            ['17:00','17:59',80],
            ['18:00','18:59',70],
            ['19:00','21:59',60],
            ['22:00','23:59',30] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_e_sz_panels
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.helper_light_basic_brightness_e_sz_panels') }}
        attributes:
          special_brightness: >
            {{ [] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_sz_panels
        unit_of_measurement: "lx"
        state: >
          {% set hours = 
            ['00:00','04:29',5],
            ['04:30','22:59',10],
            ['23:00','23:59',5] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_switching_off_entities_e_sz_panels
        unit_of_measurement: "number"
        state: >
          {% if states('switch.majo_schlafen') in ['unavailable', 'unknown', 'none']
             or states('switch.knutschen') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_sz') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_switching_off_entities_e_sz_panels') }}
          {% else %}
            {{ [states('switch.majo_schlafen'),states('switch.knutschen'),states('switch.luften_sz')] | select('equalto', 'on') | list | count }}
          {% endif %}
    binary_sensor:
      - name: helper_light_trigger_e_sz_panels
        state: >
          {% if states('binary_sensor.pm_e_sz_bett') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.pm_e_sz_gang') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_e_sz_panels') }}
          {% else %}
            {{ is_state('binary_sensor.pm_e_sz_bett', 'on')
               or is_state('binary_sensor.pm_e_sz_gang', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_e_sz_panels
        state: >
          {% if states('switch.majo_schlafen') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.schlafen_oder_aufwachphase_majo') in ['unavailable', 'unknown', 'none']
             or states('binary_sensor.schlafen_oder_licht_noch_aus_lassen_majo') in ['unavailable', 'unknown', 'none']
             or states('switch.knutschen') in ['unavailable', 'unknown', 'none']
             or states('switch.bleib_so_sz_licht') in ['unavailable', 'unknown', 'none']
             or states('switch.luften_sz') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_off_entities_e_sz_panels') }}
          {% else %}
            {{ is_state('switch.majo_schlafen', 'on') 
              or is_state('binary_sensor.schlafen_oder_aufwachphase_majo', 'on') 
              or is_state('binary_sensor.schlafen_oder_licht_noch_aus_lassen_majo', 'on') 
              or is_state('switch.knutschen', 'on') 
              or is_state('switch.bleib_so_sz_licht', 'on') 
              or is_state('switch.luften_sz', 'on') }}
          {% endif %}
      - name: helper_light_keeping_on_entities_e_sz_panels
        state: >
          {% if states('switch.bleib_so_sz_licht') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_keeping_on_entities_e_sz_panels') }}
          {% else %}
            {{ is_state('switch.bleib_so_sz_licht', 'on') }}
          {% endif %}
      - name: helper_light_keeping_fix_entities_e_sz_panels
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_e_sz_panels
        state: >
          {% if states('sensor.helligkeit_schlafzimmer_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_dark_e_sz_panels') }}
          {% else %}
            {{ (states("sensor.helligkeit_schlafzimmer_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_sz_panels") | float(1)) }}
          {% endif %}
      - name: helper_light_is_too_bright_e_sz_panels
        state: >
          {% if states('sensor.helligkeit_schlafzimmer_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_bright_e_sz_panels') }}
          {% else %}
            {{ (states("sensor.helligkeit_schlafzimmer_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_sz_panels") | float(1) + 100 ) }}
          {% endif %}

automation:
  - alias: Licht EG Schlafzimmer Panels
    id: 'auto_light_e_sz_panels'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.panels_schlafzimmer
        automation_switch: input_boolean.automation_switch_light_e_sz_panels
        trigger: binary_sensor.helper_light_trigger_e_sz_panels
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_sz_panels
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_sz_panels
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_sz_panels
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_sz_panels
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_sz_panels
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_sz_panels
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_sz_panels
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_sz_panels
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_sz_panels
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_sz_panels
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_sz_panels