# strings to replace:
#
# friendly name: Licht EG WC Panel
# id name: e_wc_panel
# light: light.panels_wc

input_boolean:
  automation_switch_light_e_wc_panel:
    name: Auto Licht EG WC Panel
    icon: mdi:auto-fix
  helper_light_auto_switched_e_wc_panel:
    name: Helper - Auto Switched - Licht EG WC Panel
    initial: off
  helper_light_manually_switched_on_e_wc_panel:
    name: Helper - Man Switched on - Licht EG WC Panel
    initial: off
  helper_light_manually_switched_off_e_wc_panel:
    name: Helper - Man Switched off - Licht EG WC Panel
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_e_wc_panel
        unit_of_measurement: "%"
        state: >
          {% set hours = 
            ['00:00','08:59',20],
            ['09:00','16:59',80],
            ['17:00','18:29',70],
            ['18:30','19:59',60],
            ['20:00','23:59',20] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_effective_brightness_e_wc_panel
        unit_of_measurement: "%"
        state: >
          {% if is_state('binary_sensor.nachtmodus_wc', 'on') %}
            {{ int(5) }}
          {% else %}
            {{ states('sensor.helper_light_basic_brightness_e_wc_panel') }}
          {% endif %}
        attributes:
          special_brightness: >
            {{ [states('binary_sensor.nachtmodus_wc')] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_e_wc_panel
        unit_of_measurement: "lx"
        state: >
          {% set hours = 
            ['00:00','04:59',5],
            ['05:00','06:29',10],
            ['06:30','08:59',20],
            ['09:00','16:59',25],
            ['17:00','18:59',20],
            ['19:00','22:59',10],
            ['23:00','23:59',5] %}
          {% set t = states('sensor.time').replace(':','')|int %}
          {% for h in hours if (h[0].replace(':','')|int) <= t <= (h[1].replace(':','')|int) %}
              {{h[2]}}
          {% endfor %}
      - name: helper_light_switching_off_entities_e_wc_panel
        unit_of_measurement: "number"
        state: >
          {{ [] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_e_wc_panel
        state: >
          {% if states('binary_sensor.pm_e_wc') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_e_wc_panel') }}
          {% else %}
            {{ is_state('binary_sensor.pm_e_wc', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_e_wc_panel
        state: >
          {{ false }}
      - name: helper_light_keeping_on_entities_e_wc_panel
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_e_wc_panel
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_e_wc_panel
        state: >
          {{ (states("sensor.helligkeit_wc_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_e_wc_panel") | float(1)) }}
      - name: helper_light_is_too_bright_e_wc_panel
        state: >
          {{ (states("sensor.helligkeit_wc_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_e_wc_panel") | float(1) + 120 ) }}

automation:
  - alias: Licht EG WC Panel
    id: 'auto_light_e_wc_panel'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.panels_wc
        automation_switch: input_boolean.automation_switch_light_e_wc_panel
        trigger: binary_sensor.helper_light_trigger_e_wc_panel
        helper_effective_brightness: sensor.helper_light_effective_brightness_e_wc_panel
        helper_basic_brightness: sensor.helper_light_basic_brightness_e_wc_panel
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_e_wc_panel
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_e_wc_panel
        helper_auto_switched: input_boolean.helper_light_auto_switched_e_wc_panel
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_e_wc_panel
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_e_wc_panel
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_e_wc_panel
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_e_wc_panel
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_e_wc_panel
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_e_wc_panel
        startup_delay_seconds: 60