# strings to replace:
#
# friendly name: Licht OG Bad Spiegel oben
# id name: o_ba_spiegel_oben
# light: light.led_auf_spiegelschrank_bad_og

input_boolean:
  automation_switch_light_o_ba_spiegel_oben:
    name: Auto Licht OG Bad Spiegel oben
    icon: mdi:auto-fix
  helper_light_auto_switched_o_ba_spiegel_oben:
    name: Helper - Auto Switched - Licht OG Bad Spiegel oben
    initial: off
  helper_light_manually_switched_on_o_ba_spiegel_oben:
    name: Helper - Man Switched on - Licht OG Bad Spiegel oben
    initial: off
  helper_light_manually_switched_off_o_ba_spiegel_oben:
    name: Helper - Man Switched off - Licht OG Bad Spiegel oben
    initial: off

template:
  - sensor:
      - name: helper_light_basic_brightness_o_ba_spiegel_oben
        unit_of_measurement: "%"
        state: >
          {{ int(90) }}
      - name: helper_light_effective_brightness_o_ba_spiegel_oben
        unit_of_measurement: "%"
        state: >
          {% if is_state('switch.bad_og_nachtmodus', 'on') %}
            {{ int(13) }}
          {% elif is_state('binary_sensor.aufwachphase_kinder', 'on') %}
            {{ int(65) }}
          {% else %}
            {{ states('sensor.helper_light_basic_brightness_o_ba_spiegel_oben') }}
          {% endif %}
        attributes:
          special_brightness: >
            {{ [states('switch.bad_og_nachtmodus'),states('binary_sensor.aufwachphase_kinder')] | select('equalto', 'on') | list | count }}
      - name: helper_light_min_illuminance_o_ba_spiegel_oben
        unit_of_measurement: "lx"
        state: >
          {{ int(90) }}
      - name: helper_light_switching_off_entities_o_ba_spiegel_oben
        unit_of_measurement: "number"
        state: >
          {{ [] | select('equalto', 'on') | list | count }}
    binary_sensor:
      - name: helper_light_trigger_o_ba_spiegel_oben
        state: >
          {% if states('binary_sensor.pm_o_ba') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_trigger_o_ba_spiegel_oben') }}
          {% else %}
            {{ is_state('binary_sensor.pm_o_ba', 'on') }}
          {% endif %}
      - name: helper_light_keeping_off_entities_o_ba_spiegel_oben
        state: >
          {{ false }}
      - name: helper_light_keeping_on_entities_o_ba_spiegel_oben
        state: >
          {{ false }}
      - name: helper_light_keeping_fix_entities_o_ba_spiegel_oben
        state: >
          {{ false }}
        attributes:
          brightness: >
            {{ int(0) }}
      - name: helper_light_is_too_dark_o_ba_spiegel_oben
        state: >
          {% if states('sensor.helligkeit_bad_og_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_dark_o_ba_spiegel_oben') }}
          {% else %}
            {{ (states("sensor.helligkeit_bad_og_pm") | float(0)) < (states("sensor.helper_light_min_illuminance_o_ba_spiegel_oben") | float(1)) }}
          {% endif %}
      - name: helper_light_is_too_bright_o_ba_spiegel_oben
        state: >
          {% if states('sensor.helligkeit_bad_og_pm') in ['unavailable', 'unknown', 'none'] %}
            {{ states('binary_sensor.helper_light_is_too_bright_o_ba_spiegel_oben') }}
          {% else %}
            {{ (states("sensor.helligkeit_bad_og_pm") | float(0)) > (states("sensor.helper_light_min_illuminance_o_ba_spiegel_oben") | float(1) + 100 ) }}
          {% endif %}

automation:
  - alias: Licht OG Bad Spiegel oben
    id: 'auto_light_o_ba_spiegel_oben'
    description: ''
    trace:
      stored_traces: 10
    use_blueprint:
      path: /config/blueprints/light_automation.yaml
      input:
        light_entity: light.led_auf_spiegelschrank_bad_og
        automation_switch: input_boolean.automation_switch_light_o_ba_spiegel_oben
        trigger: binary_sensor.helper_light_trigger_o_ba_spiegel_oben
        helper_effective_brightness: sensor.helper_light_effective_brightness_o_ba_spiegel_oben
        helper_basic_brightness: sensor.helper_light_basic_brightness_o_ba_spiegel_oben
        helper_is_too_dark: binary_sensor.helper_light_is_too_dark_o_ba_spiegel_oben
        helper_is_too_bright: binary_sensor.helper_light_is_too_bright_o_ba_spiegel_oben
        helper_auto_switched: input_boolean.helper_light_auto_switched_o_ba_spiegel_oben
        helper_manually_switched_on: input_boolean.helper_light_manually_switched_on_o_ba_spiegel_oben
        helper_manually_switched_off: input_boolean.helper_light_manually_switched_off_o_ba_spiegel_oben
        helper_switching_off_entities: sensor.helper_light_switching_off_entities_o_ba_spiegel_oben
        helper_keeping_on_entities: binary_sensor.helper_light_keeping_on_entities_o_ba_spiegel_oben
        helper_keeping_off_entities: binary_sensor.helper_light_keeping_off_entities_o_ba_spiegel_oben
        helper_keeping_fix_entities: binary_sensor.helper_light_keeping_fix_entities_o_ba_spiegel_oben
        startup_delay_seconds: 60