sensor:
  - platform: min_max
    type: max
    name: Stellwert Heizung aktueller MaxWert
    entity_ids:
      - sensor.stellwert_heizung_bad_eg
      - sensor.stellwert_heizung_bad_og
      - sensor.stellwert_heizung_esszimmer
      - sensor.stellwert_heizung_flur_og
      - sensor.stellwert_heizung_gastezimmer
      - sensor.stellwert_heizung_kuche
      - sensor.stellwert_heizung_la
      - sensor.stellwert_heizung_le
      - sensor.stellwert_heizung_nahzimmer
      - sensor.stellwert_heizung_schlafzimmer
      - sensor.stellwert_heizung_windfang_wc
      - sensor.stellwert_heizung_wohnzimmer
  - platform: statistics
    name: Stellwert Heizung Zeitverlauf Mean
    entity_id: sensor.stellwert_heizung_aktueller_maxwert
    sampling_size: 2000
    state_characteristic: average_step
    max_age:
      minutes: 30

template: 
  - sensor:
      - unique_id: stellwert_heizung_zeitverlauf_mean_hold
        # name: change entity_id in UI after creation
        unit_of_measurement: "°C"
        device_class: temperature
        state: >
          {% set measurement = states('sensor.stellwert_heizung_zeitverlauf_mean') | float(-100) | round(1) %}
          {% if measurement > -100 %}
          {{ measurement }}
          {% else %}
            {% if (now() - states.sensor.stellwert_heizung_zeitverlauf_mean.last_updated) < timedelta( hours = 24) %}
              {{ states('sensor.stellwert_heizung_zeitverlauf_mean_hold') }}
            {% else %}
              {{ 'unknown' }}
            {% endif %}
          {% endif %}
        attributes:
          friendly_name: "Stellwert Heizung Zeitverlauf Mean Hold"