sensor:
  - platform: derivative
    source: sensor.temp_esszimmer_pm
    name: Steigung Temp. EZ
    unit_time: h
    time_window: "02:30:00"

template:
  - sensor:
      - name: helper_heating_ez_shift_kelvin_limited
        unit_of_measurement: "K/h"
        state: >
          {% set multipicator = 6 %}
          {% set limit_upper = 1.0 %}
          {% set limit_lower = -1.0 %}
          {% set shift_kelvin = -1*multipicator*(states('sensor.steigung_temp_ez_median') | float(0)) %}
          {% if shift_kelvin > limit_upper %}
            {{ limit_upper }}
          {% elif shift_kelvin < limit_lower %}
            {{ limit_lower }}
          {% else %}
            {{ shift_kelvin }}
          {% endif %}