template: 
  - sensor:
      - unique_id: temp_pool
        # name: change entity_id in UI after creation
        unit_of_measurement: "°C"
        device_class: temperature
        state: >
          {{ states('sensor.temp_0xa30317605abeff28_d1_pro_1') | float(0) | round(1) }}
        attributes:
          friendly_name: "Pool-Temperatur"
    binary_sensor:
      - unique_id: pool_chlorinator_lauft
        state: >
          {% if (states('sensor.0xa4c1381ed732dbe2_power') | float(0) > 10) %}
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}
        attributes:
          friendly_name: "Pool - Chlorinator läuft"
      - unique_id: pool_pumpe_lauft
        state: >
          {% if (states('sensor.0xa4c1380e0ea5cb89_power') | float(0) > 50) %}
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}
        attributes:
          friendly_name: "Pool - Pumpe läuft"
      - unique_id: pool_heizung_lauft
        state: >
          {% if (states('sensor.0xa4c138b64253ef10_power') | float(0) > 1000) %}
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}
        attributes:
          friendly_name: "Pool - Heizung läuft"

input_number:
  zieltemperatur_pool:
    name: Zieltemperatur Pool
    min: 20
    max: 30
    step: 0.5
    icon: mdi:coolant-temperature

input_boolean:
  pool_heizung_wenn_pv_strom_uebrig:
    name: Pool Heizung wenn PV-Strom übrig
    icon: mdi:auto-fix
  pool_heizung_sobald_pv_strom:
    name: Pool Heizung sobald PV-Strom da
    icon: mdi:auto-fix
  pool_heizung_auch_bezahlstrom:
    name: Pool Heizung auch wenn Bezahlstrom
    icon: mdi:auto-fix

automation:
  - id: '447d4b8d-3f10-41ca-b3a0-b5ad292d4995'
    alias: Pool - Pumpe
    description: ''
    mode: queued
    trigger:
      - platform: time
        at: "10:00:00"
        id: pumpe_an
      - platform: time
        at: "10:10:00"
        id: pumpe_an
      - platform: time
        at: "19:00:00"
        id: pumpe_aus
      - platform: time
        at: "19:10:00"
        id: pumpe_aus
    condition: []
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: pumpe_an
          sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.0xa4c1380e0ea5cb89
        - conditions:
          - condition: trigger
            id: pumpe_aus
          sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.0xa4c1380e0ea5cb89
  - id: '4fc21835-8338-4990-8f77-4a92682cc758'
    alias: Pool - Chlorinator überwachen
    description: ''
    mode: queued
    trigger:
      - platform: time
        at: "11:00:05"
        id: check_if_running
      - platform: time
        at: "15:00:05"
        id: check_if_running
      - platform: time
        at: "18:00:05"
        id: check_if_running
    condition: []
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: check_if_running
          - condition: state
            entity_id: binary_sensor.pool_chlorinator_lauft
            state: "off"
          sequence:
          - service: notify.telegram_jo
            data:
              message: 'Chlorinator läuft nicht'
  - id: 'd431661c-bc02-447b-bbda-8df1d72afedc'
    alias: Pool - Heizung vergessen
    description: ''
    mode: queued
    trigger:
      - platform: time
        at: "21:00:01"
        id: heizung_vergessen
    condition: []
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: heizung_vergessen
          sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.0xa4c138b64253ef10