template: 
  - sensor:
      - unique_id: temp_pool
        # name: change entity_id in UI after creation
        unit_of_measurement: "°C"
        device_class: temperature
        state: >
          {% set measurement = states('sensor.pool_temperatur_gefiltert') | float(-100) | round(1) %}
          {% if measurement > -100 %}
          {{ measurement }}
          {% else %}
            {% if (now() - states.sensor.0x00124b0018e211d7_temperature_l1.last_updated) < timedelta( hours = 1) %}
              {{ states('sensor.temp_pool') }}
            {% else %}
              {{ 'unknown' }}
            {% endif %}
          {% endif %}
        attributes:
          friendly_name: "Pool-Temperatur"
    binary_sensor:
      - unique_id: pool_chlorinator_lauft
        state: >
          {% if (states('sensor.0xa4c1381ed732dbe2_power') | float(0) > 10) %}
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}
        attributes:
          friendly_name: "Pool - Chlorinator läuft"
      - unique_id: pool_pumpe_lauft
        state: >
          {% if (states('sensor.0xa4c138a1288e6b94_power') | float(0) > 50) %}
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}
        attributes:
          friendly_name: "Pool - Pumpe läuft"
      - unique_id: pool_heizung_lauft
        state: >
          {% if (states('sensor.0xa4c138b64253ef10_power') | float(0) > 100) %}
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}
        attributes:
          friendly_name: "Pool - Heizung läuft"
      - unique_id: pool_auto_heizung_freigabe
        state: >
          {% set einspeisung_ohne_poolheizung = -1*(states('sensor.leistung_netz_letzte_3_min_durchschnitt') | float(0)) + (states('sensor.0xa4c138b64253ef10_power') | float(0)) %}
          {% if is_state('input_boolean.pool_heizung_auch_bezahlstrom','on') %}
            {{ true }}
          {% elif is_state('input_boolean.pool_heizung_sobald_pv_strom','on') and (einspeisung_ohne_poolheizung > 1000) %}
            {{ true }}
          {% elif is_state('input_boolean.pool_heizung_wenn_pv_strom_uebrig','on') and (einspeisung_ohne_poolheizung > 6000) %}
            {{ true }}          
          {% else %}
            {{ false }}
          {% endif %}
        attributes:
          friendly_name: "Pool - Heizungsautomatik Freigabe"
      - unique_id: pool_auto_heizung_noetig
        state: >
         {{
          (states('sensor.temp_pool') | float(0)) <
          ((states('input_number.zieltemperatur_pool') | float(0))
          + (0.2 if is_state('binary_sensor.pool_auto_heizung_noetig', 'on') else 0)
          - (0.2 if is_state('binary_sensor.pool_auto_heizung_noetig', 'off') else 0))
         }}
        attributes:
          friendly_name: "Pool - Heizungsautomatik nötig"
      - unique_id: pool_auto_heizung_heize_jetzt
        state: >
          {% if is_state('binary_sensor.pool_auto_heizung_noetig','on') and is_state('binary_sensor.pool_auto_heizung_freigabe','on') %}
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}
        attributes:
          friendly_name: "Pool - Heizungsautomatik heize jetzt"
      - unique_id: pool_pumpe_pumpe_jetzt
        state: >
          {% set h = now().hour | int(0) %}
          {% if (h >= 10 and h <= 18) or is_state('switch.0xa4c138b64253ef10','on') %}
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}
        attributes:
          friendly_name: "Pool - Pumpe pumpe jetzt"
      - unique_id: pool_auto_heizung_hat_freigabe_heizt_aber_nicht
        state: >
         {{
          is_state('switch.0xa4c138b64253ef10', 'on') and (states('sensor.0xa4c138b64253ef10_power') | float(0) < 100)
         }}
        attributes:
          friendly_name: "Pool - Heizungsautomatik Hat Freigabe heizt aber nicht"

input_number:
  zieltemperatur_pool:
    name: Zieltemperatur Pool
    min: 20
    max: 30
    step: 0.5
    icon: mdi:coolant-temperature

input_boolean:
  pool_heizung_wenn_pv_strom_uebrig:
    name: Pool Heizung wenn PV-Strom übrig
    icon: mdi:weather-sunny
  pool_heizung_sobald_pv_strom:
    name: Pool Heizung sobald PV-Strom da
    icon: mdi:weather-partly-cloudy
  pool_heizung_auch_bezahlstrom:
    name: Pool Heizung auch wenn Bezahlstrom
    icon: mdi:cash-multiple
  chlorinator_sonderschicht_geplant:
    name: Chlor. Sonderschicht 23 Uhr
    icon: mdi:timer-sand

input_button:
  chlorinator_sonderschicht_jetzt:
    name: Chlor. Sonderschicht jetzt
    icon: mdi:arm-flex-outline

sensor:
  - platform: history_stats
    name: pool_pumpe_an_heute
    entity_id: binary_sensor.pool_pumpe_lauft
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: pool_chlorinator_an_heute
    entity_id: binary_sensor.pool_chlorinator_lauft
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: pool_heizung_an_heute
    entity_id: binary_sensor.pool_heizung_lauft
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

automation:
  - id: '447d4b8d-3f10-41ca-b3a0-b5ad292d4995'
    alias: Pool - Pumpe
    description: ''
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.pool_pumpe_pumpe_jetzt
        to: "on"
        id: pumpe_an
      - platform: state
        entity_id: binary_sensor.pool_pumpe_pumpe_jetzt
        to: "off"
        id: pumpe_aus
    condition: []
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: pumpe_an
          sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.0xa4c138a1288e6b94
        - conditions:
          - condition: trigger
            id: pumpe_aus
          sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.0xa4c138a1288e6b94
  - id: '4fc21835-8338-4990-8f77-4a92682cc758'
    alias: Pool - Chlorinator überwachen
    description: ''
    mode: queued
    trigger:
      - platform: time
        at: "11:00:05"
        id: check_if_running
      - platform: time
        at: "15:00:05"
        id: check_if_running
      - platform: time
        at: "18:00:05"
        id: check_if_running
    condition: []
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: check_if_running
          - condition: state
            entity_id: binary_sensor.pool_chlorinator_lauft
            state: "off"
          sequence:
          - service: notify.telegram_jo
            data:
              message: 'Chlorinator läuft nicht'
  - id: '2825ff19-21fc-4e2a-bdf5-910e18de87ec'
    alias: Pool - Auto-Starte Chlorinator
    description: ''
    mode: queued
    trigger:
      - platform: time
        at: "10:29:00"
        id: check_if_running
    condition: []
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.0xa4c1381ed732dbe2
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - service: switch.turn_on
        target:
          entity_id: switch.0xa4c1381ed732dbe2
      - service: notify.telegram_jo
        data:
          message: 'Habe den Chlorinator gestartet'
      - service: automation.turn_off
        target:
          entity_id: automation.pool_auto_starte_chlorinator
  - id: '4756a050-7b11-42d4-b9e5-97c1994b28e6'
    alias: Pool - Chlorinator Sonderschicht
    description: ''
    mode: queued
    trigger:
      - platform: time
        at: "22:59:00"
        id: check_sonderschicht_geplant
      - platform: state
        entity_id: input_button.chlorinator_sonderschicht_jetzt
        id: sonderschicht_jetzt
    condition:
      condition: or
      conditions:
        - condition: trigger
          id: sonderschicht_jetzt
        - condition: and
          conditions:
            - condition: trigger
              id: check_sonderschicht_geplant
            - condition: state
              entity_id: input_boolean.chlorinator_sonderschicht_geplant
              state: 'on'
    action:
      # Pumpe an
      - service: switch.turn_on
        target:
          entity_id: switch.0xa4c138a1288e6b94
      # Chlorinator aus => Restart
      - service: switch.turn_off
        target:
          entity_id: switch.0xa4c1381ed732dbe2
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      # Chlorinator an
      - service: switch.turn_on
        target:
          entity_id: switch.0xa4c1381ed732dbe2
      # Chlorinator morgen wieder zur normalen Zeit an
      - service: automation.turn_on
        target:
          entity_id: automation.pool_auto_starte_chlorinator
      # Reset geplante Sonderschicht
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.chlorinator_sonderschicht_geplant
      - service: notify.telegram_jo
        data:
          message: 'Habe Chlorinator Sonderschicht gestartet'
  - id: 'd431661c-bc02-447b-bbda-8df1d72afedc'
    alias: Pool - Heizung vergessen
    description: ''
    mode: queued
    trigger:
      - platform: time
        at: "21:00:01"
        id: heizung_vergessen
      - platform: state
        entity_id: binary_sensor.pool_heizung_lauft
        to: "on"
        id: heizung_an
      - platform: state
        entity_id: binary_sensor.pool_heizung_lauft
        to: "off"
        id: heizung_aus
    condition: []
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: heizung_vergessen
          - condition: state
            entity_id: input_boolean.pool_heizung_auch_bezahlstrom
            state: 'off'
          sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.0xa4c138b64253ef10
        - conditions:
          - condition: trigger
            id: heizung_vergessen
          - condition: state
            entity_id: input_boolean.pool_heizung_auch_bezahlstrom
            state: 'on'
          sequence:
          - service: notify.telegram_jo
            data:
              message: 'Pool heizt noch, aber der Schalter, dass die Pool-Heizung auch mit Bezahlstrom laufen soll, ist ja auch gedrückt'
#        - conditions:
#          - condition: trigger
#            id: heizung_an
#          sequence:
#          - service: notify.telegram_jo
#            data:
#              message: 'Pool-Heizung an'
#        - conditions:
#          - condition: trigger
#            id: heizung_aus
#          sequence:
#          - service: notify.telegram_jo
#            data:
#              message: 'Pool-Heizung aus'
  - id: 'e174e01b-f336-4100-a4fb-30b2c253dad1'
    alias: Pool - Heizung automatisch
    description: ''
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.pool_auto_heizung_heize_jetzt
        to: "on"
        id: heizung_an
        for: "00:30:00"
      - platform: state
        entity_id: binary_sensor.pool_auto_heizung_heize_jetzt
        to: "off"
        id: heizung_aus
        for: "00:20:00"
      - platform: state
        entity_id: binary_sensor.pool_auto_heizung_hat_freigabe_heizt_aber_nicht
        to: "on"
        id: zieltemperatur_wohl_erreicht
        for: "00:20:00"
      - platform: time
        at: "02:00:00"
        id: zieltemperatur_reset
    condition: []
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: heizung_an
          sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.0xa4c138b64253ef10
      - choose:
        - conditions:
          - condition: trigger
            id: heizung_aus
          sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.0xa4c138b64253ef10
      - choose:
        - conditions:
          - condition: trigger
            id: zieltemperatur_wohl_erreicht
          sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.zieltemperatur_pool
            data:
              value: 20
      - choose:
        - conditions:
          - condition: trigger
            id: zieltemperatur_reset
          sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.zieltemperatur_pool
            data:
              value: 30