sensor:
  - platform: powercalc
    create_group: Bekannte Verbraucher
    entities:
      - create_group: Alle Lichter
        entities:
          - create_group: Lichter Küche
            entities:
              - entity_id: light.arbeitsplatte
                linear:
                  min_power: 2
                  max_power: 90
                  gamma_curve: 4
                disable_standby_power: true
              - entity_id: light.panels_kuche
                linear:
                  min_power: 1
                  max_power: 24
                  gamma_curve: 4
                disable_standby_power: true
              - entity_id: light.panels_bar
                linear:
                  min_power: 1
                  max_power: 16
                  gamma_curve: 4
                disable_standby_power: true
              - entity_id: light.sockelbeleuchtung
                linear:
                  min_power: 2
                  max_power: 28
                  gamma_curve: 4
                disable_standby_power: true
          - create_group: Lichter Esszimmer
            entities:
              - entity_id: light.panels_esszimmer
                linear:
                  min_power: 1
                  max_power: 32
                  gamma_curve: 4
                disable_standby_power: true
              - entity_id: light.wandleuchten_esszimmer_hell
                linear:
                  min_power: 1
                  max_power: 34
                  gamma_curve: 4
                disable_standby_power: true
              - entity_id: light.wandleuchten_esszimmer_gemutlich
                linear:
                  min_power: 1
                  max_power: 25
                  gamma_curve: 4
                disable_standby_power: true
          - create_group: Lichter Wohnzimmer
            entities:
              - entity_id: light.panels_wohnzimmer
                linear:
                  min_power: 1
                  max_power: 32
                  gamma_curve: 4
                disable_standby_power: true
              - entity_id: light.schrankbeleuchtung_wohnzimmer
                linear:
                  min_power: 1
                  max_power: 21
                  gamma_curve: 4
                disable_standby_power: true
              - entity_id: light.innr_e27_color_stehlampe_wz_level_light_color_on_off
                name: Stehlampe Wohnzimmer
                manufacturer: innr
                model: 'RB 285 C'