template: 
  - binary_sensor:
      - name: dwd_weather_warnings_active
        state: >
          {% if (states('sensor.dwd_weather_warnings_advance_warning_level') | float(0) > 0) or (states('sensor.dwd_weather_warnings_current_warning_level') | float(0) > 0) %}
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}

input_text:
  helper_wetterwarnungen_bekannte_ids:
    max: 255

automation:
  - id: '01da7c50-7db6-4729-83e7-95910acdd914'
    alias: Wetter-Warnungen
    description: ''
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.dwd_weather_warnings_active
        from: 'off'
        to: 'on'
        id: dwd_weather_warnings_active
      - platform: state
        entity_id: binary_sensor.dwd_weather_warnings_active
        to: 'off'
        for: '00:35:00'
        id: dwd_weather_warnings_inactive
      - platform: state
        entity_id: sensor.dwd_weather_warnings_advance_warning_level
        id: warnings_changed
      - platform: state
        entity_id: sensor.dwd_weather_warnings_current_warning_level
        id: warnings_changed
    condition: []
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: dwd_weather_warnings_active
          sequence:
          - service: notify.telegram_jo
            data:
              message: 'Wetterwarnung'
        - conditions:
          - condition: trigger
            id: dwd_weather_warnings_inactive
          sequence:
          - service: input_text.set_value
            data:
              value: 'inactive'
            target:
              entity_id: input_text.helper_wetterwarnungen_bekannte_ids
        - conditions:
          - condition: trigger
            id: warnings_changed
          sequence:
          - repeat:
              count: "{{ state_attr('sensor.dwd_weather_warnings_advance_warning_level','warning_count') | int(0) }}"
              sequence:
                - service: notify.telegram_jo
                  data:
                    message: >
                      {% set t_start = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                      {% set t_end = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                      {% set event = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_name') %}
                      {% set level = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_level') %}
                      {% set event_fix = event[:5] %}
                      {% set str_hours = '{:03.0f}'.format((as_datetime(t_end) - as_datetime(t_start)).seconds / 3600) %}
                      {% set str_ts_start = '{:10.0f}'.format(as_timestamp(t_start)) %}
                      {% set str_level = '{:1.0f}'.format(level) %}
                      {% set id = (event_fix + '-' + str_ts_start + '-' + str_hours + '-' + str_level) | slugify(separator='-') %}
                      {{ id }}
                - condition: template
                  value_template: >
                    {% set t_start = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                    {% set t_end = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                    {% set event = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_name') %}
                    {% set level = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_level') %}
                    {% set event_fix = event[:5] %}
                    {% set str_hours = '{:03.0f}'.format((as_datetime(t_end) - as_datetime(t_start)).seconds / 3600) %}
                    {% set str_ts_start = '{:10.0f}'.format(as_timestamp(t_start)) %}
                    {% set str_level = '{:1.0f}'.format(level) %}
                    {% set id = (event_fix + '-' + str_ts_start + '-' + str_hours + '-' + str_level) | slugify(separator='-') %}
                    {{ id not in states('input_text.helper_wetterwarnungen_bekannte_ids') }}
                - service: notify.telegram_jo
                  data:
                    message: 'neue Wetterwarnung erkannt'
                - service: notify.telegram_jo
                  data:
                    message: >
                      {% set headline = state_attr("sensor.dwd_weather_warnings_advance_warning_level", "warning_" ~ loop.index ~ "_headline") %}
                      {% set description = state_attr("sensor.dwd_weather_warnings_advance_warning_level", "warning_" ~ loop.index ~ "_description") %}
                      {% set level = state_attr("sensor.sensor.dwd_weather_warnings_advance_warning_level", "warning_" ~ loop.index ~ "_level") %}
                      {% set time_start = as_local(state_attr("sensor.dwd_weather_warnings_advance_warning_level", "warning_" ~ loop.index ~ "_start")) %}
                      {% set weekday_start = as_timestamp(time_start) | timestamp_custom("%w", True) | int %}
                      {% set time_end = as_local(state_attr("sensor.dwd_weather_warnings_advance_warning_level", "warning_" ~ loop.index ~ "_end")) %}
                      {% set weekday_end = as_timestamp(time_end) | timestamp_custom("%w", True) | int %}
                      {% set zeit = ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday_start-1] ~ ", " ~ time_start.strftime("%H:%M") ~ " bis " ~ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday_end-1] ~ ", " ~ time_end.strftime("%H:%M") %}
                      {{ headline + ' von ' + zeit + ': ' + description }}
                - service: input_text.set_value
                  data:
                    value: >
                      {% set t_start = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                      {% set t_end = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                      {% set event = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_name') %}
                      {% set level = state_attr('sensor.dwd_weather_warnings_advance_warning_level', 'warning_' ~ loop.index ~ '_level') %}
                      {% set event_fix = event[:5] %}
                      {% set str_hours = '{:03.0f}'.format((as_datetime(t_end) - as_datetime(t_start)).seconds / 3600) %}
                      {% set str_ts_start = '{:10.0f}'.format(as_timestamp(t_start)) %}
                      {% set str_level = '{:1.0f}'.format(level) %}
                      {% set new_id = (event_fix + '-' + str_ts_start + '-' + str_hours + '-' + str_level) | slugify(separator='-') %}
                      {% set ns = namespace() %}
                      {% set ns.ids = '' %}
                      {% for id in states('input_text.helper_wetterwarnungen_bekannte_ids').split(',') %}
                        {% if id != 'inactive' %}
                          {% if ns.ids == '' %}
                            {% set ns.ids = ns.ids + id %}
                          {% else %}
                            {% set ns.ids = ns.ids + ',' + id %}
                          {% endif %}
                        {% endif %}
                      {% endfor %}
                      {% if ns.ids == '' %}
                        {% set ns.ids = ns.ids + new_id %}
                      {% else %}
                        {% set ns.ids = ns.ids + ',' + new_id %}
                      {% endif %}
                      {{ ns.ids }}
                  target:
                    entity_id: input_text.helper_wetterwarnungen_bekannte_ids
          - repeat:
              count: "{{ state_attr('sensor.dwd_weather_warnings_current_warning_level','warning_count') | int(0) }}"
              sequence:
                - service: notify.telegram_jo
                  data:
                    message: >
                      {% set t_start = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                      {% set t_end = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                      {% set event = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_name') %}
                      {% set level = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_level') %}
                      {% set event_fix = event[:5] %}
                      {% set str_hours = '{:03.0f}'.format((as_datetime(t_end) - as_datetime(t_start)).seconds / 3600) %}
                      {% set str_ts_start = '{:10.0f}'.format(as_timestamp(t_start)) %}
                      {% set str_level = '{:1.0f}'.format(level) %}
                      {% set id = (event_fix + '-' + str_ts_start + '-' + str_hours + '-' + str_level) | slugify(separator='-') %}
                      {{ id }}
                - condition: template
                  value_template: >
                    {% set t_start = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                    {% set t_end = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                    {% set event = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_name') %}
                    {% set level = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_level') %}
                    {% set event_fix = event[:5] %}
                    {% set str_hours = '{:03.0f}'.format((as_datetime(t_end) - as_datetime(t_start)).seconds / 3600) %}
                    {% set str_ts_start = '{:10.0f}'.format(as_timestamp(t_start)) %}
                    {% set str_level = '{:1.0f}'.format(level) %}
                    {% set id = (event_fix + '-' + str_ts_start + '-' + str_hours + '-' + str_level) | slugify(separator='-') %}
                    {{ id not in states('input_text.helper_wetterwarnungen_bekannte_ids') }}
                - service: notify.telegram_jo
                  data:
                    message: 'neue Wetterwarnung erkannt'
                - service: notify.telegram_jo
                  data:
                    message: >
                      {% set headline = state_attr("sensor.dwd_weather_warnings_current_warning_level", "warning_" ~ loop.index ~ "_headline") %}
                      {% set description = state_attr("sensor.dwd_weather_warnings_current_warning_level", "warning_" ~ loop.index ~ "_description") %}
                      {% set level = state_attr("sensor.sensor.dwd_weather_warnings_current_warning_level", "warning_" ~ loop.index ~ "_level") %}
                      {% set time_start = as_local(state_attr("sensor.dwd_weather_warnings_current_warning_level", "warning_" ~ loop.index ~ "_start")) %}
                      {% set weekday_start = as_timestamp(time_start) | timestamp_custom("%w", True) | int %}
                      {% set time_end = as_local(state_attr("sensor.dwd_weather_warnings_current_warning_level", "warning_" ~ loop.index ~ "_end")) %}
                      {% set weekday_end = as_timestamp(time_end) | timestamp_custom("%w", True) | int %}
                      {% set zeit = ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday_start-1] ~ ", " ~ time_start.strftime("%H:%M") ~ " bis " ~ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday_end-1] ~ ", " ~ time_end.strftime("%H:%M") %}
                      {{ headline + ' von ' + zeit + ': ' + description }}
                - service: input_text.set_value
                  data:
                    value: >
                      {% set t_start = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                      {% set t_end = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_start') %}
                      {% set event = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_name') %}
                      {% set level = state_attr('sensor.dwd_weather_warnings_current_warning_level', 'warning_' ~ loop.index ~ '_level') %}
                      {% set event_fix = event[:5] %}
                      {% set str_hours = '{:03.0f}'.format((as_datetime(t_end) - as_datetime(t_start)).seconds / 3600) %}
                      {% set str_ts_start = '{:10.0f}'.format(as_timestamp(t_start)) %}
                      {% set str_level = '{:1.0f}'.format(level) %}
                      {% set new_id = (event_fix + '-' + str_ts_start + '-' + str_hours + '-' + str_level) | slugify(separator='-') %}
                      {% set ns = namespace() %}
                      {% set ns.ids = '' %}
                      {% for id in states('input_text.helper_wetterwarnungen_bekannte_ids').split(',') %}
                        {% if id != 'inactive' %}
                          {% if ns.ids == '' %}
                            {% set ns.ids = ns.ids + id %}
                          {% else %}
                            {% set ns.ids = ns.ids + ',' + id %}
                          {% endif %}
                        {% endif %}
                      {% endfor %}
                      {% if ns.ids == '' %}
                        {% set ns.ids = ns.ids + new_id %}
                      {% else %}
                        {% set ns.ids = ns.ids + ',' + new_id %}
                      {% endif %}
                      {{ ns.ids }}
                  target:
                    entity_id: input_text.helper_wetterwarnungen_bekannte_ids
        default: []