template: 
  - binary_sensor:
      - name: dwd_weather_warnings_active
        state: >
          {% if (states('sensor.dwd_weather_warnings_advance_warning_level') | float(0) > 0) or (states('sensor.dwd_weather_warnings_current_warning_level') | float(0) > 0) %}
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}

input_text:
  helper_wetterwarnungen_bekannte_ids:
    max: 255

automation:
  - id: '01da7c50-7db6-4729-83e7-95910acdd914'
    alias: Wetter-Warnungen
    description: ''
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.dwd_weather_warnings_active
        from: 'off'
        to: 'on'
        id: dwd_weather_warnings_active
      - platform: state
        entity_id: binary_sensor.dwd_weather_warnings_active
        to: 'off'
        for: '00:35:00'
        id: dwd_weather_warnings_inactive
    condition: []
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: dwd_weather_warnings_active
          sequence:
          - service: notify.telegram_jo
            data:
              message: 'Wetterwarnung'
        - conditions:
          - condition: trigger
            id: dwd_weather_warnings_inactive
          sequence:
          - service: input_text.set_value
            data:
              value: 'inactive'
            target:
              entity_id: input_text.helper_wetterwarnungen_bekannte_ids
        default: []